In [2]:
import numpy as np
import pandas as pd

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 2.3.5
Pandas: 2.3.3

In [3]:
import pandas as pd
import numpy as np

calendar = pd.read_csv("data/calendar.csv")

calendar.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [4]:
print("Shape:", calendar.shape)
print("\nColumns:")
print(calendar.columns.tolist())

print("\nData types:")
calendar.info()

Shape: (1969, 14)

Columns:
['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2', 'snap_CA', 'snap_TX', 'snap_WI']

Data types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   object
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   object
 3   wday          1969 non-null   int64
 4   month         1969 non-null   int64
 5   year          1969 non-null   int64
 6   d             1969 non-null   object
 7   event_name_1  162 non-null    object
 8   event_type_1  162 non-null    object
 9   event_name_2  5 non-null      object
 10  event_type_2  5 non-null      object
 11  snap_CA       1969 non-null   int64
 12  snap_TX       1969 non-null   int64
 13  snap_WI       1969 non-null   int64
dtypes: int64(7), object(7)
memory usage: 215.5+ KB

In [7]:
sell_prices = pd.read_csv("data/sell_prices.csv")

print("Shape:", sell_prices.shape)
sell_prices.head()

Shape: (6841121, 4)

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [8]:
sales = pd.read_csv("data/sales_train_evaluation.csv")

print("Shape:", sales.shape)
sales.head()

Shape: (30490, 1947)

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,1,0,4,0,1,3,0,2,6
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,2,1,0,0,2,1,0

In [9]:
print("Shape:", sales.shape)
print(sales.columns[:15].tolist())
print(sales[["item_id", "dept_id", "cat_id", "store_id", "state_id"]].head())

Shape: (30490, 1947)
['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1', 'd_2', 'd_3', 'd_4', 'd_5', 'd_6', 'd_7', 'd_8', 'd_9']
         item_id    dept_id   cat_id store_id state_id
0  HOBBIES_1_001  HOBBIES_1  HOBBIES     CA_1       CA
1  HOBBIES_1_002  HOBBIES_1  HOBBIES     CA_1       CA
2  HOBBIES_1_003  HOBBIES_1  HOBBIES     CA_1       CA
3  HOBBIES_1_004  HOBBIES_1  HOBBIES     CA_1       CA
4  HOBBIES_1_005  HOBBIES_1  HOBBIES     CA_1       CA

In [11]:
sales_ca1 = sales[sales["store_id"] == "CA_1"].copy()

print(sales_ca1.shape)

(3049, 1947)

In [12]:
id_cols = [
    "id",
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id"
]

sales_long = sales_ca1.melt(
    id_vars=id_cols,
    var_name="d",
    value_name="demand"
)

sales_long.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0

In [13]:
dataset = sales_long.merge(
    calendar,
    on="d",
    how="left"
)

dataset[[
    "item_id",
    "store_id",
    "date",
    "weekday",
    "demand",
    "wm_yr_wk"
]].head()

         item_id store_id        date   weekday  demand  wm_yr_wk
0  HOBBIES_1_001     CA_1  2011-01-29  Saturday       0     11101
1  HOBBIES_1_002     CA_1  2011-01-29  Saturday       0     11101
2  HOBBIES_1_003     CA_1  2011-01-29  Saturday       0     11101
3  HOBBIES_1_004     CA_1  2011-01-29  Saturday       0     11101
4  HOBBIES_1_005     CA_1  2011-01-29  Saturday       0     11101

In [14]:
print("Shape:", dataset.shape)
print("Missing dates:", dataset["date"].isna().sum())

Shape: (5918109, 21)
Missing dates: 0

In [17]:
print([col for col in dataset.columns if "price" in col])

['sell_price_x', 'sell_price_y']

In [19]:
dataset[[
    "item_id",
    "store_id",
    "date",
    "weekday",
    "sell_price_x",
    "sell_price_y",
    "demand"
]].head()

,item_id,store_id,date,weekday,sell_price_x,sell_price_y,demand
0,HOBBIES_1_001,CA_1,2011-01-29,Saturday,NaN,NaN,0
1,HOBBIES_1_002,CA_1,2011-01-29,Saturday,NaN,NaN,0
2,HOBBIES_1_003,CA_1,2011-01-29,Saturday,NaN,NaN,0
3,HOBBIES_1_004,CA_1,2011-01-29,Saturday,NaN,NaN,0
4,HOBBIES_1_005,CA_1,2011-01-29,Saturday,NaN,NaN,0

In [20]:
dataset = sales_long.merge(
    calendar,
    on="d",
    how="left"
)

dataset = dataset.merge(
    sell_prices,
    on=["store_id", "item_id", "wm_yr_wk"],
    how="left"
)

dataset[[
    "item_id",
    "store_id",
    "date",
    "weekday",
    "sell_price",
    "demand"
]].head()

         item_id store_id        date   weekday  sell_price  demand
0  HOBBIES_1_001     CA_1  2011-01-29  Saturday         NaN       0
1  HOBBIES_1_002     CA_1  2011-01-29  Saturday         NaN       0
2  HOBBIES_1_003     CA_1  2011-01-29  Saturday         NaN       0
3  HOBBIES_1_004     CA_1  2011-01-29  Saturday         NaN       0
4  HOBBIES_1_005     CA_1  2011-01-29  Saturday         NaN       0

In [21]:
print("Shape:", dataset.shape)
print("Missing prices:", dataset["sell_price"].isna().sum())
print("Missing price %:", dataset["sell_price"].isna().mean() * 100)

Shape: (5918109, 22)
Missing prices: 1129842
Missing price %: 19.091267159830952

In [22]:
model_data = dataset.dropna(subset=["sell_price"]).copy()

print("Original rows:", len(dataset))
print("Usable rows:", len(model_data))
print("Rows removed:", len(dataset) - len(model_data))

model_data[[
    "date",
    "item_id",
    "store_id",
    "sell_price",
    "demand"
]].head()

Original rows: 5918109
Usable rows: 4788267
Rows removed: 1129842

          date        item_id store_id  sell_price  demand
7   2011-01-29  HOBBIES_1_008     CA_1        0.46      12
8   2011-01-29  HOBBIES_1_009     CA_1        1.56       2
9   2011-01-29  HOBBIES_1_010     CA_1        3.17       0
11  2011-01-29  HOBBIES_1_012     CA_1        5.98       0
14  2011-01-29  HOBBIES_1_015     CA_1        0.70       4

In [23]:
model_data[["sell_price", "demand"]].describe()

         sell_price        demand
count  4.788267e+06  4.788267e+06
mean   4.412670e+00  1.635717e+00
std    3.397716e+00  4.448240e+00
min    1.000000e-02  0.000000e+00
25%    2.220000e+00  0.000000e+00
50%    3.470000e+00  0.000000e+00
75%    5.770000e+00  2.000000e+00
max    3.098000e+01  6.480000e+02

In [24]:
zero_demand_pct = (model_data["demand"] == 0).mean() * 100

print("Zero-demand observations:", round(zero_demand_pct, 2), "%")
print("Total units sold:", model_data["demand"].sum())
print("Average price:", round(model_data["sell_price"].mean(), 2))

Zero-demand observations: 55.21 %
Total units sold: 7832248
Average price: 4.41

In [25]:
zero_demand_pct = (model_data["demand"] == 0).mean() * 100

print("Zero-demand observations:", round(zero_demand_pct, 2), "%")
print("Total units sold:", model_data["demand"].sum())
print("Average price:", round(model_data["sell_price"].mean(), 2))

Zero-demand observations: 55.21 %
Total units sold: 7832248
Average price: 4.41

In [26]:
model_data["revenue"] = (
    model_data["sell_price"] * model_data["demand"]
)

model_data[[
    "date",
    "item_id",
    "sell_price",
    "demand",
    "revenue"
]].head(10)

          date        item_id  sell_price  demand  revenue
7   2011-01-29  HOBBIES_1_008        0.46      12     5.52
8   2011-01-29  HOBBIES_1_009        1.56       2     3.12
9   2011-01-29  HOBBIES_1_010        3.17       0     0.00
11  2011-01-29  HOBBIES_1_012        5.98       0     0.00
14  2011-01-29  HOBBIES_1_015        0.70       4     2.80
15  2011-01-29  HOBBIES_1_016        0.70       5     3.50
21  2011-01-29  HOBBIES_1_022        6.86       2    13.72
22  2011-01-29  HOBBIES_1_023        3.44       2     6.88
27  2011-01-29  HOBBIES_1_028        6.67       0     0.00
28  2011-01-29  HOBBIES_1_029        7.44       2    14.88

In [27]:
# Convert date to a real datetime variable
model_data["date"] = pd.to_datetime(model_data["date"])

# Create time features
model_data["day_of_week"] = model_data["date"].dt.dayofweek
model_data["month"] = model_data["date"].dt.month
model_data["year"] = model_data["date"].dt.year

model_data[[
    "date",
    "day_of_week",
    "month",
    "year",
    "sell_price",
    "demand",
    "revenue"
]].head()

         date  day_of_week  month  year  sell_price  demand  revenue
7  2011-01-29            5      1  2011        0.46      12     5.52
8  2011-01-29            5      1  2011        1.56       2     3.12
9  2011-01-29            5      1  2011        3.17       0     0.00
11 2011-01-29            5      1  2011        5.98       0     0.00
14 2011-01-29            5      1  2011        0.70       4     2.80

In [30]:
import gc

del sales_ca1
del sales_long
del dataset

gc.collect()

3166

In [35]:
model_data.sort_values(
    ["store_id", "item_id", "date"],
    inplace=True
)

In [36]:
model_data["demand_lag_1"] = (
    model_data.groupby("item_id")["demand"]
    .shift(1)
)

model_data["demand_lag_7"] = (
    model_data.groupby("item_id")["demand"]
    .shift(7)
)

In [47]:
model_data[
    model_data["item_id"] == "HOBBIES_1_008"
][[
    "date",
    "demand",
    "demand_lag_1",
    "demand_lag_7"
]].head(15)

            date  demand  demand_lag_1  demand_lag_7
7     2011-01-29      12           NaN           NaN
3056  2011-01-30      15          12.0           NaN
6105  2011-01-31       0          15.0           NaN
9154  2011-02-01       0           0.0           NaN
12203 2011-02-02       0           0.0           NaN
15252 2011-02-03       4           0.0           NaN
18301 2011-02-04       6           4.0           NaN
21350 2011-02-05       5           6.0          12.0
24399 2011-02-06       7           5.0          15.0
27448 2011-02-07       0           7.0           0.0
30497 2011-02-08      13           0.0           0.0
33546 2011-02-09       2          13.0           0.0
36595 2011-02-10       2           2.0           4.0
39644 2011-02-11      20           2.0           6.0
42693 2011-02-12       9          20.0           5.0

In [49]:
model_data["rolling_mean_7"] = (
    model_data.groupby("item_id")["demand"]
    .transform(lambda x: x.shift(1).rolling(7).mean())
)

In [52]:
model_data[
    model_data["item_id"] == "HOBBIES_1_008"
][[
    "date",
    "demand",
    "demand_lag_1",
    "demand_lag_7",
    "rolling_mean_7"
]].head(15)

            date  demand  demand_lag_1  demand_lag_7  rolling_mean_7
7     2011-01-29      12           NaN           NaN             NaN
3056  2011-01-30      15          12.0           NaN             NaN
6105  2011-01-31       0          15.0           NaN             NaN
9154  2011-02-01       0           0.0           NaN             NaN
12203 2011-02-02       0           0.0           NaN             NaN
15252 2011-02-03       4           0.0           NaN             NaN
18301 2011-02-04       6           4.0           NaN             NaN
21350 2011-02-05       5           6.0          12.0        5.285714
24399 2011-02-06       7           5.0          15.0        4.285714
27448 2011-02-07       0           7.0           0.0        3.142857
30497 2011-02-08      13           0.0           0.0        3.142857
33546 2011-02-09       2          13.0           0.0        5.000000
36595 2011-02-10       2           2.0           4.0        5.285714
39644 2011-02-11      20           2.0           6.0        5.000000
42693 2011-02-12       9          20.0           5.0        7.000000

In [57]:
model_data["rolling_mean_28"] = (
    model_data.groupby("item_id")["demand"]
    .transform(lambda x: x.shift(1).rolling(28).mean())
)

In [56]:
model_data[
    model_data["item_id"] == "HOBBIES_1_008"
][[
    "date",
    "demand",
    "rolling_mean_7",
    "rolling_mean_28"
]].head(35)

             date  demand  rolling_mean_7  rolling_mean_28
7      2011-01-29      12             NaN              NaN
3056   2011-01-30      15             NaN              NaN
6105   2011-01-31       0             NaN              NaN
9154   2011-02-01       0             NaN              NaN
12203  2011-02-02       0             NaN              NaN
15252  2011-02-03       4             NaN              NaN
18301  2011-02-04       6             NaN              NaN
21350  2011-02-05       5        5.285714              NaN
24399  2011-02-06       7        4.285714              NaN
27448  2011-02-07       0        3.142857              NaN
30497  2011-02-08      13        3.142857              NaN
33546  2011-02-09       2        5.000000              NaN
36595  2011-02-10       2        5.285714              NaN
39644  2011-02-11      20        5.000000              NaN
42693  2011-02-12       9        7.000000              NaN
45742  2011-02-13       3        7.571429              NaN
48791  2011-02-14       0        7.000000              NaN
51840  2011-02-15       1        7.000000              NaN
54889  2011-02-16       0        5.285714              NaN
57938  2011-02-17       0        5.000000              NaN
60987  2011-02-18       0        4.714286              NaN
64036  2011-02-19      10        1.857143              NaN
67085  2011-02-20       4        2.000000              NaN
70134  2011-02-21       4        2.142857              NaN
73183  2011-02-22       2        2.714286              NaN
76232  2011-02-23       6        2.857143              NaN
79281  2011-02-24       2        3.714286              NaN
82330  2011-02-25       0        4.000000              NaN
85379  2011-02-26       0        4.000000         4.535714
88428  2011-02-27       0        2.571429         4.107143
91477  2011-02-28       0        2.000000         3.571429
94526  2011-03-01       0        1.428571         3.571429
97575  2011-03-02       0        1.142857         3.571429
100624 2011-03-03       0        0.285714         3.571429
103673 2011-03-04       0        0.000000         3.428571

In [58]:
features = [
    "sell_price",
    "day_of_week",
    "month",
    "year",
    "demand_lag_1",
    "demand_lag_7",
    "rolling_mean_7",
    "rolling_mean_28"
]

ml_data = model_data.dropna(
    subset=features + ["demand"]
)

print(ml_data.shape)
ml_data[features + ["demand"]].head()

(4702895, 28)

,sell_price,day_of_week,month,year,demand_lag_1,demand_lag_7,rolling_mean_7,rolling_mean_28,demand
86984,2.0,5,2,2011,4.0,1.0,1.857143,1.392857,2
90033,2.0,6,2,2011,2.0,2.0,2.000000,1.357143,2
93082,2.0,0,2,2011,2.0,0.0,2.000000,1.428571,0
96131,2.0,1,3,2011,0.0,2.0,2.000000,1.428571,2
99180,2.0,2,3,2011,2.0,2.0,2.000000,1.464286,1

In [59]:
print("First date:", ml_data["date"].min())
print("Last date:", ml_data["date"].max())
print("Number of rows:", len(ml_data))

First date: 2011-02-26 00:00:00
Last date: 2016-05-22 00:00:00
Number of rows: 4702895

In [60]:
cutoff_date = ml_data["date"].max() - pd.Timedelta(days=28)

train = ml_data[ml_data["date"] <= cutoff_date]
test = ml_data[ml_data["date"] > cutoff_date]

print("Cutoff:", cutoff_date)
print("Train:", train["date"].min(), "→", train["date"].max())
print("Test:", test["date"].min(), "→", test["date"].max())

print("Train rows:", len(train))
print("Test rows:", len(test))

Cutoff: 2016-04-24 00:00:00
Train: 2011-02-26 00:00:00 → 2016-04-24 00:00:00
Test: 2016-04-25 00:00:00 → 2016-05-22 00:00:00
Train rows: 4617523
Test rows: 85372

In [61]:
X_train = train[features]
y_train = train["demand"]

X_test = test[features]
y_test = test["demand"]

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X_train: (4617523, 8)
y_train: (4617523,)
X_test: (85372, 8)
y_test: (85372,)

In [62]:
from sklearn.ensemble import HistGradientBoostingRegressor

model = HistGradientBoostingRegressor(
    max_iter=100,
    learning_rate=0.1,
    max_depth=8,
    random_state=42
)

model.fit(X_train, y_train)

print("Model trained!")

Model trained!

In [63]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", round(mae, 3))
print("RMSE:", round(rmse, 3))
print("R²:", round(r2, 3))

MAE: 1.092
RMSE: 2.034
R²: 0.68

In [64]:
results = test[["date", "item_id", "sell_price", "demand"]].copy()
results["predicted_demand"] = y_pred

results[[
    "date",
    "item_id",
    "sell_price",
    "demand",
    "predicted_demand"
]].head(15)

              date      item_id  sell_price  demand  predicted_demand
5834349 2016-04-25  FOODS_1_001        2.24       2          1.015503
5837398 2016-04-26  FOODS_1_001        2.24       0          0.961141
5840447 2016-04-27  FOODS_1_001        2.24       0          0.848545
5843496 2016-04-28  FOODS_1_001        2.24       0          0.838746
5846545 2016-04-29  FOODS_1_001        2.24       0          0.954813
5849594 2016-04-30  FOODS_1_001        2.24       1          0.987492
5852643 2016-05-01  FOODS_1_001        2.24       1          1.107763
5855692 2016-05-02  FOODS_1_001        2.24       0          0.934803
5858741 2016-05-03  FOODS_1_001        2.24       6          0.625401
5861790 2016-05-04  FOODS_1_001        2.24       1          1.346806
5864839 2016-05-05  FOODS_1_001        2.24       0          0.909324
5867888 2016-05-06  FOODS_1_001        2.24       3          0.960359
5870937 2016-05-07  FOODS_1_001        2.24       0          1.606614
5873986 2016-05-08  FOODS_1_001        2.24       0          1.440795
5877035 2016-05-09  FOODS_1_001        2.24       0          0.934156

In [65]:
baseline_pred = X_test["demand_lag_1"]

baseline_mae = mean_absolute_error(y_test, baseline_pred)
baseline_rmse = np.sqrt(mean_squared_error(y_test, baseline_pred))
baseline_r2 = r2_score(y_test, baseline_pred)

print("BASELINE")
print("MAE:", round(baseline_mae, 3))
print("RMSE:", round(baseline_rmse, 3))
print("R²:", round(baseline_r2, 3))

print("\nAI MODEL")
print("MAE:", round(mae, 3))
print("RMSE:", round(rmse, 3))
print("R²:", round(r2, 3))

BASELINE
MAE: 1.348
RMSE: 2.761
R²: 0.411

AI MODEL
MAE: 1.092
RMSE: 2.034
R²: 0.68

In [66]:
evaluation = pd.DataFrame({
    "Model": ["Naive Lag-1", "HistGradientBoosting"],
    "MAE": [baseline_mae, mae],
    "RMSE": [baseline_rmse, rmse],
    "R2": [baseline_r2, r2]
})

evaluation

                  Model       MAE      RMSE        R2
0           Naive Lag-1  1.347702  2.761078  0.410787
1  HistGradientBoosting  1.092405  2.033618  0.680366

In [67]:
example = X_test.iloc[[0]].copy()

example

,sell_price,day_of_week,month,year,demand_lag_1,demand_lag_7,rolling_mean_7,rolling_mean_28
5834349,2.24,0,4,2016,0.0,4.0,1.142857,1.178571

In [68]:
price_grid = np.linspace(
    example["sell_price"].iloc[0] * 0.7,
    example["sell_price"].iloc[0] * 1.3,
    15
)

simulations = []

for price in price_grid:
    scenario = example.copy()
    scenario["sell_price"] = price

    predicted_demand = model.predict(scenario)[0]

    simulations.append({
        "price": price,
        "predicted_demand": predicted_demand,
        "predicted_revenue": price * max(predicted_demand, 0)
    })

price_simulation = pd.DataFrame(simulations)

price_simulation

    price  predicted_demand  predicted_revenue
0   1.568          1.055441           1.654931
1   1.664          1.055441           1.756253
2   1.760          1.028624           1.810378
3   1.856          1.028624           1.909126
4   1.952          1.024696           2.000206
5   2.048          1.015503           2.079751
6   2.144          1.015503           2.177239
7   2.240          1.015503           2.274727
8   2.336          1.015503           2.372216
9   2.432          1.015503           2.469704
10  2.528          1.015503           2.567192
11  2.624          1.015503           2.664681
12  2.720          1.015503           2.762169
13  2.816          1.015503           2.859657
14  2.912          1.015503           2.957146

In [71]:
model_data["item_avg_price"] = (
    model_data.groupby("item_id")["sell_price"]
    .transform("mean")
)

model_data["price_ratio"] = (
    model_data["sell_price"] /
    model_data["item_avg_price"]
)

model_data["price_discount_pct"] = (
    (model_data["item_avg_price"] - model_data["sell_price"])
    / model_data["item_avg_price"]
)

In [72]:
model_data[
    model_data["item_id"] == "HOBBIES_1_008"
][[
    "date",
    "sell_price",
    "item_avg_price",
    "price_ratio",
    "price_discount_pct",
    "demand"
]].head(20)

,date,sell_price,item_avg_price,price_ratio,price_discount_pct,demand
7,2011-01-29,0.46,0.476249,0.965881,0.034119,12
3056,2011-01-30,0.46,0.476249,0.965881,0.034119,15
6105,2011-01-31,0.46,0.476249,0.965881,0.034119,0
9154,2011-02-01,0.46,0.476249,0.965881,0.034119,0
12203,2011-02-02,0.46,0.476249,0.965881,0.034119,0
15252,2011-02-03,0.46,0.476249,0.965881,0.034119,4
18301,2011-02-04,0.46,0.476249,0.965881,0.034119,6
21350,2011-02-05,0.46,0.476249,0.965881,0.034119,5
24399,2011-02-06,0.46,0.476249,0.965881,0.034119,7
27448,2011-02-07,0.46,0.476249,0.965881,0.034119,0
30497,2011-02-08,0.46,0.476249,0.965881,0.034119,13
33546,2011-02-09,0.46,0.476249,0.965881,0.034119,2
36595,2011-02-10,0.46,0.476249,0.965881,0.034119,2
39644,2011-02-11,0.46,0.476249,0.965881,0.034119,20
42693,2011-02-12,0.46,0.476249,0.965881,0.034119,9
45742,2011-02-13,0.46,0.476249,0.965881,0.034119,3
48791,2011-02-14,0.46,0.476249,0.965881,0.034119,0
51840,2011-02-15,0.46,0.476249,0.965881,0.034119,1
54889,2011-02-16,0.46,0.476249,0.965881,0.034119,0
57938,2011-02-17,0.46,0.476249,0.965881,0.034119,0

In [73]:
price_variation = (
    model_data.groupby("item_id")["sell_price"]
    .agg(["min", "max", "mean", "std", "nunique"])
)

price_variation["price_range_pct"] = (
    (price_variation["max"] - price_variation["min"])
    / price_variation["mean"]
)

price_variation.sort_values(
    "price_range_pct",
    ascending=False
).head(20)

                  min    max       mean       std  nunique  price_range_pct
item_id
HOUSEHOLD_1_266  1.00   2.88   1.017856  0.182472        2         1.847019
HOUSEHOLD_1_443  0.01   2.64   2.519911  0.181509        4         1.043687
HOBBIES_2_075    0.05   2.88   2.759253  0.198839        5         1.025640
HOBBIES_2_149    0.97   2.47   1.559572  0.732968        2         0.961802
HOUSEHOLD_2_497  1.00   6.48   5.780252  0.591591        4         0.948055
HOUSEHOLD_1_077  1.00   6.98   6.473170  0.449358        4         0.923813
HOUSEHOLD_1_189  1.00   5.88   5.430695  0.717412        4         0.898596
HOUSEHOLD_1_165  2.00  17.97  17.897173  1.076338        2         0.892320
HOUSEHOLD_1_491  1.00   6.48   6.380617  0.526226        4         0.858851
HOBBIES_2_042    0.74   1.47   0.882785  0.212149        3         0.826928
HOBBIES_1_333    0.97   4.97   4.952086  0.267174        2         0.807740
HOUSEHOLD_2_448  0.99   4.97   4.930313  0.395728        2         0.807251
HOUSEHOLD_2_384  2.00   6.48   5.675801  0.586923        6         0.789316
HOUSEHOLD_1_419  2.00   8.94   8.897757  0.540036        2         0.779972
FOODS_1_158      1.34   4.98   4.677303  0.224611        3         0.778226
HOBBIES_2_062    1.47   5.88   5.699860  0.493290        3         0.773703
HOUSEHOLD_2_387  2.00   6.48   5.829241  0.863794        4         0.768539
HOUSEHOLD_1_109  1.00   3.97   3.864549  0.296652        3         0.768524
HOUSEHOLD_2_026  1.00   3.97   3.933376  0.327863        2         0.755076
HOUSEHOLD_2_077  3.48   6.67   4.302881  1.396827        2         0.741364

In [74]:
candidate_stats = (
    model_data.groupby("item_id")
    .agg(
        min_price=("sell_price", "min"),
        max_price=("sell_price", "max"),
        avg_price=("sell_price", "mean"),
        unique_prices=("sell_price", "nunique"),
        observations=("demand", "size"),
        total_demand=("demand", "sum"),
        selling_days=("demand", lambda x: (x > 0).sum())
    )
)

candidate_stats["price_range_pct"] = (
    (candidate_stats["max_price"] - candidate_stats["min_price"])
    / candidate_stats["avg_price"]
)

candidates = candidate_stats[
    (candidate_stats["unique_prices"] >= 4) &
    (candidate_stats["selling_days"] >= 100)
].sort_values(
    "price_range_pct",
    ascending=False
)

candidates.head(15)

,min_price,max_price,avg_price,unique_prices,observations,total_demand,selling_days,price_range_pct
item_id,,,,,,,,
HOUSEHOLD_1_443,0.01,2.64,2.519911,4,1920,2965,1186,1.043687
HOBBIES_2_075,0.05,2.88,2.759253,5,1927,1525,731,1.025640
HOUSEHOLD_2_497,1.00,6.48,5.780252,4,1941,351,285,0.948055
HOUSEHOLD_1_077,1.00,6.98,6.473170,4,1227,819,506,0.923813
HOUSEHOLD_1_189,1.00,5.88,5.430695,4,1899,302,214,0.898596
HOUSEHOLD_1_491,1.00,6.48,6.380617,4,1038,637,414,0.858851
HOUSEHOLD_2_384,2.00,6.48,5.675801,6,1941,453,350,0.789316
HOUSEHOLD_2_387,2.00,6.48,5.829241,4,1199,245,193,0.768539
HOUSEHOLD_1_407,1.48,5.24,5.182626,4,1192,820,540,0.725501
FOODS_2_211,0.99,2.64,2.305930,5,1941,1813,941,0.715546
FOODS_2_177,1.00,3.33,3.278548,5,1570,1175,599,0.710681
HOBBIES_1_112,1.00,2.72,2.676979,4,1920,203,170,0.642515
HOBBIES_1_295,0.20,0.50,0.475023,5,1941,13115,1465,0.631548
HOUSEHOLD_2_445,3.00,6.48,5.649536,4,1941,407,329,0.615980
FOODS_1_133,1.74,3.48,3.184601,8,1941,1670,672,0.546379

In [75]:
product_id = "HOBBIES_1_295"

product_data = model_data[
    model_data["item_id"] == product_id
]

price_demand = (
    product_data.groupby("sell_price")
    .agg(
        avg_demand=("demand", "mean"),
        median_demand=("demand", "median"),
        total_demand=("demand", "sum"),
        observations=("demand", "size")
    )
    .reset_index()
)

price_demand

   sell_price  avg_demand  median_demand  total_demand  observations
0        0.20    5.714286            0.0            40             7
1        0.42   18.174603           13.0          1145            63
2        0.46    6.375750            5.0          5311           833
3        0.48    6.473815            4.0          2596           401
4        0.50    6.315542            3.0          4023           637

In [76]:
product_data[["sell_price", "demand"]].corr()

            sell_price    demand
sell_price    1.000000 -0.092937
demand       -0.092937  1.000000

In [77]:
from sklearn.linear_model import LinearRegression
import numpy as np

elasticity_data = price_demand[
    (price_demand["avg_demand"] > 0) &
    (price_demand["sell_price"] > 0)
].copy()

X_elasticity = np.log(
    elasticity_data[["sell_price"]]
)

y_elasticity = np.log(
    elasticity_data["avg_demand"]
)

elasticity_model = LinearRegression()

elasticity_model.fit(
    X_elasticity,
    y_elasticity,
    sample_weight=elasticity_data["observations"]
)

elasticity = elasticity_model.coef_[0]

print("Estimated price elasticity:", round(elasticity, 3))

Estimated price elasticity: -0.865

In [78]:
candidate_prices = np.sort(
    product_data.loc[
        product_data["sell_price"] >= 0.42,
        "sell_price"
    ].unique()
)

candidate_prices

array([0.42, 0.46, 0.48, 0.5 ])

In [79]:
pricing_example = test[
    test["item_id"] == "HOBBIES_1_295"
].iloc[[0]]

base_price = pricing_example["sell_price"].iloc[0]

base_forecast = model.predict(
    pricing_example[features]
)[0]

print("Current price:", base_price)
print("Base demand forecast:", base_forecast)

Current price: 0.48
Base demand forecast: 6.931505982235625

In [80]:
pricing_scenarios = []

for new_price in candidate_prices:

    adjusted_demand = base_forecast * (
        new_price / base_price
    ) ** elasticity

    expected_revenue = new_price * adjusted_demand

    pricing_scenarios.append({
        "price": new_price,
        "forecast_demand": adjusted_demand,
        "expected_revenue": expected_revenue
    })

pricing_results = pd.DataFrame(pricing_scenarios)

pricing_results

   price  forecast_demand  expected_revenue
0   0.42         7.780345          3.267745
1   0.46         7.191482          3.308082
2   0.48         6.931506          3.327123
3   0.50         6.690980          3.345490

In [81]:
recommended = pricing_results.loc[
    pricing_results["expected_revenue"].idxmax()
]

recommended

price               0.50000
forecast_demand     6.69098
expected_revenue    3.34549
Name: 3, dtype: float64

In [82]:
from sklearn.linear_model import PoissonRegressor

elasticity_df = product_data[[
    "demand",
    "sell_price",
    "day_of_week",
    "month",
    "demand_lag_1",
    "demand_lag_7",
    "rolling_mean_7",
    "rolling_mean_28"
]].dropna().copy()

# Log price → coefficient can be interpreted as price elasticity
elasticity_df["log_price"] = np.log(elasticity_df["sell_price"])

# Turn weekday/month into categorical variables
elasticity_df = pd.get_dummies(
    elasticity_df,
    columns=["day_of_week", "month"],
    drop_first=True,
    dtype=float
)

X_elasticity_controlled = elasticity_df.drop(
    columns=["demand", "sell_price"]
)

y_elasticity_controlled = elasticity_df["demand"]

controlled_model = PoissonRegressor(
    alpha=0.001,
    max_iter=1000
)

controlled_model.fit(
    X_elasticity_controlled,
    y_elasticity_controlled
)

controlled_elasticity = controlled_model.coef_[
    X_elasticity_controlled.columns.get_loc("log_price")
]

print(
    "Controlled price elasticity:",
    round(controlled_elasticity, 3)
)

Controlled price elasticity: -0.167

In [84]:
elasticity = controlled_elasticity

In [85]:
pricing_scenarios = []

for new_price in candidate_prices:

    adjusted_demand = base_forecast * (
        new_price / base_price
    ) ** elasticity

    expected_revenue = new_price * adjusted_demand

    pricing_scenarios.append({
        "price": new_price,
        "forecast_demand": adjusted_demand,
        "expected_revenue": expected_revenue
    })

pricing_results = pd.DataFrame(pricing_scenarios)

pricing_results

   price  forecast_demand  expected_revenue
0   0.42         7.087845          2.976895
1   0.46         6.980957          3.211240
2   0.48         6.931506          3.327123
3   0.50         6.884403          3.442202

In [86]:
recommended = pricing_results.loc[
    pricing_results["expected_revenue"].idxmax()
]

recommended

price               0.500000
forecast_demand     6.884403
expected_revenue    3.442202
Name: 3, dtype: float64

In [87]:
elasticity_train = model_data[
    model_data["date"] <= cutoff_date
]

candidate_train = (
    elasticity_train.groupby("item_id")
    .agg(
        unique_prices=("sell_price", "nunique"),
        observations=("demand", "size"),
        selling_days=("demand", lambda x: (x > 0).sum())
    )
)

candidate_items = candidate_train[
    (candidate_train["unique_prices"] >= 4) &
    (candidate_train["selling_days"] >= 100)
].index

print("Eligible products:", len(candidate_items))

Eligible products: 659

In [94]:
# Select only 25 products once
test_items = list(candidate_items[:25])

elasticity_subset = elasticity_train[
    elasticity_train["item_id"].isin(test_items)
][[
    "item_id",
    "date",
    "demand",
    "sell_price",
    "day_of_week",
    "month",
    "demand_lag_1",
    "demand_lag_7",
    "rolling_mean_7",
    "rolling_mean_28"
]].dropna().copy()

# Create expensive features only once
elasticity_subset["log_price"] = np.log(
    elasticity_subset["sell_price"]
)

elasticity_subset["time_idx"] = (
    elasticity_subset["date"] -
    elasticity_subset["date"].min()
).dt.days

print("Rows to process:", len(elasticity_subset))
print("Products:", elasticity_subset["item_id"].nunique())

Rows to process: 42967
Products: 25

In [109]:
elasticity_results = []

for i, (item_id, df) in enumerate(
    elasticity_subset.groupby("item_id"), 1
):

    if df["sell_price"].nunique() < 4:
        continue

    temp = pd.get_dummies(
        df,
        columns=["day_of_week", "month"],
        drop_first=True,
        dtype=float
    )

    X = temp.drop(columns=[
        "item_id",
        "date",
        "demand",
        "sell_price"
    ])

    y = temp["demand"]

    model_e = PoissonRegressor(
        alpha=0.001,
        max_iter=300
    )

    try:
        model_e.fit(X, y)

        elasticity = model_e.coef_[
            X.columns.get_loc("log_price")
        ]

        elasticity_results.append({
            "item_id": item_id,
            "elasticity": elasticity,
            "avg_price": df["sell_price"].mean(),
            "avg_demand": y.mean(),
            "observations": len(df),
            "unique_prices": df["sell_price"].nunique()
        })

        print(f"{i}/25 done — {item_id}")

    except Exception as e:
        print(f"{i}/25 failed — {item_id}: {e}")

C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_glm\glm.py:286: ConvergenceWarning: lbfgs failed to converge after 300 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=300).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result(
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_glm\glm.py:286: ConvergenceWarning: lbfgs failed to converge after 300 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=300).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result(
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights

1/25 done — FOODS_1_009
2/25 done — FOODS_1_010
3/25 done — FOODS_1_011
4/25 done — FOODS_1_012
5/25 done — FOODS_1_013
6/25 done — FOODS_1_015
7/25 done — FOODS_1_017

C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_glm\glm.py:286: ConvergenceWarning: lbfgs failed to converge after 300 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=300).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result(
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_glm\glm.py:286: ConvergenceWarning: lbfgs failed to converge after 300 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=300).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result(

8/25 done — FOODS_1_022
9/25 done — FOODS_1_023

C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_glm\glm.py:286: ConvergenceWarning: lbfgs failed to converge after 300 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=300).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result(
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights

10/25 done — FOODS_1_030
11/25 done — FOODS_1_033
12/25 done — FOODS_1_034
13/25 done — FOODS_1_035

C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_glm\glm.py:286: ConvergenceWarning: lbfgs failed to converge after 300 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=300).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result(

14/25 done — FOODS_1_037

C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_glm\glm.py:286: ConvergenceWarning: lbfgs failed to converge after 300 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=300).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result(

15/25 done — FOODS_1_038

C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_glm\glm.py:286: ConvergenceWarning: lbfgs failed to converge after 300 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=300).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result(

16/25 done — FOODS_1_044

C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_glm\glm.py:286: ConvergenceWarning: lbfgs failed to converge after 300 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=300).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result(

17/25 done — FOODS_1_049

C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_glm\glm.py:286: ConvergenceWarning: lbfgs failed to converge after 300 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=300).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result(

18/25 done — FOODS_1_053

C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_glm\glm.py:286: ConvergenceWarning: lbfgs failed to converge after 300 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=300).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result(
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights

19/25 done — FOODS_1_055
20/25 done — FOODS_1_059
21/25 done — FOODS_1_061
22/25 done — FOODS_1_065
23/25 done — FOODS_1_072
24/25 done — FOODS_1_073
25/25 done — FOODS_1_076

C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_glm\glm.py:286: ConvergenceWarning: lbfgs failed to converge after 300 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=300).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result(
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
C:\Users\iliasso\conda\Lib\site-packages\sklearn\linear_model\_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights

In [97]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import PoissonRegressor
import numpy as np
import pandas as pd

elasticity_results = []

scale_cols = [
    "demand_lag_1",
    "demand_lag_7",
    "rolling_mean_7",
    "rolling_mean_28",
    "time_idx"
]

for i, (item_id, df) in enumerate(
    elasticity_subset.groupby("item_id"), 1
):

    if df["sell_price"].nunique() < 4:
        continue

    temp = pd.get_dummies(
        df,
        columns=["day_of_week", "month"],
        drop_first=True,
        dtype=float
    )

    # Remove invalid values
    temp = temp.replace([np.inf, -np.inf], np.nan).dropna()

    # Scale controls, NOT log_price
    scaler = StandardScaler()
    temp[scale_cols] = scaler.fit_transform(temp[scale_cols])

    X = temp.drop(columns=[
        "item_id",
        "date",
        "demand",
        "sell_price"
    ])

    y = temp["demand"]

    model_e = PoissonRegressor(
        alpha=0.01,
        max_iter=1000,
        tol=1e-6
    )

    try:
        model_e.fit(X, y)

        elasticity = model_e.coef_[
            X.columns.get_loc("log_price")
        ]

        elasticity_results.append({
            "item_id": item_id,
            "elasticity": elasticity,
            "avg_price": df["sell_price"].mean(),
            "avg_demand": df["demand"].mean(),
            "observations": len(df),
            "unique_prices": df["sell_price"].nunique(),
            "iterations": model_e.n_iter_
        })

        print(
            f"{i}/25 done — {item_id} "
            f"| elasticity={elasticity:.3f} "
            f"| iterations={model_e.n_iter_}"
        )

    except Exception as e:
        print(f"{i}/25 FAILED — {item_id}: {e}")

1/25 done — FOODS_1_009 | elasticity=-0.109 | iterations=61
2/25 done — FOODS_1_010 | elasticity=0.052 | iterations=39
3/25 done — FOODS_1_011 | elasticity=0.155 | iterations=73
4/25 done — FOODS_1_012 | elasticity=-1.593 | iterations=84
5/25 done — FOODS_1_013 | elasticity=-0.116 | iterations=56
6/25 done — FOODS_1_015 | elasticity=-0.323 | iterations=107
7/25 done — FOODS_1_017 | elasticity=0.006 | iterations=61
8/25 done — FOODS_1_022 | elasticity=-0.000 | iterations=27
9/25 done — FOODS_1_023 | elasticity=-0.718 | iterations=90
10/25 done — FOODS_1_030 | elasticity=-0.234 | iterations=74
11/25 done — FOODS_1_033 | elasticity=0.031 | iterations=69
12/25 done — FOODS_1_034 | elasticity=-0.002 | iterations=40
13/25 done — FOODS_1_035 | elasticity=0.122 | iterations=75
14/25 done — FOODS_1_037 | elasticity=-0.217 | iterations=102
15/25 done — FOODS_1_038 | elasticity=-0.131 | iterations=76
16/25 done — FOODS_1_044 | elasticity=0.413 | iterations=119
17/25 done — FOODS_1_049 | elasticity=-0.455 | iterations=54
18/25 done — FOODS_1_053 | elasticity=-0.090 | iterations=55
19/25 done — FOODS_1_055 | elasticity=-0.321 | iterations=169
20/25 done — FOODS_1_059 | elasticity=0.014 | iterations=52
21/25 done — FOODS_1_061 | elasticity=-0.231 | iterations=67
22/25 done — FOODS_1_065 | elasticity=-0.189 | iterations=54
23/25 done — FOODS_1_072 | elasticity=0.044 | iterations=55
24/25 done — FOODS_1_073 | elasticity=0.065 | iterations=61
25/25 done — FOODS_1_076 | elasticity=-0.008 | iterations=66

In [98]:
elasticity_table = pd.DataFrame(elasticity_results)

def classify_elasticity(e):
    if e <= -1:
        return "Elastic"
    elif e < 0:
        return "Inelastic"
    else:
        return "Investigate"

elasticity_table["classification"] = (
    elasticity_table["elasticity"]
    .apply(classify_elasticity)
)

elasticity_table.sort_values("elasticity")

,item_id,elasticity,avg_price,avg_demand,observations,unique_prices,iterations,classification
3,FOODS_1_012,-1.593250,5.487381,3.056371,1703,10,84,Elastic
8,FOODS_1_023,-0.717935,5.485531,1.467410,1703,9,90,Inelastic
16,FOODS_1_049,-0.454801,2.240520,0.979841,1885,4,54,Inelastic
5,FOODS_1_015,-0.323402,3.204564,0.693747,1871,6,107,Inelastic
18,FOODS_1_055,-0.321213,3.916552,2.743236,1885,5,169,Inelastic
9,FOODS_1_030,-0.233846,3.189191,0.536741,1878,6,74,Inelastic
20,FOODS_1_061,-0.231086,2.168160,1.682403,1864,4,67,Inelastic
13,FOODS_1_037,-0.216715,3.221470,1.047923,1878,5,102,Inelastic
21,FOODS_1_065,-0.189142,3.302483,0.650928,1885,4,54,Inelastic
14,FOODS_1_038,-0.130638,9.194302,0.539936,1878,5,76,Inelastic
4,FOODS_1_013,-0.116265,1.473968,1.329443,1885,4,56,Inelastic
0,FOODS_1_009,-0.108667,2.398654,0.584791,1486,4,61,Inelastic
17,FOODS_1_053,-0.089943,5.548637,0.375066,1885,6,55,Inelastic
24,FOODS_1_076,-0.008007,5.502366,0.789390,1885,7,66,Inelastic
11,FOODS_1_034,-0.001788,5.522744,0.321212,1815,8,40,Inelastic
7,FOODS_1_022,-0.000007,4.597059,0.123629,1003,9,27,Inelastic
6,FOODS_1_017,0.005855,2.359364,0.562542,1479,4,61,Investigate
19,FOODS_1_059,0.013579,4.708763,0.479036,954,7,52,Investigate
10,FOODS_1_033,0.030943,5.380985,0.411296,1381,9,69,Investigate
22,FOODS_1_072,0.044009,4.887854,0.411087,1822,4,55,Investigate
1,FOODS_1_010,0.051918,5.368937,0.222539,1402,10,39,Investigate
23,FOODS_1_073,0.064631,1.987279,1.157029,1885,4,61,Investigate
12,FOODS_1_035,0.122080,2.518647,0.708223,1885,4,75,Investigate
2,FOODS_1_011,0.155202,2.519390,0.613793,1885,4,73,Investigate
15,FOODS_1_044,0.412732,2.815714,1.942175,1885,4,119,Investigate

In [99]:
print(elasticity_table["classification"].value_counts())

print("\nElasticity statistics:")
print(elasticity_table["elasticity"].describe())

classification
Inelastic      15
Investigate     9
Elastic         1
Name: count, dtype: int64

Elasticity statistics:
count    25.000000
mean     -0.153430
std       0.373088
min      -1.593250
25%      -0.231086
50%      -0.089943
75%       0.030943
max       0.412732
Name: elasticity, dtype: float64

In [100]:
elasticity_table[
    elasticity_table["elasticity"] > 0
][[
    "item_id",
    "elasticity",
    "avg_price",
    "avg_demand",
    "unique_prices"
]]

        item_id  elasticity  avg_price  avg_demand  unique_prices
1   FOODS_1_010    0.051918   5.368937    0.222539             10
2   FOODS_1_011    0.155202   2.519390    0.613793              4
6   FOODS_1_017    0.005855   2.359364    0.562542              4
10  FOODS_1_033    0.030943   5.380985    0.411296              9
12  FOODS_1_035    0.122080   2.518647    0.708223              4
15  FOODS_1_044    0.412732   2.815714    1.942175              4
19  FOODS_1_059    0.013579   4.708763    0.479036              7
22  FOODS_1_072    0.044009   4.887854    0.411087              4
23  FOODS_1_073    0.064631   1.987279    1.157029              4

In [103]:
all_items = list(candidate_items)

batch_size = 100
all_elasticity_results = []

print("Products to process:", len(all_items))

Products to process: 659

In [105]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import PoissonRegressor

for start in range(0, len(all_items), batch_size):

    batch_items = all_items[start:start + batch_size]

    batch = elasticity_train[
        elasticity_train["item_id"].isin(batch_items)
    ][[
        "item_id",
        "date",
        "demand",
        "sell_price",
        "day_of_week",
        "month",
        "demand_lag_1",
        "demand_lag_7",
        "rolling_mean_7",
        "rolling_mean_28"
    ]].dropna().copy()

    batch["log_price"] = np.log(batch["sell_price"])

    batch["time_idx"] = (
        batch["date"] - batch["date"].min()
    ).dt.days

    for item_id, df in batch.groupby("item_id"):

        temp = pd.get_dummies(
            df,
            columns=["day_of_week", "month"],
            drop_first=True,
            dtype=float
        )

        temp = temp.replace(
            [np.inf, -np.inf],
            np.nan
        ).dropna()

        scaler = StandardScaler()

        temp[scale_cols] = scaler.fit_transform(
            temp[scale_cols]
        )

        X = temp.drop(columns=[
            "item_id",
            "date",
            "demand",
            "sell_price"
        ])

        y = temp["demand"]

        model_e = PoissonRegressor(
            alpha=0.01,
            max_iter=1000,
            tol=1e-6
        )

        try:
            model_e.fit(X, y)

            e = model_e.coef_[
                X.columns.get_loc("log_price")
            ]

            all_elasticity_results.append({
                "item_id": item_id,
                "elasticity": e,
                "avg_price": df["sell_price"].mean(),
                "avg_demand": df["demand"].mean(),
                "observations": len(df),
                "unique_prices": df["sell_price"].nunique(),
                "iterations": model_e.n_iter_
            })

        except Exception as error:
            print("FAILED:", item_id, error)

    # save progress after each batch
    pd.DataFrame(
        all_elasticity_results
    ).to_csv(
        "data/elasticity_results_checkpoint.csv",
        index=False
    )

    print(
        f"Completed {min(start + batch_size, len(all_items))}"
        f"/{len(all_items)}"
    )

Completed 100/659
Completed 200/659
Completed 300/659
Completed 400/659
Completed 500/659
Completed 600/659
Completed 659/659

In [108]:
data/elasticity_results_checkpoint.csv

NameError: name 'data' is not defined

In [110]:
master_elasticity = pd.DataFrame(all_elasticity_results)

def classify_elasticity(e):
    if e <= -1:
        return "Elastic"
    elif e < 0:
        return "Inelastic"
    else:
        return "Investigate"

master_elasticity["classification"] = (
    master_elasticity["elasticity"]
    .apply(classify_elasticity)
)

print("Products modeled:", len(master_elasticity))
print("\nClassification:")
print(master_elasticity["classification"].value_counts())

master_elasticity.sort_values("elasticity").head(20)

Products modeled: 1318

Classification:
classification
Inelastic      810
Investigate    470
Elastic         38
Name: count, dtype: int64

,item_id,elasticity,avg_price,avg_demand,observations,unique_prices,iterations,classification
936,FOODS_3_064,-3.615252,1.131087,14.998867,1766,4,87,Elastic
277,FOODS_3_064,-3.615252,1.131087,14.998867,1766,4,87,Elastic
284,FOODS_3_086,-1.676797,1.102828,7.849337,1885,5,77,Elastic
943,FOODS_3_086,-1.676797,1.102828,7.849337,1885,5,77,Elastic
1094,FOODS_3_681,-1.667788,1.104721,17.314589,1885,5,110,Elastic
435,FOODS_3_681,-1.667788,1.104721,17.314589,1885,5,110,Elastic
662,FOODS_1_012,-1.593250,5.487381,3.056371,1703,10,84,Elastic
3,FOODS_1_012,-1.593250,5.487381,3.056371,1703,10,84,Elastic
269,FOODS_3_020,-1.549446,1.050663,6.031830,1885,5,84,Elastic
928,FOODS_3_020,-1.549446,1.050663,6.031830,1885,5,84,Elastic
830,FOODS_2_212,-1.518477,4.656891,2.348541,1885,8,126,Elastic
171,FOODS_2_212,-1.518477,4.656891,2.348541,1885,8,126,Elastic
538,HOBBIES_1_370,-1.385161,0.476286,7.644032,1885,4,99,Elastic
1197,HOBBIES_1_370,-1.385161,0.476286,7.644032,1885,4,99,Elastic
999,FOODS_3_281,-1.316180,1.221113,11.972843,1878,5,120,Elastic
340,FOODS_3_281,-1.316180,1.221113,11.972843,1878,5,120,Elastic
940,FOODS_3_076,-1.309682,1.103088,3.815915,1885,5,79,Elastic
281,FOODS_3_076,-1.309682,1.103088,3.815915,1885,5,79,Elastic
738,FOODS_2_029,-1.295129,10.911056,2.848806,1885,4,146,Elastic
79,FOODS_2_029,-1.295129,10.911056,2.848806,1885,4,146,Elastic

In [111]:
master_elasticity = pd.DataFrame(all_elasticity_results)

print("Rows before cleaning:", len(master_elasticity))
print("Unique products:", master_elasticity["item_id"].nunique())

master_elasticity = (
    master_elasticity
    .drop_duplicates(subset="item_id", keep="last")
    .reset_index(drop=True)
)

print("Rows after cleaning:", len(master_elasticity))

Rows before cleaning: 1318
Unique products: 659
Rows after cleaning: 659

In [112]:
def classify_elasticity(e):
    if e <= -1:
        return "Elastic"
    elif e < 0:
        return "Inelastic"
    else:
        return "Investigate"

master_elasticity["classification"] = (
    master_elasticity["elasticity"]
    .apply(classify_elasticity)
)

print(master_elasticity["classification"].value_counts())
print("\nTotal:", len(master_elasticity))

classification
Inelastic      405
Investigate    235
Elastic         19
Name: count, dtype: int64

Total: 659

In [113]:
master_elasticity.to_csv(
    "data/master_product_elasticities.csv",
    index=False
)

print("Clean master elasticity table saved.")

Clean master elasticity table saved.

In [114]:

def recommend_price(item_id, min_price_days=14):

    # 1. Get product elasticity
    row = master_elasticity[
        master_elasticity["item_id"] == item_id
    ]

    if row.empty:
        return {
            "item_id": item_id,
            "status": "NO_ELASTICITY_MODEL"
        }

    elasticity = row["elasticity"].iloc[0]
    classification = row["classification"].iloc[0]

    # Governance rule
    if classification == "Investigate":
        return {
            "item_id": item_id,
            "status": "MANUAL_REVIEW",
            "elasticity": elasticity,
            "classification": classification
        }

    # 2. Get latest available test observation
    product_test = test[
        test["item_id"] == item_id
    ].sort_values("date")

    if product_test.empty:
        return {
            "item_id": item_id,
            "status": "NO_TEST_OBSERVATION"
        }

    latest = product_test.iloc[[-1]]

    base_price = latest["sell_price"].iloc[0]

    # 3. Baseline demand forecast
    base_forecast = max(
        model.predict(latest[features])[0],
        0
    )

    # 4. Only use prices with enough historical support
    price_support = (
        elasticity_train[
            elasticity_train["item_id"] == item_id
        ]
        .groupby("sell_price")
        .size()
    )

    safe_prices = price_support[
        price_support >= min_price_days
    ].index.to_numpy()

    if len(safe_prices) < 2:
        return {
            "item_id": item_id,
            "status": "INSUFFICIENT_PRICE_HISTORY",
            "safe_prices": len(safe_prices)
        }

    # 5. Simulate prices
    scenarios = []

    for new_price in safe_prices:

        adjusted_demand = base_forecast * (
            new_price / base_price
        ) ** elasticity

        adjusted_demand = max(adjusted_demand, 0)

        expected_revenue = (
            new_price * adjusted_demand
        )

        scenarios.append({
            "price": new_price,
            "forecast_demand": adjusted_demand,
            "expected_revenue": expected_revenue
        })

    scenarios = pd.DataFrame(scenarios)

    best = scenarios.loc[
        scenarios["expected_revenue"].idxmax()
    ]

    current_revenue = (
        base_price * base_forecast
    )

    uplift_pct = (
        (best["expected_revenue"] - current_revenue)
        / current_revenue * 100
        if current_revenue > 0
        else 0
    )

    return {
        "item_id": item_id,
        "status": "AUTO_RECOMMEND",
        "classification": classification,
        "elasticity": round(elasticity, 3),
        "current_price": round(base_price, 3),
        "recommended_price": round(best["price"], 3),
        "forecast_current_demand": round(base_forecast, 3),
        "forecast_recommended_demand": round(
            best["forecast_demand"], 3
        ),
        "current_expected_revenue": round(
            current_revenue, 3
        ),
        "recommended_expected_revenue": round(
            best["expected_revenue"], 3
        ),
        "expected_revenue_uplift_pct": round(
            uplift_pct, 2
        )
    }

In [115]:
recommend_price("HOBBIES_1_295")

{'item_id': 'HOBBIES_1_295',
 'status': 'AUTO_RECOMMEND',
 'classification': 'Inelastic',
 'elasticity': np.float64(-0.036),
 'current_price': np.float64(0.48),
 'recommended_price': np.float64(0.5),
 'forecast_current_demand': np.float64(9.202),
 'forecast_recommended_demand': np.float64(9.189),
 'current_expected_revenue': np.float64(4.417),
 'recommended_expected_revenue': np.float64(4.594),
 'expected_revenue_uplift_pct': np.float64(4.01)}

In [116]:
investigate_item = master_elasticity[
    master_elasticity["classification"] == "Investigate"
]["item_id"].iloc[0]

recommend_price(investigate_item)

{'item_id': 'FOODS_1_010',
 'status': 'MANUAL_REVIEW',
 'elasticity': np.float64(0.05191811591473074),
 'classification': 'Investigate'}

In [117]:
import joblib
import json
from pathlib import Path

Path("models").mkdir(exist_ok=True)

# Save forecasting model
joblib.dump(
    model,
    "models/demand_forecaster.joblib"
)

# Save exact feature order
with open("models/features.json", "w") as f:
    json.dump(features, f)

print("Model and features saved.")

Model and features saved.

In [118]:
loaded_model = joblib.load(
    "models/demand_forecaster.joblib"
)

test_prediction = loaded_model.predict(
    X_test.iloc[[0]]
)[0]

print("Original prediction:", model.predict(X_test.iloc[[0]])[0])
print("Loaded prediction:", test_prediction)

Original prediction: 1.0155033248289378
Loaded prediction: 1.0155033248289378

In [119]:
import json
import joblib
import pandas as pd
import numpy as np
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent

MODEL_PATH = BASE_DIR / "models" / "demand_forecaster.joblib"
FEATURES_PATH = BASE_DIR / "models" / "features.json"
ELASTICITY_PATH = BASE_DIR / "data" / "master_product_elasticities.csv"


# Load model once
model = joblib.load(MODEL_PATH)

with open(FEATURES_PATH, "r") as f:
    features = json.load(f)

elasticities = pd.read_csv(ELASTICITY_PATH)


def get_elasticity(item_id):

    row = elasticities[
        elasticities["item_id"] == item_id
    ]

    if row.empty:
        return None

    return {
        "elasticity": float(row["elasticity"].iloc[0]),
        "classification": row["classification"].iloc[0]
    }


def forecast_demand(feature_values):

    X = pd.DataFrame(
        [feature_values],
        columns=features
    )

    prediction = model.predict(X)[0]

    return max(float(prediction), 0)


def optimize_price(
    base_price,
    base_demand,
    elasticity,
    candidate_prices
):

    scenarios = []

    for price in candidate_prices:

        demand = base_demand * (
            price / base_price
        ) ** elasticity

        demand = max(float(demand), 0)

        revenue = float(price * demand)

        scenarios.append({
            "price": float(price),
            "forecast_demand": demand,
            "expected_revenue": revenue
        })

    results = pd.DataFrame(scenarios)

    best = results.loc[
        results["expected_revenue"].idxmax()
    ]

    return {
        "recommended_price": float(best["price"]),
        "forecast_demand": float(best["forecast_demand"]),
        "expected_revenue": float(best["expected_revenue"]),
        "scenarios": scenarios
    }

NameError: name '__file__' is not defined

In [120]:
from pathlib import Path

Path("src").mkdir(exist_ok=True)

In [121]:
%%writefile src/pricing_engine.py

UsageError: %%writefile is a cell magic, but the cell body is empty.

In [122]:

from pathlib import Path

code = '''
import json
import joblib
import pandas as pd
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

MODEL_PATH = BASE_DIR / "models" / "demand_forecaster.joblib"
FEATURES_PATH = BASE_DIR / "models" / "features.json"
ELASTICITY_PATH = BASE_DIR / "data" / "master_product_elasticities.csv"

model = joblib.load(MODEL_PATH)

with open(FEATURES_PATH, "r") as f:
    features = json.load(f)

elasticities = pd.read_csv(ELASTICITY_PATH)


def get_elasticity(item_id):
    row = elasticities[elasticities["item_id"] == item_id]

    if row.empty:
        return None

    return {
        "elasticity": float(row["elasticity"].iloc[0]),
        "classification": str(row["classification"].iloc[0])
    }


def forecast_demand(feature_values):
    X = pd.DataFrame([feature_values])[features]
    prediction = model.predict(X)[0]

    return max(float(prediction), 0.0)


def optimize_price(base_price, base_demand, elasticity, candidate_prices):
    scenarios = []

    for price in candidate_prices:
        demand = base_demand * (price / base_price) ** elasticity
        demand = max(float(demand), 0.0)
        revenue = float(price * demand)

        scenarios.append({
            "price": float(price),
            "forecast_demand": demand,
            "expected_revenue": revenue
        })

    best = max(scenarios, key=lambda x: x["expected_revenue"])

    return {
        "recommended_price": best["price"],
        "forecast_demand": best["forecast_demand"],
        "expected_revenue": best["expected_revenue"],
        "scenarios": scenarios
    }
'''

Path("src").mkdir(exist_ok=True)
Path("src/pricing_engine.py").write_text(code, encoding="utf-8")

print("pricing_engine.py created successfully!")

pricing_engine.py created successfully!

In [123]:
from src.pricing_engine import (
    get_elasticity,
    forecast_demand,
    optimize_price
)

print("Pricing engine imported successfully!")

Pricing engine imported successfully!

In [124]:
get_elasticity("HOBBIES_1_295")

{'elasticity': -0.0364939817461, 'classification': 'Inelastic'}

In [125]:

sample_features = X_test.iloc[0].to_dict()

prediction = forecast_demand(sample_features)

print("Demand forecast:", prediction)

Demand forecast: 1.0155033248289378

In [126]:
elasticity_info = get_elasticity("HOBBIES_1_295")

result = optimize_price(
    base_price=0.48,
    base_demand=9.202,
    elasticity=elasticity_info["elasticity"],
    candidate_prices=[0.42, 0.46, 0.48, 0.50]
)

result

{'recommended_price': 0.5,
 'forecast_demand': 9.188301461236792,
 'expected_revenue': 4.594150730618396,
 'scenarios': [{'price': 0.42,
   'forecast_demand': 9.246951632238869,
   'expected_revenue': 3.8837196855403247},
  {'price': 0.46,
   'forecast_demand': 9.216303373331725,
   'expected_revenue': 4.239499551732593},
  {'price': 0.48,
   'forecast_demand': 9.202,
   'expected_revenue': 4.4169599999999996},
  {'price': 0.5,
   'forecast_demand': 9.188301461236792,
   'expected_revenue': 4.594150730618396}]}

In [128]:
%pip install fastapi uvicorn

Requirement already satisfied: fastapi in c:\users\iliasso\conda\lib\site-packages (0.141.1)
Requirement already satisfied: uvicorn in c:\users\iliasso\conda\lib\site-packages (0.52.4)
Requirement already satisfied: starlette>=0.46.0 in c:\users\iliasso\conda\lib\site-packages (from fastapi) (1.6.0)
Requirement already satisfied: pydantic>=2.9.0 in c:\users\iliasso\conda\lib\site-packages (from fastapi) (2.12.4)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\iliasso\conda\lib\site-packages (from fastapi) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\iliasso\conda\lib\site-packages (from fastapi) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\iliasso\conda\lib\site-packages (from fastapi) (0.0.5)
Requirement already satisfied: click>=7.0 in c:\users\iliasso\conda\lib\site-packages (from uvicorn) (8.2.1)
Requirement already satisfied: h11>=0.8 in c:\users\iliasso\conda\lib\site-packages (from uvicorn) (0.16.0)
Requirement already satisfied: colorama in c:\users\iliasso\conda\lib\site-packages (from click>=7.0->uvicorn) (0.4.6)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\iliasso\conda\lib\site-packages (from pydantic>=2.9.0->fastapi) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\iliasso\conda\lib\site-packages (from pydantic>=2.9.0->fastapi) (2.41.5)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\iliasso\conda\lib\site-packages (from starlette>=0.46.0->fastapi) (4.10.0)
Requirement already satisfied: idna>=2.8 in c:\users\iliasso\conda\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (3.11)
Requirement already satisfied: sniffio>=1.1 in c:\users\iliasso\conda\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (1.3.0)
Note: you may need to restart the kernel to use updated packages.

In [129]:
from pathlib import Path

from src.pricing_engine import (
    get_elasticity,
    forecast_demand,
    optimize_price
)

app = FastAPI(
    title="AI

Path("api").mkdir(exist_ok=True)

api_code = '''
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Dict, List Demand & Pricing Engine",
    version="1.0.0",
    description="Demand forecasting and price recommendation API"
)


class ForecastRequest(BaseModel):
    features: Dict[str, float]


class PricingRequest(BaseModel):
    item_id: str
    base_price: float
    base_demand: float
    candidate_prices: List[float]


@app.get("/")
def root():
    return {
        "service": "AI Demand & Pricing Engine",
        "status": "running"
    }


@app.get("/health")
def health():
    return {"status": "healthy"}


@app.get("/elasticity/{item_id}")
def elasticity(item_id: str):

    result = get_elasticity(item_id)

    if result is None:
        raise HTTPException(
            status_code=404,
            detail="Product elasticity not found"
        )

    return {
        "item_id": item_id,
        **result
    }


@app.post("/forecast")
def forecast(request: ForecastRequest):

    prediction = forecast_demand(
        request.features
    )

    return {
        "predicted_demand": prediction
    }


@app.post("/recommend-price")
def recommend_price(request: PricingRequest):

    info = get_elasticity(request.item_id)

    if info is None:
        raise HTTPException(
            status_code=404,
            detail="Product elasticity not found"
        )

    if info["classification"] == "Investigate":
        return {
            "item_id": request.item_id,
            "status": "MANUAL_REVIEW",
            "elasticity": info["elasticity"],
            "classification": info["classification"]
        }

    result = optimize_price(
        base_price=request.base_price,
        base_demand=request.base_demand,
        elasticity=info["elasticity"],
        candidate_prices=request.candidate_prices
    )

    return {
        "item_id": request.item_id,
        "status": "AUTO_RECOMMEND",
        "elasticity": info["elasticity"],
        "classification": info["classification"],
        **result
    }
'''

Path("api/app.py").write_text(
    api_code,
    encoding="utf-8"
)

print("FastAPI application created!")

FastAPI application created!

In [130]:
from pathlib import Path

print(Path("dashboard/app.py").exists())

False

In [131]:
from pathlib import Path

Path("dashboard").mkdir(exist_ok=True)

dashboard_code = '''
import streamlit as st
import requests
import pandas as pd

API_URL = "http://127.0.0.1:8000"

st.set_page_config(
    page_title="AI Demand & Pricing Engine",
    page_icon="📈",
    layout="wide"
)

st.title("AI Demand & Pricing Engine")
st.caption(
    "Demand forecasting, price elasticity and revenue-aware pricing recommendations"
)

# API status
try:
    health = requests.get(f"{API_URL}/health", timeout=3)

    if health.status_code == 200:
        st.sidebar.success("API Online")
    else:
        st.sidebar.error("API Error")

except Exception:
    st.sidebar.error("API Offline")


st.sidebar.header("Engine")
st.sidebar.write("• Demand Forecasting")
st.sidebar.write("• Product Elasticity")
st.sidebar.write("• Revenue Optimization")
st.sidebar.write("• Governance Layer")


st.header("Product Pricing Simulation")

col1, col2, col3 = st.columns(3)

with col1:
    item_id = st.text_input(
        "Product ID",
        value="HOBBIES_1_295"
    )

with col2:
    base_price = st.number_input(
        "Current Price",
        min_value=0.01,
        value=0.48,
        step=0.01
    )

with col3:
    base_demand = st.number_input(
        "Current Demand Forecast",
        min_value=0.0,
        value=9.202,
        step=0.1
    )


candidate_text = st.text_input(
    "Candidate Prices",
    value="0.42, 0.46, 0.48, 0.50"
)


if st.button(
    "Generate Recommendation",
    type="primary",
    use_container_width=True
):

    try:
        candidate_prices = [
            float(x.strip())
            for x in candidate_text.split(",")
            if x.strip()
        ]

        payload = {
            "item_id": item_id,
            "base_price": base_price,
            "base_demand": base_demand,
            "candidate_prices": candidate_prices
        }

        response = requests.post(
            f"{API_URL}/recommend-price",
            json=payload,
            timeout=10
        )

        if response.status_code == 404:
            st.error("Product elasticity not found.")
            st.stop()

        if response.status_code != 200:
            st.error(f"API error: {response.text}")
            st.stop()

        result = response.json()


        # Governance rule
        if result["status"] == "MANUAL_REVIEW":

            st.warning("Manual Review Required")

            c1, c2 = st.columns(2)

            c1.metric(
                "Elasticity",
                f"{result['elasticity']:.3f}"
            )

            c2.metric(
                "Classification",
                result["classification"]
            )

            st.info(
                "This product is not considered safe for automatic repricing."
            )


        else:

            recommended_price = result["recommended_price"]
            recommended_demand = result["forecast_demand"]
            recommended_revenue = result["expected_revenue"]

            current_revenue = base_price * base_demand

            uplift = (
                (
                    recommended_revenue - current_revenue
                )
                / current_revenue * 100
                if current_revenue > 0
                else 0
            )

            st.success("Automatic Recommendation Generated")

            m1, m2, m3, m4 = st.columns(4)

            m1.metric(
                "Current Price",
                f"{base_price:.2f}"
            )

            m2.metric(
                "Recommended Price",
                f"{recommended_price:.2f}",
                delta=f"{recommended_price - base_price:+.2f}"
            )

            m3.metric(
                "Expected Revenue",
                f"{recommended_revenue:.2f}"
            )

            m4.metric(
                "Revenue Uplift",
                f"{uplift:.2f}%"
            )


            c1, c2, c3 = st.columns(3)

            c1.metric(
                "Elasticity",
                f"{result['elasticity']:.3f}"
            )

            c2.metric(
                "Classification",
                result["classification"]
            )

            c3.metric(
                "Demand @ Recommended Price",
                f"{recommended_demand:.2f}"
            )


            scenarios = pd.DataFrame(
                result["scenarios"]
            ).sort_values("price")

            scenarios.columns = [
                "Price",
                "Forecast Demand",
                "Expected Revenue"
            ]


            st.subheader("Pricing Scenarios")

            st.dataframe(
                scenarios,
                use_container_width=True,
                hide_index=True
            )


            st.subheader("Expected Revenue by Price")

            st.line_chart(
                scenarios.set_index("Price")[
                    ["Expected Revenue"]
                ]
            )


            st.subheader("Demand Response to Price")

            st.line_chart(
                scenarios.set_index("Price")[
                    ["Forecast Demand"]
                ]
            )


    except ValueError:
        st.error(
            "Candidate prices must contain numbers only."
        )

    except requests.exceptions.ConnectionError:
        st.error(
            "FastAPI is offline. Keep the Uvicorn terminal running."
        )

    except Exception as e:
        st.error(f"Unexpected error: {e}")
'''

Path("dashboard/app.py").write_text(
    dashboard_code,
    encoding="utf-8"
)

print("Dashboard created successfully!")
print("Exists:", Path("dashboard/app.py").exists())

Dashboard created successfully!
Exists: True

In [132]:
from pathlib import Path

p = Path("dashboard/app.py")

text = p.read_text(encoding="utf-8")
text = text.replace(
    'API_URL = "http://127.0.0.1:8000"',
    'API_URL = "http://127.0.0.1:8001"'
)

p.write_text(text, encoding="utf-8")

print("Dashboard API changed to port 8001.")

Dashboard API changed to port 8001.

In [133]:
from pathlib import Path

requirements = """fastapi
uvicorn
streamlit
requests
pandas
numpy
scikit-learn
joblib
pydantic
"""

Path("requirements.txt").write_text(
    requirements,
    encoding="utf-8"
)

print("requirements.txt created successfully!")

requirements.txt created successfully!

In [134]:
from pathlib import Path

# Add testing dependencies to requirements.txt
requirements_path = Path("requirements.txt")
requirements_text = requirements_path.read_text(encoding="utf-8")

for package in ["pytest", "httpx"]:
    if package not in requirements_text:
        requirements_text += f"{package}\n"

requirements_path.write_text(
    requirements_text,
    encoding="utf-8"
)

# Create tests folder
Path("tests").mkdir(exist_ok=True)

test_code = '''
from fastapi.testclient import TestClient

from api.app import app
from src.pricing_engine import (
    get_elasticity,
    optimize_price
)

client = TestClient(app)


def test_health_endpoint():
    response = client.get("/health")

    assert response.status_code == 200
    assert response.json() == {"status": "healthy"}


def test_known_product_elasticity():
    result = get_elasticity("HOBBIES_1_295")

    assert result is not None
    assert "elasticity" in result
    assert "classification" in result
    assert result["classification"] == "Inelastic"
    assert result["elasticity"] < 0


def test_unknown_product_elasticity():
    result = get_elasticity("PRODUCT_DOES_NOT_EXIST")

    assert result is None


def test_price_optimizer():
    elasticity_info = get_elasticity("HOBBIES_1_295")

    result = optimize_price(
        base_price=0.48,
        base_demand=9.202,
        elasticity=elasticity_info["elasticity"],
        candidate_prices=[0.42, 0.46, 0.48, 0.50]
    )

    assert "recommended_price" in result
    assert "forecast_demand" in result
    assert "expected_revenue" in result
    assert "scenarios" in result

    assert result["recommended_price"] == 0.50
    assert len(result["scenarios"]) == 4


def test_recommend_price_endpoint():
    payload = {
        "item_id": "HOBBIES_1_295",
        "base_price": 0.48,
        "base_demand": 9.202,
        "candidate_prices": [
            0.42,
            0.46,
            0.48,
            0.50
        ]
    }

    response = client.post(
        "/recommend-price",
        json=payload
    )

    assert response.status_code == 200

    data = response.json()

    assert data["status"] == "AUTO_RECOMMEND"
    assert data["classification"] == "Inelastic"
    assert data["recommended_price"] == 0.50


def test_unknown_product_endpoint():
    payload = {
        "item_id": "PRODUCT_DOES_NOT_EXIST",
        "base_price": 1.0,
        "base_demand": 10.0,
        "candidate_prices": [
            0.90,
            1.00,
            1.10
        ]
    }

    response = client.post(
        "/recommend-price",
        json=payload
    )

    assert response.status_code == 404
'''

Path("tests/test_project.py").write_text(
    test_code,
    encoding="utf-8"
)

print("Automated tests created successfully!")
print("Test file exists:", Path("tests/test_project.py").exists())

Automated tests created successfully!
Test file exists: True

In [135]:
from pathlib import Path

gitignore = """
# Python
__pycache__/
*.py[cod]
*.pyd
*.so

# Virtual environments
venv/
env/
.venv/

# Jupyter
.ipynb_checkpoints/

# Pytest
.pytest_cache/

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db

# Logs
*.log

# Local environment
.env

# Large/raw data
data/sales_train_evaluation.csv
data/sales_train_validation.csv
data/calendar.csv
data/sell_prices.csv

# Temporary files
*.tmp
"""

Path(".gitignore").write_text(
    gitignore.strip() + "\n",
    encoding="utf-8"
)

print(".gitignore created successfully!")

.gitignore created successfully!

In [136]:
from pathlib import Path

folders = [
    "docs",
    "assets"
]

for folder in folders:
    Path(folder).mkdir(exist_ok=True)

print("Repository structure prepared.")

Repository structure prepared.

In [137]:
from pathlib import Path

folders = [
    "docs",
    "assets"
]

for folder in folders:
    Path(folder).mkdir(exist_ok=True)

print("Repository structure prepared.")

Repository structure prepared.

In [141]:
from pathlib import Path

pages_dir = Path("dashboard/pages")
pages_dir.mkdir(parents=True, exist_ok=True)

print("Dashboard V2 structure created.")

Dashboard V2 structure created.

In [142]:
from pathlib import Path

product_page = '''
import streamlit as st
import pandas as pd
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent

DATA_FILE = (
    BASE_DIR
    / "data"
    / "master_product_elasticities.csv"
)

st.set_page_config(
    page_title="Product Intelligence",
    page_icon="◇",
    layout="wide"
)

st.title("Product Intelligence")
st.caption(
    "Explore SKU-level price sensitivity and demand characteristics."
)

@st.cache_data
def load_data():
    return pd.read_csv(DATA_FILE)

df = load_data()

item_id = st.selectbox(
    "Select Product",
    sorted(df["item_id"].unique())
)

product = df[
    df["item_id"] == item_id
].iloc[0]

c1, c2, c3, c4 = st.columns(4)

c1.metric(
    "Elasticity",
    f"{product['elasticity']:.3f}"
)

c2.metric(
    "Classification",
    product["classification"]
)

c3.metric(
    "Average Price",
    f"{product['avg_price']:.2f}"
)

c4.metric(
    "Average Demand",
    f"{product['avg_demand']:.2f}"
)

st.divider()

left, right = st.columns(2)

with left:

    st.subheader("Historical Support")

    st.metric(
        "Observations",
        f"{int(product['observations']):,}"
    )

    st.metric(
        "Unique Prices",
        int(product["unique_prices"])
    )

with right:

    st.subheader("Interpretation")

    elasticity = product["elasticity"]

    if product["classification"] == "Investigate":

        st.warning(
            "Manual Review Required"
        )

        st.write(
            """
            The observed price-demand relationship is not considered
            sufficiently reliable for automated repricing.
            """
        )

    elif elasticity <= -1:

        st.success("Price-Sensitive Product")

        st.write(
            """
            Demand is relatively elastic. Price increases may result
            in proportionally larger demand reductions.
            """
        )

    else:

        st.success("Relatively Price-Inelastic")

        st.write(
            """
            Historical demand appears comparatively resistant to
            moderate price changes.
            """
        )

st.divider()

st.subheader("Raw Product Model Record")

st.dataframe(
    df[df["item_id"] == item_id],
    use_container_width=True,
    hide_index=True
)
'''

Path(
    "dashboard/pages/1_Product_Intelligence.py"
).write_text(
    product_page,
    encoding="utf-8"
)

print("Product Intelligence page created.")

Product Intelligence page created.

In [143]:
from pathlib import Path

current_dashboard = Path(
    "dashboard/app.py"
).read_text(
    encoding="utf-8"
)

print("Overview ready.")

Overview ready.

In [144]:
from pathlib import Path

performance_page = '''
import streamlit as st
import pandas as pd

st.set_page_config(
    page_title="Model Performance",
    page_icon="△",
    layout="wide"
)

st.title("Model Performance")

st.caption(
    "Validated forecasting performance on an unseen "
    "28-day future holdout period."
)

metrics = pd.DataFrame({
    "Model": [
        "Naive Lag-1",
        "HistGradientBoosting"
    ],
    "MAE": [
        1.348,
        1.092
    ],
    "RMSE": [
        2.761,
        2.034
    ],
    "R²": [
        0.411,
        0.680
    ]
})

c1, c2, c3 = st.columns(3)

c1.metric(
    "Test MAE",
    "1.092",
    delta="-19.0% vs baseline",
    delta_color="inverse"
)

c2.metric(
    "Test RMSE",
    "2.034",
    delta="-26.3% vs baseline",
    delta_color="inverse"
)

c3.metric(
    "Test R²",
    "0.680",
    delta="+0.269"
)

st.divider()

st.subheader(
    "Benchmark Comparison"
)

st.dataframe(
    metrics,
    use_container_width=True,
    hide_index=True
)

st.subheader(
    "MAE Comparison"
)

st.bar_chart(
    metrics.set_index("Model")[
        ["MAE"]
    ]
)

st.subheader(
    "RMSE Comparison"
)

st.bar_chart(
    metrics.set_index("Model")[
        ["RMSE"]
    ]
)

st.info(
    """
    The evaluation uses a chronological train/test split.
    The final 28 days were excluded from training and used
    as unseen future observations.
    """
)

st.warning(
    """
    Current lag-based evaluation represents a rolling
    one-step-ahead forecasting setup rather than a fully
    recursive 28-day forecast.
    """
)
'''

Path(
    "dashboard/pages/3_Model_Performance.py"
).write_text(
    performance_page,
    encoding="utf-8"
)

print("Model Performance page created.")

Model Performance page created.

In [145]:
from pathlib import Path

governance_page = '''
import streamlit as st
import pandas as pd
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent

DATA_FILE = (
    BASE_DIR
    / "data"
    / "master_product_elasticities.csv"
)

st.set_page_config(
    page_title="AI Governance",
    page_icon="◇",
    layout="wide"
)

st.title("AI Governance & Human Review")

st.caption(
    "Decision safeguards around automated pricing recommendations."
)

df = pd.read_csv(DATA_FILE)

investigate = df[
    df["classification"] == "Investigate"
]

safe = df[
    df["classification"] != "Investigate"
]

c1, c2, c3 = st.columns(3)

c1.metric(
    "Total Products",
    len(df)
)

c2.metric(
    "Auto Eligible",
    len(safe)
)

c3.metric(
    "Manual Review",
    len(investigate)
)

st.divider()

st.subheader(
    "Decision Policy"
)

st.markdown(
"""
### AUTO_RECOMMEND

Allowed when the product-level elasticity is economically
coherent and sufficient historical support exists.

### MANUAL_REVIEW

Triggered when the elasticity estimate is classified as
**Investigate**.

The system therefore separates:

**model prediction → decision recommendation → human authorization**

rather than treating every statistical output as an
automatic business decision.
"""
)

st.divider()

st.subheader(
    "Products Requiring Review"
)

st.dataframe(
    investigate[
        [
            "item_id",
            "elasticity",
            "avg_price",
            "avg_demand",
            "observations",
            "unique_prices"
        ]
    ],
    use_container_width=True,
    hide_index=True
)

st.warning(
    """
    Elasticity estimates are observational rather than causal.
    Promotions, seasonality, lifecycle effects and other
    confounders may influence both price and demand.
    """
)
'''

Path(
    "dashboard/pages/4_Governance.py"
).write_text(
    governance_page,
    encoding="utf-8"
)

print("Governance page created.")

Governance page created.

In [147]:
from pathlib import Path

latest_product_features = (
    ml_data
    .sort_values("date")
    .groupby("item_id")
    .tail(1)
    [
        [
            "item_id",
            "date",
            "sell_price",
            "day_of_week",
            "month",
            "year",
            "demand_lag_1",
            "demand_lag_7",
            "rolling_mean_7",
            "rolling_mean_28"
        ]
    ]
    .copy()
)

latest_product_features.to_csv(
    "data/latest_product_features.csv",
    index=False
)

print(
    "Latest product feature store created successfully!"
)

print(
    "Products:",
    latest_product_features["item_id"].nunique()
)

latest_product_features.head()

Latest product feature store created successfully!
Products: 3049

,item_id,date,sell_price,day_of_week,month,year,demand_lag_1,demand_lag_7,rolling_mean_7,rolling_mean_28
5915966,HOUSEHOLD_1_348,2016-05-22,1.86,6,5,2016,2.0,0.0,0.857143,2.250000
5915283,HOBBIES_1_231,2016-05-22,6.87,6,5,2016,1.0,2.0,0.714286,0.714286
5915894,HOUSEHOLD_1_276,2016-05-22,17.97,6,5,2016,0.0,0.0,0.285714,0.142857
5915891,HOUSEHOLD_1_272,2016-05-22,9.97,6,5,2016,11.0,12.0,8.285714,7.285714
5915896,HOUSEHOLD_1_278,2016-05-22,5.97,6,5,2016,0.0,0.0,0.571429,0.535714

In [149]:

from pathlib import Path

latest_product_features = (
    ml_data
    .sort_values("date")
    .groupby("item_id")
    .tail(1)
    [
        [
            "item_id",
            "date",
            "sell_price",
            "day_of_week",
            "month",
            "year",
            "demand_lag_1",
            "demand_lag_7",
            "rolling_mean_7",
            "rolling_mean_28"
        ]
    ]
    .copy()
)

latest_product_features.to_csv(
    "data/latest_product_features.csv",
    index=False
)

print("Latest product feature store created successfully!")
print("Products:", latest_product_features["item_id"].nunique())

latest_product_features.head()

Latest product feature store created successfully!
Products: 3049

,item_id,date,sell_price,day_of_week,month,year,demand_lag_1,demand_lag_7,rolling_mean_7,rolling_mean_28
5915966,HOUSEHOLD_1_348,2016-05-22,1.86,6,5,2016,2.0,0.0,0.857143,2.250000
5915283,HOBBIES_1_231,2016-05-22,6.87,6,5,2016,1.0,2.0,0.714286,0.714286
5915894,HOUSEHOLD_1_276,2016-05-22,17.97,6,5,2016,0.0,0.0,0.285714,0.142857
5915891,HOUSEHOLD_1_272,2016-05-22,9.97,6,5,2016,11.0,12.0,8.285714,7.285714
5915896,HOUSEHOLD_1_278,2016-05-22,5.97,6,5,2016,0.0,0.0,0.571429,0.535714

In [150]:
from pathlib import Path

path = Path("src/pricing_engine.py")

text = path.read_text(encoding="utf-8")

v2_code = r'''

# ============================================================
# BACKEND V2 — AUTOMATIC PRICING RECOMMENDATION
# ============================================================

FEATURE_STORE_PATH = (
    BASE_DIR
    / "data"
    / "latest_product_features.csv"
)

latest_product_features = pd.read_csv(
    FEATURE_STORE_PATH
)


def get_latest_product_features(item_id):
    """
    Retrieve the most recent ML feature snapshot
    available for a product.
    """

    row = latest_product_features[
        latest_product_features["item_id"] == item_id
    ]

    if row.empty:
        return None

    row = row.iloc[0]

    return {
        "item_id": item_id,
        "date": str(row["date"]),
        "sell_price": float(row["sell_price"]),
        "day_of_week": float(row["day_of_week"]),
        "month": float(row["month"]),
        "year": float(row["year"]),
        "demand_lag_1": float(row["demand_lag_1"]),
        "demand_lag_7": float(row["demand_lag_7"]),
        "rolling_mean_7": float(row["rolling_mean_7"]),
        "rolling_mean_28": float(row["rolling_mean_28"])
    }


def generate_candidate_prices(
    base_price,
    max_change_pct=0.10
):
    """
    Generate controlled candidate prices around
    the current price.

    Default range:
    -10%, -5%, current, +5%, +10%
    """

    multipliers = [
        1 - max_change_pct,
        1 - max_change_pct / 2,
        1.0,
        1 + max_change_pct / 2,
        1 + max_change_pct
    ]

    prices = [
        round(
            max(base_price * m, 0.01),
            2
        )
        for m in multipliers
    ]

    return sorted(set(prices))


def validate_price_guardrails(
    base_price,
    candidate_prices,
    max_change_pct=0.10
):
    """
    Prevent prices outside the allowed
    percentage change around the current price.
    """

    minimum_price = (
        base_price
        * (1 - max_change_pct)
    )

    maximum_price = (
        base_price
        * (1 + max_change_pct)
    )

    approved = []

    for price in candidate_prices:

        if (
            price >= minimum_price - 0.001
            and
            price <= maximum_price + 0.001
            and
            price > 0
        ):
            approved.append(
                round(float(price), 2)
            )

    return sorted(set(approved))


def recommend_price_auto(
    item_id,
    max_change_pct=0.10
):
    """
    Fully automatic pricing workflow.

    Product ID
        ↓
    Feature store
        ↓
    Demand forecast
        ↓
    Elasticity lookup
        ↓
    Governance
        ↓
    Candidate price generation
        ↓
    Guardrails
        ↓
    Revenue optimization
    """

    # ------------------------------------------
    # 1. Product features
    # ------------------------------------------

    snapshot = get_latest_product_features(
        item_id
    )

    if snapshot is None:

        return {
            "status": "NOT_FOUND",
            "item_id": item_id,
            "reason": (
                "Latest product features "
                "not available."
            )
        }


    # ------------------------------------------
    # 2. Elasticity
    # ------------------------------------------

    elasticity_info = get_elasticity(
        item_id
    )

    if elasticity_info is None:

        return {
            "status": "NOT_FOUND",
            "item_id": item_id,
            "reason": (
                "Product elasticity "
                "not available."
            )
        }


    # ------------------------------------------
    # 3. Automatic ML demand forecast
    # ------------------------------------------

    feature_values = {
        feature:
        snapshot[feature]
        for feature in features
    }

    predicted_demand = forecast_demand(
        feature_values
    )

    current_price = float(
        snapshot["sell_price"]
    )


    # ------------------------------------------
    # 4. Human-in-the-loop governance
    # ------------------------------------------

    if (
        elasticity_info[
            "classification"
        ]
        ==
        "Investigate"
    ):

        return {
            "status": "MANUAL_REVIEW",
            "item_id": item_id,
            "current_price": current_price,
            "forecast_demand": predicted_demand,
            "elasticity": elasticity_info[
                "elasticity"
            ],
            "classification": elasticity_info[
                "classification"
            ],
            "reason": (
                "Elasticity estimate requires "
                "human validation before repricing."
            )
        }


    # ------------------------------------------
    # 5. Automatic candidate prices
    # ------------------------------------------

    candidate_prices = (
        generate_candidate_prices(
            current_price,
            max_change_pct
        )
    )


    # ------------------------------------------
    # 6. Business guardrails
    # ------------------------------------------

    approved_prices = (
        validate_price_guardrails(
            current_price,
            candidate_prices,
            max_change_pct
        )
    )


    if not approved_prices:

        return {
            "status": "MANUAL_REVIEW",
            "item_id": item_id,
            "reason": (
                "No candidate price passed "
                "business guardrails."
            )
        }


    # ------------------------------------------
    # 7. Revenue optimization
    # ------------------------------------------

    optimization = optimize_price(
        base_price=current_price,
        base_demand=predicted_demand,
        elasticity=elasticity_info[
            "elasticity"
        ],
        candidate_prices=approved_prices
    )


    current_revenue = (
        current_price
        *
        predicted_demand
    )

    recommended_revenue = (
        optimization[
            "expected_revenue"
        ]
    )

    revenue_uplift_pct = (
        (
            recommended_revenue
            -
            current_revenue
        )
        /
        current_revenue
        *
        100
        if current_revenue > 0
        else 0.0
    )


    return {
        "status": "AUTO_RECOMMEND",
        "item_id": item_id,

        "snapshot_date":
        snapshot["date"],

        "current_price":
        current_price,

        "forecast_demand":
        predicted_demand,

        "elasticity":
        elasticity_info[
            "elasticity"
        ],

        "classification":
        elasticity_info[
            "classification"
        ],

        "candidate_prices":
        approved_prices,

        "recommended_price":
        optimization[
            "recommended_price"
        ],

        "forecast_demand_at_recommended_price":
        optimization[
            "forecast_demand"
        ],

        "current_expected_revenue":
        current_revenue,

        "recommended_expected_revenue":
        recommended_revenue,

        "expected_revenue_uplift_pct":
        revenue_uplift_pct,

        "guardrail_max_change_pct":
        max_change_pct * 100,

        "scenarios":
        optimization[
            "scenarios"
        ]
    }
'''

if "def recommend_price_auto(" not in text:
    text += v2_code

    path.write_text(
        text,
        encoding="utf-8"
    )

    print("Backend V2 added successfully!")

else:
    print("Backend V2 already exists — nothing changed.")

Backend V2 added successfully!

In [152]:
import importlib
import src.pricing_engine as pe

importlib.reload(pe)

print(
    "V2 function available:",
    hasattr(pe, "recommend_price_auto")
)

V2 function available: True

In [153]:
result = pe.recommend_price_auto(
    "HOBBIES_1_295"
)

result

{'status': 'AUTO_RECOMMEND',
 'item_id': 'HOBBIES_1_295',
 'snapshot_date': '2016-05-22',
 'current_price': 0.48,
 'forecast_demand': 9.202316043705068,
 'elasticity': -0.0364939817461,
 'classification': 'Inelastic',
 'candidate_prices': [0.46, 0.48, 0.5],
 'recommended_price': 0.5,
 'forecast_demand_at_recommended_price': 9.188617034464036,
 'current_expected_revenue': 4.417111700978432,
 'recommended_expected_revenue': 4.594308517232018,
 'expected_revenue_uplift_pct': 4.011599168169897,
 'guardrail_max_change_pct': 10.0,
 'scenarios': [{'price': 0.46,
   'forecast_demand': 9.216619908287727,
   'expected_revenue': 4.239645157812355},
  {'price': 0.48,
   'forecast_demand': 9.202316043705068,
   'expected_revenue': 4.417111700978432},
  {'price': 0.5,
   'forecast_demand': 9.188617034464036,
   'expected_revenue': 4.594308517232018}]}

In [154]:

from pathlib import Path

path = Path("src/pricing_engine.py")

text = path.read_text(encoding="utf-8")

old_code = '''    minimum_price = (
        base_price
        * (1 - max_change_pct)
    )

    maximum_price = (
        base_price
        * (1 + max_change_pct)
    )'''

new_code = '''    minimum_price = round(
        base_price * (1 - max_change_pct),
        2
    )

    maximum_price = round(
        base_price * (1 + max_change_pct),
        2
    )'''

if old_code in text:

    text = text.replace(
        old_code,
        new_code
    )

    path.write_text(
        text,
        encoding="utf-8"
    )

    print("Guardrail rounding fixed successfully!")

else:

    print("Guardrail block not found.")

Guardrail rounding fixed successfully!

In [155]:
import importlib
import src.pricing_engine as pe

importlib.reload(pe)

result = pe.recommend_price_auto(
    "HOBBIES_1_295"
)

print("Candidates:", result["candidate_prices"])
print("Recommended:", result["recommended_price"])
print("Uplift:", round(result["expected_revenue_uplift_pct"], 2), "%")

Candidates: [0.43, 0.46, 0.48, 0.5, 0.53]
Recommended: 0.53
Uplift: 10.02 %

In [156]:
from pathlib import Path

path = Path("api/app.py")

text = path.read_text(encoding="utf-8")

endpoint_code = r'''

# ============================================================
# BACKEND V2 — AUTOMATIC RECOMMENDATION ENDPOINT
# ============================================================

from src.pricing_engine import recommend_price_auto


@app.get("/recommend-auto/{item_id}")
def recommend_auto(
    item_id: str,
    max_change_pct: float = 0.10
):
    """
    Generate a complete pricing recommendation
    automatically from a product ID.
    """

    if max_change_pct <= 0 or max_change_pct > 0.25:
        raise HTTPException(
            status_code=400,
            detail=(
                "max_change_pct must be greater than 0 "
                "and no higher than 0.25."
            )
        )

    result = recommend_price_auto(
        item_id=item_id,
        max_change_pct=max_change_pct
    )

    if result["status"] == "NOT_FOUND":
        raise HTTPException(
            status_code=404,
            detail=result["reason"]
        )

    return result
'''

if '/recommend-auto/{item_id}' not in text:

    text += endpoint_code

    path.write_text(
        text,
        encoding="utf-8"
    )

    print("Automatic FastAPI endpoint added successfully!")

else:

    print("Automatic endpoint already exists — nothing changed.")

Automatic FastAPI endpoint added successfully!

In [157]:
from pathlib import Path

text = Path("api/app.py").read_text(encoding="utf-8")

print(
    "Auto endpoint exists in file:",
    '/recommend-auto/{item_id}' in text
)

Auto endpoint exists in file: True

In [158]:
from pathlib import Path

path = Path("tests/test_project.py")
text = path.read_text(encoding="utf-8")

new_tests = r'''


def test_auto_recommend_endpoint():

    response = client.get(
        "/recommend-auto/HOBBIES_1_295"
    )

    assert response.status_code == 200

    data = response.json()

    assert data["status"] == "AUTO_RECOMMEND"
    assert data["item_id"] == "HOBBIES_1_295"
    assert data["classification"] == "Inelastic"

    assert "forecast_demand" in data
    assert "candidate_prices" in data
    assert "recommended_price" in data
    assert "expected_revenue_uplift_pct" in data

    assert data["recommended_price"] == 0.53
    assert len(data["candidate_prices"]) == 5


def test_auto_recommend_guardrail_validation():

    response = client.get(
        "/recommend-auto/HOBBIES_1_295",
        params={
            "max_change_pct": 0.50
        }
    )

    assert response.status_code == 400
'''

if "def test_auto_recommend_endpoint(" not in text:

    text += new_tests

    path.write_text(
        text,
        encoding="utf-8"
    )

    print("Backend V2 tests added successfully!")

else:

    print("Backend V2 tests already exist.")

Backend V2 tests added successfully!

In [159]:
from pathlib import Path

path = Path("src/pricing_engine.py")
text = path.read_text(encoding="utf-8")

profit_code = r'''

# ============================================================
# BACKEND V3 — PROFIT OPTIMIZATION
# ============================================================

def optimize_profit(
    base_price,
    base_demand,
    elasticity,
    candidate_prices,
    unit_cost
):
    """
    Compare candidate prices using both expected
    revenue and expected gross profit.

    Profit = (Price - Unit Cost) * Forecast Demand
    """

    if unit_cost < 0:
        raise ValueError(
            "unit_cost cannot be negative."
        )

    scenarios = []

    for price in candidate_prices:

        demand = (
            base_demand
            *
            (price / base_price)
            ** elasticity
        )

        demand = max(
            float(demand),
            0.0
        )

        revenue = float(
            price * demand
        )

        profit = float(
            (price - unit_cost)
            * demand
        )

        margin_pct = (
            (
                price - unit_cost
            )
            /
            price
            *
            100
            if price > 0
            else 0.0
        )

        scenarios.append({
            "price": float(price),
            "forecast_demand": demand,
            "expected_revenue": revenue,
            "expected_profit": profit,
            "gross_margin_pct": margin_pct
        })


    revenue_best = max(
        scenarios,
        key=lambda x:
        x["expected_revenue"]
    )

    profit_best = max(
        scenarios,
        key=lambda x:
        x["expected_profit"]
    )


    current_profit = (
        (base_price - unit_cost)
        *
        base_demand
    )

    profit_uplift_pct = (
        (
            profit_best["expected_profit"]
            -
            current_profit
        )
        /
        abs(current_profit)
        *
        100
        if current_profit != 0
        else 0.0
    )


    return {
        "unit_cost": float(unit_cost),

        "revenue_maximizing_price":
        revenue_best["price"],

        "profit_maximizing_price":
        profit_best["price"],

        "expected_revenue_at_revenue_optimum":
        revenue_best["expected_revenue"],

        "expected_profit_at_profit_optimum":
        profit_best["expected_profit"],

        "forecast_demand_at_profit_optimum":
        profit_best["forecast_demand"],

        "current_expected_profit":
        float(current_profit),

        "expected_profit_uplift_pct":
        float(profit_uplift_pct),

        "scenarios":
        scenarios
    }
'''

if "def optimize_profit(" not in text:

    text += profit_code

    path.write_text(
        text,
        encoding="utf-8"
    )

    print("Profit optimization engine added successfully!")

else:

    print("Profit optimization already exists.")

Profit optimization engine added successfully!

In [160]:
import importlib
import src.pricing_engine as pe

importlib.reload(pe)

profit_result = pe.optimize_profit(
    base_price=0.48,
    base_demand=9.202,
    elasticity=-0.0364939817461,
    candidate_prices=[
        0.43,
        0.46,
        0.48,
        0.50,
        0.53
    ],
    unit_cost=0.30
)

profit_result

{'unit_cost': 0.3,
 'revenue_maximizing_price': 0.53,
 'profit_maximizing_price': 0.53,
 'expected_revenue_at_revenue_optimum': 4.859455320716498,
 'expected_profit_at_profit_optimum': 2.1088202335184807,
 'forecast_demand_at_profit_optimum': 9.168783623993393,
 'current_expected_profit': 1.6563599999999998,
 'expected_profit_uplift_pct': 27.316539491323198,
 'scenarios': [{'price': 0.43,
   'forecast_demand': 9.239014484053325,
   'expected_revenue': 3.9727762281429295,
   'expected_profit': 1.2010718829269322,
   'gross_margin_pct': 30.232558139534888},
  {'price': 0.46,
   'forecast_demand': 9.216303373331725,
   'expected_revenue': 4.239499551732593,
   'expected_profit': 1.4746085397330762,
   'gross_margin_pct': 34.78260869565218},
  {'price': 0.48,
   'forecast_demand': 9.202,
   'expected_revenue': 4.4169599999999996,
   'expected_profit': 1.6563599999999998,
   'gross_margin_pct': 37.5},
  {'price': 0.5,
   'forecast_demand': 9.188301461236792,
   'expected_revenue': 4.594150730618396,
   'expected_profit': 1.8376602922473584,
   'gross_margin_pct': 40.0},
  {'price': 0.53,
   'forecast_demand': 9.168783623993393,
   'expected_revenue': 4.859455320716498,
   'expected_profit': 2.1088202335184807,
   'gross_margin_pct': 43.39622641509435}]}

In [161]:
from pathlib import Path

path = Path("src/pricing_engine.py")
text = path.read_text(encoding="utf-8")

profit_auto_code = r'''

# ============================================================
# BACKEND V3 — AUTOMATIC PROFIT-AWARE RECOMMENDATION
# ============================================================

def recommend_profit_auto(
    item_id,
    unit_cost,
    max_change_pct=0.10
):
    """
    Fully automatic revenue + profit pricing workflow.

    Inputs:
        item_id
        unit_cost

    The engine automatically handles:
        product features
        demand forecasting
        elasticity
        governance
        candidate price generation
        pricing guardrails
        revenue optimization
        profit optimization
    """

    # ------------------------------------------
    # 1. Validate cost
    # ------------------------------------------

    if unit_cost < 0:
        return {
            "status": "INVALID_INPUT",
            "item_id": item_id,
            "reason": "unit_cost cannot be negative."
        }


    # ------------------------------------------
    # 2. Latest product snapshot
    # ------------------------------------------

    snapshot = get_latest_product_features(
        item_id
    )

    if snapshot is None:
        return {
            "status": "NOT_FOUND",
            "item_id": item_id,
            "reason": (
                "Latest product features "
                "not available."
            )
        }


    current_price = float(
        snapshot["sell_price"]
    )


    # ------------------------------------------
    # 3. Cost / margin guardrail
    # ------------------------------------------

    if unit_cost >= current_price:
        return {
            "status": "MANUAL_REVIEW",
            "item_id": item_id,
            "current_price": current_price,
            "unit_cost": float(unit_cost),
            "reason": (
                "Unit cost is greater than or equal "
                "to the current selling price."
            )
        }


    # ------------------------------------------
    # 4. Elasticity
    # ------------------------------------------

    elasticity_info = get_elasticity(
        item_id
    )

    if elasticity_info is None:
        return {
            "status": "NOT_FOUND",
            "item_id": item_id,
            "reason": (
                "Product elasticity "
                "not available."
            )
        }


    # ------------------------------------------
    # 5. Automatic ML demand forecast
    # ------------------------------------------

    feature_values = {
        feature:
        snapshot[feature]
        for feature in features
    }

    predicted_demand = forecast_demand(
        feature_values
    )


    # ------------------------------------------
    # 6. Governance
    # ------------------------------------------

    if (
        elasticity_info["classification"]
        ==
        "Investigate"
    ):
        return {
            "status": "MANUAL_REVIEW",
            "item_id": item_id,
            "current_price": current_price,
            "unit_cost": float(unit_cost),
            "forecast_demand": predicted_demand,
            "elasticity": elasticity_info[
                "elasticity"
            ],
            "classification": elasticity_info[
                "classification"
            ],
            "reason": (
                "Elasticity estimate requires "
                "human validation."
            )
        }


    # ------------------------------------------
    # 7. Generate candidate prices
    # ------------------------------------------

    candidate_prices = generate_candidate_prices(
        current_price,
        max_change_pct
    )


    # ------------------------------------------
    # 8. Apply pricing guardrails
    # ------------------------------------------

    approved_prices = validate_price_guardrails(
        current_price,
        candidate_prices,
        max_change_pct
    )


    # Never optimize toward a price at/below cost
    approved_prices = [
        price
        for price in approved_prices
        if price > unit_cost
    ]


    if not approved_prices:
        return {
            "status": "MANUAL_REVIEW",
            "item_id": item_id,
            "reason": (
                "No profitable candidate price "
                "passed the business guardrails."
            )
        }


    # ------------------------------------------
    # 9. Profit + revenue optimization
    # ------------------------------------------

    optimization = optimize_profit(
        base_price=current_price,
        base_demand=predicted_demand,
        elasticity=elasticity_info[
            "elasticity"
        ],
        candidate_prices=approved_prices,
        unit_cost=unit_cost
    )


    current_revenue = (
        current_price
        *
        predicted_demand
    )

    current_profit = (
        (current_price - unit_cost)
        *
        predicted_demand
    )


    return {
        "status": "AUTO_RECOMMEND",
        "item_id": item_id,

        "snapshot_date":
        snapshot["date"],

        "current_price":
        current_price,

        "unit_cost":
        float(unit_cost),

        "forecast_demand":
        predicted_demand,

        "elasticity":
        elasticity_info[
            "elasticity"
        ],

        "classification":
        elasticity_info[
            "classification"
        ],

        "current_expected_revenue":
        current_revenue,

        "current_expected_profit":
        current_profit,

        "candidate_prices":
        approved_prices,

        "revenue_maximizing_price":
        optimization[
            "revenue_maximizing_price"
        ],

        "profit_maximizing_price":
        optimization[
            "profit_maximizing_price"
        ],

        "expected_revenue_at_revenue_optimum":
        optimization[
            "expected_revenue_at_revenue_optimum"
        ],

        "expected_profit_at_profit_optimum":
        optimization[
            "expected_profit_at_profit_optimum"
        ],

        "expected_profit_uplift_pct":
        optimization[
            "expected_profit_uplift_pct"
        ],

        "forecast_demand_at_profit_optimum":
        optimization[
            "forecast_demand_at_profit_optimum"
        ],

        "guardrail_max_change_pct":
        max_change_pct * 100,

        "scenarios":
        optimization[
            "scenarios"
        ]
    }
'''

if "def recommend_profit_auto(" not in text:

    text += profit_auto_code

    path.write_text(
        text,
        encoding="utf-8"
    )

    print(
        "Automatic profit-aware backend added successfully!"
    )

else:

    print(
        "Automatic profit-aware backend already exists."
    )

Automatic profit-aware backend added successfully!

In [162]:
import importlib
import src.pricing_engine as pe

importlib.reload(pe)

profit_auto_result = pe.recommend_profit_auto(
    item_id="HOBBIES_1_295",
    unit_cost=0.30,
    max_change_pct=0.10
)

profit_auto_result

{'status': 'AUTO_RECOMMEND',
 'item_id': 'HOBBIES_1_295',
 'snapshot_date': '2016-05-22',
 'current_price': 0.48,
 'unit_cost': 0.3,
 'forecast_demand': 9.202316043705068,
 'elasticity': -0.0364939817461,
 'classification': 'Inelastic',
 'current_expected_revenue': 4.417111700978432,
 'current_expected_profit': 1.656416887866912,
 'candidate_prices': [0.43, 0.46, 0.48, 0.5, 0.53],
 'revenue_maximizing_price': 0.53,
 'profit_maximizing_price': 0.53,
 'expected_revenue_at_revenue_optimum': 4.859622219245533,
 'expected_profit_at_profit_optimum': 2.108892661182024,
 'expected_profit_uplift_pct': 27.316539491323194,
 'forecast_demand_at_profit_optimum': 9.169098526878363,
 'guardrail_max_change_pct': 10.0,
 'scenarios': [{'price': 0.43,
   'forecast_demand': 9.23933179902493,
   'expected_revenue': 3.9729126735807196,
   'expected_profit': 1.2011131338732408,
   'gross_margin_pct': 30.232558139534888},
  {'price': 0.46,
   'forecast_demand': 9.216619908287727,
   'expected_revenue': 4.239645157812355,
   'expected_profit': 1.4746591853260367,
   'gross_margin_pct': 34.78260869565218},
  {'price': 0.48,
   'forecast_demand': 9.202316043705068,
   'expected_revenue': 4.417111700978432,
   'expected_profit': 1.656416887866912,
   'gross_margin_pct': 37.5},
  {'price': 0.5,
   'forecast_demand': 9.188617034464036,
   'expected_revenue': 4.594308517232018,
   'expected_profit': 1.8377234068928072,
   'gross_margin_pct': 40.0},
  {'price': 0.53,
   'forecast_demand': 9.169098526878363,
   'expected_revenue': 4.859622219245533,
   'expected_profit': 2.108892661182024,
   'gross_margin_pct': 43.39622641509435}]}

In [163]:
from pathlib import Path

path = Path("api/app.py")
text = path.read_text(encoding="utf-8")

profit_endpoint_code = r'''

# ============================================================
# BACKEND V3 — PROFIT-AWARE API
# ============================================================

from src.pricing_engine import recommend_profit_auto


class ProfitAutoRequest(BaseModel):
    item_id: str
    unit_cost: float
    max_change_pct: float = 0.10


@app.post("/recommend-profit-auto")
def recommend_profit(
    request: ProfitAutoRequest
):
    """
    Generate an automatic pricing recommendation
    using both revenue and profit optimization.
    """

    if request.unit_cost < 0:
        raise HTTPException(
            status_code=400,
            detail="unit_cost cannot be negative."
        )

    if (
        request.max_change_pct <= 0
        or request.max_change_pct > 0.25
    ):
        raise HTTPException(
            status_code=400,
            detail=(
                "max_change_pct must be greater than 0 "
                "and no higher than 0.25."
            )
        )

    result = recommend_profit_auto(
        item_id=request.item_id,
        unit_cost=request.unit_cost,
        max_change_pct=request.max_change_pct
    )

    if result["status"] == "NOT_FOUND":
        raise HTTPException(
            status_code=404,
            detail=result["reason"]
        )

    if result["status"] == "INVALID_INPUT":
        raise HTTPException(
            status_code=400,
            detail=result["reason"]
        )

    return result
'''

if '/recommend-profit-auto' not in text:

    text += profit_endpoint_code

    path.write_text(
        text,
        encoding="utf-8"
    )

    print("Profit-aware FastAPI endpoint added successfully!")

else:

    print("Profit-aware endpoint already exists.")

Profit-aware FastAPI endpoint added successfully!

In [164]:
from pathlib import Path

path = Path("tests/test_project.py")
text = path.read_text(encoding="utf-8")

profit_tests = r'''


def test_profit_auto_endpoint():

    payload = {
        "item_id": "HOBBIES_1_295",
        "unit_cost": 0.30,
        "max_change_pct": 0.10
    }

    response = client.post(
        "/recommend-profit-auto",
        json=payload
    )

    assert response.status_code == 200

    data = response.json()

    assert data["status"] == "AUTO_RECOMMEND"
    assert data["item_id"] == "HOBBIES_1_295"
    assert data["unit_cost"] == 0.30

    assert "revenue_maximizing_price" in data
    assert "profit_maximizing_price" in data
    assert "expected_profit_at_profit_optimum" in data
    assert "expected_profit_uplift_pct" in data
    assert "scenarios" in data


def test_profit_auto_negative_cost():

    payload = {
        "item_id": "HOBBIES_1_295",
        "unit_cost": -0.10,
        "max_change_pct": 0.10
    }

    response = client.post(
        "/recommend-profit-auto",
        json=payload
    )

    assert response.status_code == 400


def test_profit_auto_excessive_price_change():

    payload = {
        "item_id": "HOBBIES_1_295",
        "unit_cost": 0.30,
        "max_change_pct": 0.50
    }

    response = client.post(
        "/recommend-profit-auto",
        json=payload
    )

    assert response.status_code == 400
'''

if "def test_profit_auto_endpoint(" not in text:

    text += profit_tests

    path.write_text(
        text,
        encoding="utf-8"
    )

    print("Profit-aware API tests added successfully!")

else:

    print("Profit-aware API tests already exist.")

Profit-aware API tests added successfully!

In [165]:

from pathlib import Path

profit_page = r'''
import streamlit as st
import requests
import pandas as pd
from pathlib import Path

API_URL = "http://127.0.0.1:8001"

BASE_DIR = Path(__file__).resolve().parent.parent.parent

DATA_FILE = (
    BASE_DIR
    / "data"
    / "master_product_elasticities.csv"
)

st.set_page_config(
    page_title="Profit Optimization",
    page_icon="◈",
    layout="wide"
)

st.title("Revenue & Profit Optimization")

st.caption(
    "AI-powered pricing decisions combining demand forecasting, "
    "price elasticity, commercial guardrails and gross-profit optimization."
)


@st.cache_data
def load_products():
    return pd.read_csv(DATA_FILE)


products = load_products()

product_list = sorted(
    products["item_id"].unique()
)

default_index = (
    product_list.index("HOBBIES_1_295")
    if "HOBBIES_1_295" in product_list
    else 0
)

item_id = st.selectbox(
    "Select Product",
    product_list,
    index=default_index
)

product = products[
    products["item_id"] == item_id
].iloc[0]


# PRODUCT CONTEXT

c1, c2, c3 = st.columns(3)

c1.metric(
    "Elasticity",
    f"{product['elasticity']:.3f}"
)

c2.metric(
    "Classification",
    product["classification"]
)

c3.metric(
    "Historical Avg. Price",
    f"{product['avg_price']:.2f}"
)


st.divider()


# BUSINESS INPUTS

st.subheader("Commercial Inputs")

left, right = st.columns(2)

with left:

    default_cost = max(
        round(
            float(product["avg_price"]) * 0.60,
            2
        ),
        0.01
    )

    unit_cost = st.number_input(
        "Unit Cost",
        min_value=0.00,
        value=default_cost,
        step=0.01,
        help=(
            "Unit cost is a business input because "
            "the M5 dataset does not provide product costs."
        )
    )


with right:

    max_change_pct = st.slider(
        "Maximum Allowed Price Change",
        min_value=0.05,
        max_value=0.25,
        value=0.10,
        step=0.01,
        format="%.0f%%"
    )


st.info(
    "The engine automatically retrieves the latest product features, "
    "forecasts demand, loads elasticity, generates candidate prices "
    "and applies pricing guardrails."
)


if st.button(
    "Run AI Pricing Optimization",
    type="primary",
    use_container_width=True
):

    payload = {
        "item_id": item_id,
        "unit_cost": unit_cost,
        "max_change_pct": max_change_pct
    }

    try:

        response = requests.post(
            f"{API_URL}/recommend-profit-auto",
            json=payload,
            timeout=15
        )

        if response.status_code != 200:

            st.error(
                f"Backend error: {response.text}"
            )

            st.stop()


        result = response.json()


        # MANUAL REVIEW

        if result["status"] == "MANUAL_REVIEW":

            st.warning(
                "Human Review Required"
            )

            st.write(
                result.get(
                    "reason",
                    "The recommendation did not pass governance rules."
                )
            )

            st.stop()


        # AUTO RECOMMEND

        st.success(
            "AI Pricing Recommendation Generated"
        )


        st.subheader("Executive Recommendation")

        m1, m2, m3, m4 = st.columns(4)

        m1.metric(
            "Current Price",
            f"{result['current_price']:.2f}"
        )

        m2.metric(
            "Revenue-Max Price",
            f"{result['revenue_maximizing_price']:.2f}"
        )

        m3.metric(
            "Profit-Max Price",
            f"{result['profit_maximizing_price']:.2f}"
        )

        m4.metric(
            "Expected Profit Uplift",
            f"{result['expected_profit_uplift_pct']:.2f}%"
        )


        st.divider()


        # ECONOMICS

        st.subheader("Unit Economics")

        e1, e2, e3, e4 = st.columns(4)

        e1.metric(
            "Unit Cost",
            f"{result['unit_cost']:.2f}"
        )

        e2.metric(
            "Forecast Demand",
            f"{result['forecast_demand']:.2f}"
        )

        e3.metric(
            "Current Expected Profit",
            f"{result['current_expected_profit']:.2f}"
        )

        e4.metric(
            "Optimized Expected Profit",
            f"{result['expected_profit_at_profit_optimum']:.2f}"
        )


        # SCENARIOS

        scenarios = pd.DataFrame(
            result["scenarios"]
        ).sort_values("price")


        st.divider()

        st.subheader("Pricing Scenario Analysis")

        st.dataframe(
            scenarios,
            use_container_width=True,
            hide_index=True
        )


        left_chart, right_chart = st.columns(2)


        with left_chart:

            st.subheader(
                "Expected Revenue"
            )

            st.line_chart(
                scenarios
                .set_index("price")[
                    ["expected_revenue"]
                ]
            )


        with right_chart:

            st.subheader(
                "Expected Profit"
            )

            st.line_chart(
                scenarios
                .set_index("price")[
                    ["expected_profit"]
                ]
            )


        st.subheader(
            "Demand Response"
        )

        st.line_chart(
            scenarios
            .set_index("price")[
                ["forecast_demand"]
            ]
        )


        st.caption(
            f"Business guardrail: ±"
            f"{result['guardrail_max_change_pct']:.0f}% "
            "around the current selling price."
        )


    except requests.exceptions.ConnectionError:

        st.error(
            "FastAPI is offline. Start the backend on port 8001."
        )

    except Exception as e:

        st.error(
            f"Unexpected error: {e}"
        )
'''

Path(
    "dashboard/pages/3_Profit_Optimization.py"
).write_text(
    profit_page,
    encoding="utf-8"
)

print("Profit Optimization dashboard created successfully!")

Profit Optimization dashboard created successfully!

In [166]:
from pathlib import Path

path = Path("dashboard/pages/3_Profit_Optimization.py")
text = path.read_text(encoding="utf-8")

old = '''    max_change_pct = st.slider(
        "Maximum Allowed Price Change",
        min_value=0.05,
        max_value=0.25,
        value=0.10,
        step=0.01,
        format="%.0f%%"
    )'''

new = '''    max_change_percent = st.slider(
        "Maximum Allowed Price Change",
        min_value=5,
        max_value=25,
        value=10,
        step=1,
        format="%d%%"
    )

    max_change_pct = max_change_percent / 100'''

if old in text:
    text = text.replace(old, new)
    path.write_text(text, encoding="utf-8")
    print("Percentage slider fixed successfully!")
else:
    print("Slider block not found.")

Percentage slider fixed successfully!

In [167]:
from pathlib import Path

path = Path("src/pricing_engine.py")
text = path.read_text(encoding="utf-8")

explanation_code = r'''

# ============================================================
# BACKEND V4 — EXECUTIVE DECISION EXPLANATION
# ============================================================

def build_pricing_explanation(result):
    """
    Convert pricing-engine outputs into a concise
    executive decision explanation and governance checks.
    """

    if result.get("status") != "AUTO_RECOMMEND":

        return {
            "decision_summary": (
                result.get(
                    "reason",
                    "Recommendation requires human review."
                )
            ),
            "governance_checks": {
                "automatic_recommendation": False
            }
        }


    current_price = float(
        result["current_price"]
    )

    recommended_price = float(
        result["profit_maximizing_price"]
    )

    elasticity = float(
        result["elasticity"]
    )

    classification = result[
        "classification"
    ]

    profit_uplift = float(
        result["expected_profit_uplift_pct"]
    )

    max_change = float(
        result["guardrail_max_change_pct"]
    )

    unit_cost = float(
        result["unit_cost"]
    )


    # ------------------------------------------
    # Price direction
    # ------------------------------------------

    if recommended_price > current_price:

        direction_text = (
            f"Increase the price from "
            f"{current_price:.2f} to "
            f"{recommended_price:.2f}."
        )

    elif recommended_price < current_price:

        direction_text = (
            f"Decrease the price from "
            f"{current_price:.2f} to "
            f"{recommended_price:.2f}."
        )

    else:

        direction_text = (
            f"Maintain the current price at "
            f"{current_price:.2f}."
        )


    # ------------------------------------------
    # Elasticity interpretation
    # ------------------------------------------

    if classification == "Inelastic":

        elasticity_text = (
            "The SKU is relatively price-inelastic, "
            "so forecast demand is expected to remain "
            "comparatively stable under moderate price changes."
        )

    elif classification == "Elastic":

        elasticity_text = (
            "The SKU is price-sensitive, so demand may "
            "respond materially to price changes."
        )

    else:

        elasticity_text = (
            "The estimated price-response relationship "
            "requires additional validation."
        )


    # ------------------------------------------
    # Profit interpretation
    # ------------------------------------------

    if profit_uplift > 0:

        profit_text = (
            f"The selected price is expected to improve "
            f"gross profit by approximately "
            f"{profit_uplift:.1f}%."
        )

    elif profit_uplift < 0:

        profit_text = (
            f"The scenario implies an expected gross-profit "
            f"change of {profit_uplift:.1f}%."
        )

    else:

        profit_text = (
            "The selected scenario does not materially "
            "change expected gross profit."
        )


    guardrail_text = (
        f"The recommendation remains inside the configured "
        f"±{max_change:.0f}% pricing guardrail."
    )


    decision_summary = " ".join(
        [
            direction_text,
            elasticity_text,
            profit_text,
            guardrail_text
        ]
    )


    # ------------------------------------------
    # Governance checks
    # ------------------------------------------

    price_change_pct = (
        (
            recommended_price
            -
            current_price
        )
        /
        current_price
        *
        100
        if current_price > 0
        else 0
    )


    governance_checks = {
        "elasticity_accepted":
        classification in [
            "Elastic",
            "Inelastic"
        ],

        "automatic_recommendation":
        result["status"]
        ==
        "AUTO_RECOMMEND",

        "price_within_guardrails":
        abs(price_change_pct)
        <=
        max_change + 0.01,

        "price_above_unit_cost":
        recommended_price
        >
        unit_cost,

        "positive_expected_profit":
        result[
            "expected_profit_at_profit_optimum"
        ]
        >
        0
    }


    return {
        "decision_summary":
        decision_summary,

        "governance_checks":
        governance_checks
    }
'''

if "def build_pricing_explanation(" not in text:

    text += explanation_code

    path.write_text(
        text,
        encoding="utf-8"
    )

    print(
        "Executive Decision Explanation engine added successfully!"
    )

else:

    print(
        "Decision Explanation engine already exists."
    )

Executive Decision Explanation engine added successfully!

In [168]:
import importlib
import src.pricing_engine as pe

importlib.reload(pe)

result = pe.recommend_profit_auto(
    item_id="HOBBIES_1_295",
    unit_cost=0.30,
    max_change_pct=0.10
)

explanation = pe.build_pricing_explanation(
    result
)

explanation

{'decision_summary': 'Increase the price from 0.48 to 0.53. The SKU is relatively price-inelastic, so forecast demand is expected to remain comparatively stable under moderate price changes. The selected price is expected to improve gross profit by approximately 27.3%. The recommendation remains inside the configured ±10% pricing guardrail.',
 'governance_checks': {'elasticity_accepted': True,
  'automatic_recommendation': True,
  'price_within_guardrails': False,
  'price_above_unit_cost': True,
  'positive_expected_profit': True}}

In [169]:
from pathlib import Path

path = Path("src/pricing_engine.py")
text = path.read_text(encoding="utf-8")

old = '''    minimum_price = round(
        base_price * (1 - max_change_pct),
        2
    )

    maximum_price = round(
        base_price * (1 + max_change_pct),
        2
    )'''

new = '''    import math

    # Strict commercial guardrails on a 2-decimal price grid.
    # Lower limit rounds UP and upper limit rounds DOWN,
    # ensuring the configured percentage is never exceeded.
    minimum_price = (
        math.ceil(
            base_price * (1 - max_change_pct) * 100
        )
        / 100
    )

    maximum_price = (
        math.floor(
            base_price * (1 + max_change_pct) * 100
        )
        / 100
    )'''

if old in text:
    text = text.replace(old, new)
    path.write_text(text, encoding="utf-8")
    print("Strict pricing guardrails fixed successfully!")
else:
    print("Guardrail block not found.")

Strict pricing guardrails fixed successfully!

In [170]:
import importlib
import src.pricing_engine as pe

importlib.reload(pe)

result = pe.recommend_profit_auto(
    item_id="HOBBIES_1_295",
    unit_cost=0.30,
    max_change_pct=0.10
)

explanation = pe.build_pricing_explanation(result)

print("Candidates:", result["candidate_prices"])
print("Recommended:", result["profit_maximizing_price"])
print("Governance:", explanation["governance_checks"])
print()
print(explanation["decision_summary"])

Candidates: [0.46, 0.48, 0.5]
Recommended: 0.5
Governance: {'elasticity_accepted': True, 'automatic_recommendation': True, 'price_within_guardrails': True, 'price_above_unit_cost': True, 'positive_expected_profit': True}

Increase the price from 0.48 to 0.50. The SKU is relatively price-inelastic, so forecast demand is expected to remain comparatively stable under moderate price changes. The selected price is expected to improve gross profit by approximately 10.9%. The recommendation remains inside the configured ±10% pricing guardrail.

In [171]:
from pathlib import Path

path = Path("src/pricing_engine.py")
text = path.read_text(encoding="utf-8")

start = text.index("def generate_candidate_prices(")
end = text.index("\ndef validate_price_guardrails(", start)

new_function = '''def generate_candidate_prices(
    base_price,
    max_change_pct=0.10
):
    """
    Generate five cent-level candidate prices while
    strictly respecting the configured price-change limit.
    """

    import math

    minimum_price = (
        math.ceil(
            base_price * (1 - max_change_pct) * 100
        )
        / 100
    )

    maximum_price = (
        math.floor(
            base_price * (1 + max_change_pct) * 100
        )
        / 100
    )

    current_price = round(
        base_price,
        2
    )

    lower_mid = round(
        (minimum_price + current_price) / 2,
        2
    )

    upper_mid = round(
        (current_price + maximum_price) / 2,
        2
    )

    prices = [
        minimum_price,
        lower_mid,
        current_price,
        upper_mid,
        maximum_price
    ]

    return sorted(
        set(
            price
            for price in prices
            if price > 0
        )
    )

'''

text = (
    text[:start]
    + new_function
    + text[end + 1:]
)

path.write_text(
    text,
    encoding="utf-8"
)

print("Strict 5-price candidate generator added successfully!")

Strict 5-price candidate generator added successfully!

In [172]:
import importlib
import src.pricing_engine as pe

importlib.reload(pe)

result = pe.recommend_profit_auto(
    item_id="HOBBIES_1_295",
    unit_cost=0.30,
    max_change_pct=0.10
)

explanation = pe.build_pricing_explanation(
    result
)

print("Candidates:", result["candidate_prices"])
print("Recommended:", result["profit_maximizing_price"])
print("Governance:", explanation["governance_checks"])

Candidates: [0.44, 0.46, 0.48, 0.5, 0.52]
Recommended: 0.52
Governance: {'elasticity_accepted': True, 'automatic_recommendation': True, 'price_within_guardrails': True, 'price_above_unit_cost': True, 'positive_expected_profit': True}

In [173]:
from pathlib import Path

path = Path("api/app.py")
text = path.read_text(encoding="utf-8")

# Add explanation function to the V3 import
text = text.replace(
    "from src.pricing_engine import recommend_profit_auto",
    "from src.pricing_engine import recommend_profit_auto, build_pricing_explanation"
)

old = '''    if result["status"] == "INVALID_INPUT":
        raise HTTPException(
            status_code=400,
            detail=result["reason"]
        )

    return result'''

new = '''    if result["status"] == "INVALID_INPUT":
        raise HTTPException(
            status_code=400,
            detail=result["reason"]
        )

    explanation = build_pricing_explanation(
        result
    )

    result["decision_summary"] = explanation[
        "decision_summary"
    ]

    result["governance_checks"] = explanation[
        "governance_checks"
    ]

    return result'''

if old in text:

    text = text.replace(
        old,
        new
    )

    path.write_text(
        text,
        encoding="utf-8"
    )

    print(
        "Executive explanation connected to FastAPI successfully!"
    )

else:

    print(
        "Target API block not found or already updated."
    )

Executive explanation connected to FastAPI successfully!

In [174]:
from pathlib import Path

path = Path("dashboard/pages/3_Profit_Optimization.py")
text = path.read_text(encoding="utf-8")

old = '''        st.success(
            "AI Pricing Recommendation Generated"
        )


        st.subheader("Executive Recommendation")'''

new = '''        st.success(
            "AI Pricing Recommendation Generated"
        )


        # ====================================================
        # EXECUTIVE DECISION
        # ====================================================

        st.subheader("Executive Decision")

        st.info(
            result.get(
                "decision_summary",
                "Executive explanation unavailable."
            )
        )


        # ====================================================
        # GOVERNANCE STATUS
        # ====================================================

        st.subheader("Governance Status")

        governance = result.get(
            "governance_checks",
            {}
        )

        labels = {
            "elasticity_accepted":
                "Elasticity Accepted",

            "automatic_recommendation":
                "Auto Recommendation",

            "price_within_guardrails":
                "Within Guardrails",

            "price_above_unit_cost":
                "Above Unit Cost",

            "positive_expected_profit":
                "Positive Profit"
        }

        governance_columns = st.columns(5)

        for column, (key, label) in zip(
            governance_columns,
            labels.items()
        ):

            value = governance.get(
                key,
                False
            )

            with column:

                if value:
                    st.success(
                        f"✓ {label}"
                    )

                else:
                    st.error(
                        f"✕ {label}"
                    )


        st.divider()

        st.subheader("Executive Recommendation")'''

if old in text:

    text = text.replace(
        old,
        new
    )

    path.write_text(
        text,
        encoding="utf-8"
    )

    print(
        "Executive Decision panel added successfully!"
    )

else:

    print(
        "Target dashboard block not found or already updated."
    )

Executive Decision panel added successfully!

In [175]:
from pathlib import Path
import re

path = Path("tests/test_project.py")
text = path.read_text(encoding="utf-8")

text, count = re.subn(
    r'assert\s+data\["recommended_price"\]\s*==\s*0\.53',
    'assert data["recommended_price"] == 0.52',
    text
)

path.write_text(
    text,
    encoding="utf-8"
)

print("Assertions updated:", count)

Assertions updated: 1

In [176]:
from pathlib import Path

path = Path("src/pricing_engine.py")
text = path.read_text(encoding="utf-8")

portfolio_code = r'''

# ============================================================
# BACKEND V5 — PORTFOLIO OPPORTUNITY ENGINE
# ============================================================

def build_portfolio_opportunities(
    max_change_pct=0.10,
    top_n=None
):
    """
    Scan eligible products and rank automatic
    repricing opportunities by expected revenue gain.
    """

    opportunities = []

    eligible_products = elasticity_table[
        elasticity_table["classification"].isin(
            ["Elastic", "Inelastic"]
        )
    ]["item_id"].unique()


    for item_id in eligible_products:

        try:

            result = recommend_price_auto(
                item_id=item_id,
                max_change_pct=max_change_pct
            )

            if result.get("status") != "AUTO_RECOMMEND":
                continue


            current_revenue = float(
                result["current_expected_revenue"]
            )

            recommended_revenue = float(
                result["recommended_expected_revenue"]
            )

            revenue_gain = (
                recommended_revenue
                -
                current_revenue
            )


            price_change_pct = (
                (
                    result["recommended_price"]
                    -
                    result["current_price"]
                )
                /
                result["current_price"]
                *
                100
                if result["current_price"] > 0
                else 0
            )


            opportunities.append({
                "item_id":
                    item_id,

                "classification":
                    result["classification"],

                "elasticity":
                    result["elasticity"],

                "current_price":
                    result["current_price"],

                "recommended_price":
                    result["recommended_price"],

                "price_change_pct":
                    price_change_pct,

                "forecast_demand":
                    result["forecast_demand"],

                "current_expected_revenue":
                    current_revenue,

                "recommended_expected_revenue":
                    recommended_revenue,

                "expected_revenue_gain":
                    revenue_gain,

                "expected_revenue_uplift_pct":
                    result[
                        "expected_revenue_uplift_pct"
                    ],

                "snapshot_date":
                    result["snapshot_date"]
            })


        except Exception:
            continue


    portfolio = pd.DataFrame(
        opportunities
    )


    if portfolio.empty:
        return portfolio


    portfolio = portfolio.sort_values(
        [
            "expected_revenue_gain",
            "expected_revenue_uplift_pct"
        ],
        ascending=False
    ).reset_index(drop=True)


    portfolio.insert(
        0,
        "rank",
        range(
            1,
            len(portfolio) + 1
        )
    )


    if top_n is not None:

        portfolio = portfolio.head(
            int(top_n)
        )


    return portfolio
'''

if "def build_portfolio_opportunities(" not in text:

    text += portfolio_code

    path.write_text(
        text,
        encoding="utf-8"
    )

    print(
        "Portfolio Opportunity Engine added successfully!"
    )

else:

    print(
        "Portfolio Opportunity Engine already exists."
    )

Portfolio Opportunity Engine added successfully!

In [178]:
from pathlib import Path

path = Path("src/pricing_engine.py")
text = path.read_text(encoding="utf-8")

old = '''    opportunities = []

    eligible_products = elasticity_table[
        elasticity_table["classification"].isin(
            ["Elastic", "Inelastic"]
        )
    ]["item_id"].unique()'''

new = '''    opportunities = []

    portfolio_elasticity_table = pd.read_csv(
        ELASTICITY_PATH
    )

    eligible_products = portfolio_elasticity_table[
        portfolio_elasticity_table["classification"].isin(
            ["Elastic", "Inelastic"]
        )
    ]["item_id"].unique()'''

if old in text:

    text = text.replace(old, new)

    path.write_text(
        text,
        encoding="utf-8"
    )

    print("Portfolio elasticity loading fixed successfully!")

else:

    print("Target block not found.")

Portfolio elasticity loading fixed successfully!

In [180]:
import importlib
import src.pricing_engine as pe

importlib.reload(pe)

portfolio_opportunities = pe.build_portfolio_opportunities(
    max_change_pct=0.10,
    top_n=20
)

portfolio_opportunities

,rank,item_id,classification,elasticity,current_price,recommended_price,price_change_pct,forecast_demand,current_expected_revenue,recommended_expected_revenue,expected_revenue_gain,expected_revenue_uplift_pct,snapshot_date
0,1,FOODS_3_064,Elastic,-3.615252,1.18,1.07,-9.322034,39.175937,46.227605,59.709713,13.482108,29.164626,2016-05-22
1,2,FOODS_3_124,Inelastic,-0.022289,5.44,5.98,9.926471,10.663683,58.010438,63.634448,5.624010,9.694825,2016-05-22
2,3,FOODS_3_202,Inelastic,-0.406057,4.68,5.14,9.829060,18.336316,85.813957,90.728070,4.914113,5.726473,2016-05-22
3,4,FOODS_3_469,Inelastic,-0.051212,5.98,6.57,9.866221,7.559981,45.208687,49.430313,4.221626,9.338085,2016-05-22
4,5,FOODS_3_534,Inelastic,-0.119746,4.88,5.36,9.836066,9.616580,46.928909,50.969033,4.040124,8.609031,2016-05-22
5,6,FOODS_3_535,Inelastic,-0.203412,5.98,6.57,9.866221,7.916719,47.341981,51.026803,3.684822,7.783413,2016-05-22
6,7,FOODS_2_052,Inelastic,-0.091582,13.97,15.36,9.949893,2.888293,40.349450,43.980454,3.631004,8.998894,2016-05-22
7,8,FOODS_3_324,Inelastic,-0.399543,3.00,3.30,10.000000,19.102728,57.308184,60.683579,3.375395,5.889901,2016-05-22
8,9,FOODS_3_083,Inelastic,-0.141041,18.73,20.60,9.983983,1.947336,36.473599,39.580286,3.106687,8.517632,2016-05-22
9,10,FOODS_3_697,Inelastic,-0.405468,3.00,3.30,10.000000,16.448154,49.344463,52.221301,2.876838,5.830114,2016-05-22
10,11,FOODS_3_473,Inelastic,-0.251148,4.18,4.59,9.808612,9.448110,39.493101,42.359605,2.866505,7.258241,2016-05-22
11,12,FOODS_2_276,Inelastic,-0.236303,3.42,3.76,9.941520,10.061313,34.409691,36.992686,2.582996,7.506593,2016-05-22
12,13,FOODS_2_060,Inelastic,-0.027241,7.98,8.77,9.899749,3.112309,24.836223,27.224848,2.388625,9.617504,2016-05-22
13,14,FOODS_2_194,Inelastic,-0.230611,6.72,7.39,9.970238,4.646696,31.225798,33.594655,2.368857,7.586218,2016-05-22
14,15,FOODS_2_029,Elastic,-1.295129,9.98,8.99,-9.919840,7.032049,70.179847,72.377348,2.197501,3.131242,2016-05-22
15,16,FOODS_3_363,Inelastic,-0.430103,2.77,3.04,9.747292,14.180953,39.281240,41.419560,2.138321,5.443619,2016-05-22
16,17,HOBBIES_1_141,Inelastic,-0.393482,13.98,15.37,9.942775,2.513218,35.134793,37.213946,2.079153,5.917648,2016-05-22
17,18,FOODS_1_088,Inelastic,-0.368173,5.28,5.80,9.848485,6.351726,33.537111,35.587742,2.050630,6.114511,2016-05-22
18,19,FOODS_3_681,Elastic,-1.667788,1.00,0.90,-10.000000,26.732481,26.732481,28.681084,1.948603,7.289270,2016-05-22
19,20,FOODS_3_298,Inelastic,-0.101440,18.73,20.60,9.983983,1.085443,20.330347,22.145310,1.814963,8.927357,2016-05-22

In [182]:
portfolio_opportunities.to_csv(
    "data/portfolio_opportunities.csv",
    index=False
)

print("Portfolio opportunities saved successfully!")
print("Rows saved:", len(portfolio_opportunities))

Portfolio opportunities saved successfully!
Rows saved: 20

In [183]:
from pathlib import Path

portfolio_page = r'''
import streamlit as st
import pandas as pd
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent

DATA_FILE = (
    BASE_DIR
    / "data"
    / "portfolio_opportunities.csv"
)

st.set_page_config(
    page_title="Portfolio Opportunities",
    page_icon="◈",
    layout="wide"
)

st.title("Portfolio Pricing Opportunities")

st.caption(
    "Portfolio-level ranking of the strongest automated repricing opportunities."
)

@st.cache_data
def load_data():
    return pd.read_csv(DATA_FILE)

df = load_data()

# ---------------------------
# FILTERS
# ---------------------------

st.subheader("Opportunity Filters")

f1, f2, f3 = st.columns(3)

with f1:
    classifications = ["All"] + sorted(
        df["classification"].dropna().unique().tolist()
    )

    classification_filter = st.selectbox(
        "Classification",
        classifications
    )

with f2:
    min_uplift = st.slider(
        "Minimum Revenue Uplift",
        min_value=0.0,
        max_value=float(
            max(
                1.0,
                round(
                    df["expected_revenue_uplift_pct"].max(),
                    1
                )
            )
        ),
        value=0.0,
        step=0.5,
        format="%.1f%%"
    )

with f3:
    top_n = st.slider(
        "Top Opportunities",
        min_value=5,
        max_value=min(20, len(df)),
        value=min(10, len(df)),
        step=1
    )


filtered = df.copy()

if classification_filter != "All":
    filtered = filtered[
        filtered["classification"] == classification_filter
    ]

filtered = filtered[
    filtered["expected_revenue_uplift_pct"] >= min_uplift
]

filtered = filtered.head(top_n)


# ---------------------------
# KPIs
# ---------------------------

st.divider()

k1, k2, k3, k4 = st.columns(4)

k1.metric(
    "Displayed Opportunities",
    len(filtered)
)

k2.metric(
    "Average Revenue Uplift",
    (
        f"{filtered['expected_revenue_uplift_pct'].mean():.2f}%"
        if not filtered.empty
        else "0.00%"
    )
)

k3.metric(
    "Total Expected Revenue Gain",
    (
        f"{filtered['expected_revenue_gain'].sum():.2f}"
        if not filtered.empty
        else "0.00"
    )
)

k4.metric(
    "Largest Single Revenue Gain",
    (
        f"{filtered['expected_revenue_gain'].max():.2f}"
        if not filtered.empty
        else "0.00"
    )
)


# ---------------------------
# RANKING
# ---------------------------

st.divider()

st.subheader("Top Pricing Opportunities")

display_cols = [
    "rank",
    "item_id",
    "classification",
    "elasticity",
    "current_price",
    "recommended_price",
    "price_change_pct",
    "forecast_demand",
    "expected_revenue_gain",
    "expected_revenue_uplift_pct"
]

st.dataframe(
    filtered[display_cols],
    use_container_width=True,
    hide_index=True
)


# ---------------------------
# CHARTS
# ---------------------------

st.divider()

left, right = st.columns(2)

with left:

    st.subheader("Expected Revenue Gain")

    if not filtered.empty:

        chart_data = (
            filtered[
                [
                    "item_id",
                    "expected_revenue_gain"
                ]
            ]
            .set_index("item_id")
        )

        st.bar_chart(
            chart_data
        )


with right:

    st.subheader("Expected Revenue Uplift")

    if not filtered.empty:

        uplift_chart = (
            filtered[
                [
                    "item_id",
                    "expected_revenue_uplift_pct"
                ]
            ]
            .set_index("item_id")
        )

        st.bar_chart(
            uplift_chart
        )


# ---------------------------
# PRICE COMPARISON
# ---------------------------

st.divider()

st.subheader("Current vs Recommended Price")

if not filtered.empty:

    price_comparison = filtered[
        [
            "item_id",
            "current_price",
            "recommended_price"
        ]
    ].set_index("item_id")

    st.bar_chart(
        price_comparison
    )


# ---------------------------
# BUSINESS INTERPRETATION
# ---------------------------

st.divider()

st.subheader("Portfolio Interpretation")

if not filtered.empty:

    best = filtered.iloc[0]

    st.info(
        f"The highest-ranked opportunity is "
        f"{best['item_id']}. "
        f"The engine recommends moving the price from "
        f"{best['current_price']:.2f} to "
        f"{best['recommended_price']:.2f}, "
        f"with an estimated revenue uplift of "
        f"{best['expected_revenue_uplift_pct']:.2f}%."
    )

st.caption(
    "Portfolio ranking is based on expected revenue opportunity. "
    "Profit ranking requires reliable SKU-level unit-cost data."
)
'''

Path(
    "dashboard/pages/4_Portfolio_Opportunities.py"
).write_text(
    portfolio_page,
    encoding="utf-8"
)

print("Portfolio Opportunities dashboard created successfully!")

Portfolio Opportunities dashboard created successfully!

In [184]:
from pathlib import Path

path = Path("api/app.py")
text = path.read_text(encoding="utf-8")

portfolio_api_code = r'''

# ============================================================
# BACKEND V5 — PORTFOLIO OPPORTUNITIES API
# ============================================================

import json

from src.pricing_engine import build_portfolio_opportunities


@app.get("/portfolio-opportunities")
def get_portfolio_opportunities(
    top_n: int = 20,
    max_change_pct: float = 0.10
):
    """
    Rank the strongest automated pricing opportunities
    across the eligible product portfolio.
    """

    if top_n < 1 or top_n > 100:
        raise HTTPException(
            status_code=400,
            detail="top_n must be between 1 and 100."
        )

    if (
        max_change_pct <= 0
        or max_change_pct > 0.25
    ):
        raise HTTPException(
            status_code=400,
            detail=(
                "max_change_pct must be greater than 0 "
                "and no higher than 0.25."
            )
        )


    portfolio = build_portfolio_opportunities(
        max_change_pct=max_change_pct,
        top_n=top_n
    )


    if portfolio.empty:

        return {
            "summary": {
                "opportunities": 0,
                "total_expected_revenue_gain": 0.0,
                "average_revenue_uplift_pct": 0.0
            },
            "opportunities": []
        }


    # Convert DataFrame safely into JSON-native values
    records = json.loads(
        portfolio.to_json(
            orient="records"
        )
    )


    summary = {
        "opportunities":
            int(len(portfolio)),

        "total_expected_revenue_gain":
            float(
                portfolio[
                    "expected_revenue_gain"
                ].sum()
            ),

        "average_revenue_uplift_pct":
            float(
                portfolio[
                    "expected_revenue_uplift_pct"
                ].mean()
            ),

        "largest_expected_revenue_gain":
            float(
                portfolio[
                    "expected_revenue_gain"
                ].max()
            )
    }


    return {
        "summary": summary,
        "opportunities": records
    }
'''

if '/portfolio-opportunities' not in text:

    text += portfolio_api_code

    path.write_text(
        text,
        encoding="utf-8"
    )

    print(
        "Portfolio Opportunities API added successfully!"
    )

else:

    print(
        "Portfolio Opportunities API already exists."
    )

Portfolio Opportunities API added successfully!

In [185]:
from pathlib import Path

path = Path("dashboard/pages/4_Portfolio_Opportunities.py")
text = path.read_text(encoding="utf-8")

old = '''import streamlit as st
import pandas as pd
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent

DATA_FILE = (
    BASE_DIR
    / "data"
    / "portfolio_opportunities.csv"
)'''

new = '''import streamlit as st
import pandas as pd
import requests

API_URL = "http://127.0.0.1:8001"'''

text = text.replace(
    old,
    new
)

old_loader = '''@st.cache_data
def load_data():
    return pd.read_csv(DATA_FILE)

df = load_data()'''

new_loader = '''@st.cache_data(ttl=300)
def load_data(
    top_n=20,
    max_change_pct=0.10
):
    response = requests.get(
        f"{API_URL}/portfolio-opportunities",
        params={
            "top_n": top_n,
            "max_change_pct": max_change_pct
        },
        timeout=60
    )

    response.raise_for_status()

    payload = response.json()

    return (
        pd.DataFrame(
            payload["opportunities"]
        ),
        payload["summary"]
    )


try:

    df, api_summary = load_data(
        top_n=20,
        max_change_pct=0.10
    )

except requests.exceptions.ConnectionError:

    st.error(
        "FastAPI backend is offline. "
        "Start the backend on port 8001."
    )

    st.stop()

except Exception as e:

    st.error(
        f"Unable to load portfolio opportunities: {e}"
    )

    st.stop()'''

text = text.replace(
    old_loader,
    new_loader
)

path.write_text(
    text,
    encoding="utf-8"
)

print(
    "Portfolio dashboard connected to FastAPI successfully!"
)

Portfolio dashboard connected to FastAPI successfully!

In [186]:
from pathlib import Path

path = Path("tests/test_project.py")
text = path.read_text(encoding="utf-8")

portfolio_tests = r'''


def test_portfolio_opportunities_endpoint():

    response = client.get(
        "/portfolio-opportunities",
        params={
            "top_n": 5,
            "max_change_pct": 0.10
        }
    )

    assert response.status_code == 200

    data = response.json()

    assert "summary" in data
    assert "opportunities" in data

    assert len(data["opportunities"]) <= 5

    assert "opportunities" in data["summary"]
    assert "total_expected_revenue_gain" in data["summary"]
    assert "average_revenue_uplift_pct" in data["summary"]

    if data["opportunities"]:

        first = data["opportunities"][0]

        assert "rank" in first
        assert "item_id" in first
        assert "current_price" in first
        assert "recommended_price" in first
        assert "expected_revenue_gain" in first
        assert "expected_revenue_uplift_pct" in first


def test_portfolio_invalid_top_n():

    response = client.get(
        "/portfolio-opportunities",
        params={
            "top_n": 0,
            "max_change_pct": 0.10
        }
    )

    assert response.status_code == 400


def test_portfolio_invalid_guardrail():

    response = client.get(
        "/portfolio-opportunities",
        params={
            "top_n": 10,
            "max_change_pct": 0.50
        }
    )

    assert response.status_code == 400
'''

if "def test_portfolio_opportunities_endpoint(" not in text:

    text += portfolio_tests

    path.write_text(
        text,
        encoding="utf-8"
    )

    print("Portfolio API tests added successfully!")

else:

    print("Portfolio API tests already exist.")

Portfolio API tests added successfully!

In [187]:
import json
from pathlib import Path

model_metadata = {
    "model_name": "Demand Forecasting Engine",
    "model_type": "HistGradientBoostingRegressor",
    "version": "1.0.0",

    "status": "Production Ready",

    "evaluation": {
        "test_strategy": "Chronological 28-day holdout",
        "mae": 1.092,
        "rmse": 2.034,
        "r2": 0.680
    },

    "baseline": {
        "model": "Lag-1 Naive Forecast",
        "mae": 1.348,
        "rmse": 2.761,
        "r2": 0.411
    },

    "features": [
        "sell_price",
        "day_of_week",
        "month",
        "year",
        "demand_lag_1",
        "demand_lag_7",
        "rolling_mean_7",
        "rolling_mean_28"
    ],

    "governance": {
        "pricing_guardrails": True,
        "human_review": True,
        "elasticity_validation": True,
        "profit_guardrail": True
    }
}

Path("models/model_metadata.json").write_text(
    json.dumps(
        model_metadata,
        indent=4
    ),
    encoding="utf-8"
)

print("Model monitoring metadata created successfully!")

Model monitoring metadata created successfully!

In [188]:
from pathlib import Path

path = Path("api/app.py")
text = path.read_text(encoding="utf-8")

model_info_code = r'''

# ============================================================
# BACKEND V6 — MODEL MONITORING / METADATA API
# ============================================================

from pathlib import Path


@app.get("/model-info")
def model_info():
    """
    Return model performance, features,
    baseline comparison and governance metadata.
    """

    metadata_path = (
        Path(__file__).resolve().parent.parent
        / "models"
        / "model_metadata.json"
    )

    if not metadata_path.exists():
        raise HTTPException(
            status_code=404,
            detail="Model metadata file not found."
        )

    with open(
        metadata_path,
        "r",
        encoding="utf-8"
    ) as file:
        metadata = json.load(file)

    # Additional computed metrics
    model_mae = metadata["evaluation"]["mae"]
    baseline_mae = metadata["baseline"]["mae"]

    mae_improvement_pct = (
        (baseline_mae - model_mae)
        / baseline_mae
        * 100
    )

    metadata["computed_metrics"] = {
        "mae_improvement_vs_baseline_pct":
            mae_improvement_pct
    }

    return metadata
'''

if '/model-info' not in text:

    text += model_info_code

    path.write_text(
        text,
        encoding="utf-8"
    )

    print("Model Monitoring API added successfully!")

else:

    print("Model Monitoring API already exists.")

Model Monitoring API added successfully!

In [189]:
from pathlib import Path

monitoring_page = r'''
import streamlit as st
import pandas as pd
import requests

API_URL = "http://127.0.0.1:8001"

st.set_page_config(
    page_title="Model Monitoring",
    page_icon="◈",
    layout="wide"
)

st.title("Model Monitoring & Explainability")

st.caption(
    "Performance monitoring, baseline comparison, model features "
    "and governance controls for the demand forecasting engine."
)


# ============================================================
# LOAD MODEL METADATA FROM FASTAPI
# ============================================================

@st.cache_data(ttl=300)
def load_model_info():

    response = requests.get(
        f"{API_URL}/model-info",
        timeout=10
    )

    response.raise_for_status()

    return response.json()


try:

    model = load_model_info()

except requests.exceptions.ConnectionError:

    st.error(
        "FastAPI backend is offline. "
        "Start the backend on port 8001."
    )

    st.stop()

except Exception as e:

    st.error(
        f"Unable to load model information: {e}"
    )

    st.stop()


# ============================================================
# MODEL STATUS
# ============================================================

st.subheader("Model Status")

c1, c2, c3, c4 = st.columns(4)

c1.metric(
    "Model",
    model["model_type"]
)

c2.metric(
    "Version",
    model["version"]
)

c3.metric(
    "Status",
    model["status"]
)

c4.metric(
    "Evaluation Window",
    "28 Days"
)


# ============================================================
# PERFORMANCE
# ============================================================

st.divider()

st.subheader("Forecasting Performance")

evaluation = model["evaluation"]
baseline = model["baseline"]

improvement = model[
    "computed_metrics"
][
    "mae_improvement_vs_baseline_pct"
]

m1, m2, m3, m4 = st.columns(4)

m1.metric(
    "Test MAE",
    f"{evaluation['mae']:.3f}",
    delta=f"-{improvement:.1f}% vs baseline",
    delta_color="inverse"
)

m2.metric(
    "Test RMSE",
    f"{evaluation['rmse']:.3f}"
)

m3.metric(
    "Test R²",
    f"{evaluation['r2']:.3f}"
)

m4.metric(
    "MAE Improvement",
    f"{improvement:.1f}%"
)


# ============================================================
# BASELINE COMPARISON
# ============================================================

st.divider()

st.subheader("Model vs Baseline")

comparison = pd.DataFrame({
    "Model": [
        baseline["model"],
        model["model_type"]
    ],

    "MAE": [
        baseline["mae"],
        evaluation["mae"]
    ],

    "RMSE": [
        baseline["rmse"],
        evaluation["rmse"]
    ],

    "R²": [
        baseline["r2"],
        evaluation["r2"]
    ]
})

st.dataframe(
    comparison,
    use_container_width=True,
    hide_index=True
)

left, right = st.columns(2)

with left:

    st.markdown("#### MAE")

    st.bar_chart(
        comparison
        .set_index("Model")[
            ["MAE"]
        ]
    )


with right:

    st.markdown("#### RMSE")

    st.bar_chart(
        comparison
        .set_index("Model")[
            ["RMSE"]
        ]
    )


# ============================================================
# FEATURES
# ============================================================

st.divider()

st.subheader("Model Features")

feature_df = pd.DataFrame({
    "Feature": model["features"]
})

feature_df["Status"] = "Active"

st.dataframe(
    feature_df,
    use_container_width=True,
    hide_index=True
)

st.info(
    f"The forecasting model currently uses "
    f"{len(model['features'])} engineered features combining "
    "price, calendar information, demand lags and rolling demand signals."
)


# ============================================================
# GOVERNANCE CONTROLS
# ============================================================

st.divider()

st.subheader("Model Governance")

governance = model["governance"]

labels = {
    "pricing_guardrails":
        "Pricing Guardrails",

    "human_review":
        "Human Review",

    "elasticity_validation":
        "Elasticity Validation",

    "profit_guardrail":
        "Profit Protection"
}

columns = st.columns(4)

for column, (key, label) in zip(
    columns,
    labels.items()
):

    enabled = governance.get(
        key,
        False
    )

    with column:

        if enabled:

            st.success(
                f"✓ {label}"
            )

        else:

            st.error(
                f"✕ {label}"
            )


# ============================================================
# EVALUATION DESIGN
# ============================================================

st.divider()

st.subheader("Validation Design")

st.write(
    f"**Test strategy:** {evaluation['test_strategy']}"
)

st.write(
    """
    The forecasting model was evaluated on a chronological future
    holdout rather than a random train/test split. This reduces
    information leakage and better reflects a real forecasting workflow.
    """
)

st.warning(
    """
    Current evaluation uses lag-based one-step-ahead predictions.
    It should not be interpreted as a fully recursive 28-day forecast.
    """
)


# ============================================================
# EXPLAINABILITY PLACEHOLDER
# ============================================================

st.divider()

st.subheader("Model Explainability")

st.info(
    """
    Feature importance will be calculated using permutation importance
    on held-out observations. This avoids displaying unsupported or
    fabricated importance scores.
    """
)

st.caption(
    "AI Demand & Pricing Engine — Model Monitoring Layer"
)
'''

Path(
    "dashboard/pages/5_Model_Monitoring.py"
).write_text(
    monitoring_page,
    encoding="utf-8"
)

print("Model Monitoring dashboard created successfully!")

Model Monitoring dashboard created successfully!

In [190]:
for name in [
    "X_test",
    "y_test"
]:
    print(
        name,
        "exists:",
        name in globals()
    )

X_test exists: True
y_test exists: True

In [191]:
import json
import joblib
import pandas as pd

from pathlib import Path
from sklearn.inspection import permutation_importance


# Load the exact production model
model = joblib.load(
    "models/demand_forecaster.joblib"
)

# Load the exact model feature order
with open(
    "models/features.json",
    "r",
    encoding="utf-8"
) as f:
    feature_names = json.load(f)


# Use a representative test sample
# so permutation importance does not take too long
sample_size = min(
    10000,
    len(X_test)
)

X_explain = X_test[
    feature_names
].sample(
    n=sample_size,
    random_state=42
)

y_explain = y_test.loc[
    X_explain.index
]


# Calculate permutation importance
importance = permutation_importance(
    model,
    X_explain,
    y_explain,
    scoring="neg_mean_absolute_error",
    n_repeats=5,
    random_state=42,
    n_jobs=-1
)


feature_importance = pd.DataFrame({
    "feature": feature_names,
    "importance_mean": importance.importances_mean,
    "importance_std": importance.importances_std
}).sort_values(
    "importance_mean",
    ascending=False
).reset_index(drop=True)


feature_importance["rank"] = (
    range(
        1,
        len(feature_importance) + 1
    )
)


feature_importance.to_csv(
    "models/feature_importance.csv",
    index=False
)

print(
    "Real permutation feature importance created successfully!"
)

feature_importance

Real permutation feature importance created successfully!

           feature  importance_mean  importance_std  rank
0   rolling_mean_7         0.335203        0.011986     1
1  rolling_mean_28         0.217523        0.004605     2
2     demand_lag_1         0.199380        0.012182     3
3      day_of_week         0.050144        0.002281     4
4       sell_price         0.005662        0.001619     5
5     demand_lag_7         0.002967        0.001297     6
6            month         0.000150        0.000057     7
7             year         0.000000        0.000000     8

In [192]:
from pathlib import Path

path = Path("api/app.py")
text = path.read_text(encoding="utf-8")

feature_api_code = r'''

# ============================================================
# BACKEND V6 — FEATURE IMPORTANCE API
# ============================================================

@app.get("/feature-importance")
def feature_importance():
    """
    Return permutation feature importance calculated
    on held-out demand forecasting observations.
    """

    importance_path = (
        Path(__file__).resolve().parent.parent
        / "models"
        / "feature_importance.csv"
    )

    if not importance_path.exists():
        raise HTTPException(
            status_code=404,
            detail="Feature importance file not found."
        )

    importance_df = pd.read_csv(
        importance_path
    )

    return {
        "method": "Permutation Importance",
        "scoring": "Negative Mean Absolute Error",
        "features": json.loads(
            importance_df.to_json(
                orient="records"
            )
        )
    }
'''

if '/feature-importance' not in text:

    text += feature_api_code

    path.write_text(
        text,
        encoding="utf-8"
    )

    print(
        "Feature Importance API added successfully!"
    )

else:

    print(
        "Feature Importance API already exists."
    )

Feature Importance API added successfully!

In [193]:
from pathlib import Path

path = Path("api/app.py")
text = path.read_text(encoding="utf-8")

if "import pandas as pd" not in text:

    text = "import pandas as pd\n" + text

    path.write_text(
        text,
        encoding="utf-8"
    )

    print("Pandas import added to FastAPI successfully!")

else:

    print("Pandas is already imported.")

Pandas import added to FastAPI successfully!

In [194]:
from pathlib import Path

path = Path("dashboard/pages/5_Model_Monitoring.py")
text = path.read_text(encoding="utf-8")

old = '''st.subheader("Model Explainability")

st.info(
    """
    Feature importance will be calculated using permutation importance
    on held-out observations. This avoids displaying unsupported or
    fabricated importance scores.
    """
)

st.caption(
    "AI Demand & Pricing Engine — Model Monitoring Layer"
)'''

new = '''st.subheader("Model Explainability")

@st.cache_data(ttl=300)
def load_feature_importance():

    response = requests.get(
        f"{API_URL}/feature-importance",
        timeout=10
    )

    response.raise_for_status()

    return response.json()


try:

    importance_payload = load_feature_importance()

    importance_df = pd.DataFrame(
        importance_payload["features"]
    ).sort_values(
        "rank"
    )

    st.caption(
        f"Method: {importance_payload['method']} · "
        f"Scoring: {importance_payload['scoring']}"
    )


    # -----------------------------------------
    # IMPORTANCE CHART
    # -----------------------------------------

    chart_df = (
        importance_df
        .sort_values(
            "importance_mean",
            ascending=True
        )
        .set_index("feature")
    )

    st.bar_chart(
        chart_df[
            ["importance_mean"]
        ]
    )


    # -----------------------------------------
    # RANKING TABLE
    # -----------------------------------------

    st.markdown(
        "#### Feature Ranking"
    )

    st.dataframe(
        importance_df[
            [
                "rank",
                "feature",
                "importance_mean",
                "importance_std"
            ]
        ],
        use_container_width=True,
        hide_index=True
    )


    # -----------------------------------------
    # INTERPRETATION
    # -----------------------------------------

    if not importance_df.empty:

        top_feature = importance_df.iloc[0]

        st.info(
            f"The most influential predictive feature is "
            f"**{top_feature['feature']}**. "
            "Recent demand and rolling-demand signals dominate "
            "the forecasting model's predictive performance."
        )


    st.warning(
        """
        Permutation importance measures predictive contribution,
        not causal impact. Correlated lag and rolling features may
        share predictive information.
        """
    )


except Exception as e:

    st.error(
        f"Unable to load feature importance: {e}"
    )


st.caption(
    "AI Demand & Pricing Engine — Model Monitoring Layer"
)'''

if old in text:

    text = text.replace(
        old,
        new
    )

    path.write_text(
        text,
        encoding="utf-8"
    )

    print(
        "Live explainability dashboard added successfully!"
    )

else:

    print(
        "Explainability placeholder not found or already updated."
    )

Live explainability dashboard added successfully!

In [195]:
from pathlib import Path

path = Path("tests/test_project.py")
text = path.read_text(encoding="utf-8")

monitoring_tests = r'''


def test_model_info_endpoint():

    response = client.get(
        "/model-info"
    )

    assert response.status_code == 200

    data = response.json()

    assert data["model_type"] == "HistGradientBoostingRegressor"
    assert data["version"] == "1.0.0"

    assert "evaluation" in data
    assert "baseline" in data
    assert "features" in data
    assert "governance" in data
    assert "computed_metrics" in data

    assert len(data["features"]) == 8

    assert data["evaluation"]["mae"] > 0
    assert data["evaluation"]["rmse"] > 0

    assert (
        data["computed_metrics"]
        ["mae_improvement_vs_baseline_pct"]
        > 0
    )


def test_feature_importance_endpoint():

    response = client.get(
        "/feature-importance"
    )

    assert response.status_code == 200

    data = response.json()

    assert data["method"] == "Permutation Importance"

    assert "features" in data
    assert len(data["features"]) == 8

    first = data["features"][0]

    assert "feature" in first
    assert "importance_mean" in first
    assert "importance_std" in first
    assert "rank" in first

    ranks = [
        feature["rank"]
        for feature in data["features"]
    ]

    assert sorted(ranks) == list(
        range(1, 9)
    )
'''

if "def test_model_info_endpoint(" not in text:

    text += monitoring_tests

    path.write_text(
        text,
        encoding="utf-8"
    )

    print("Monitoring and explainability tests added successfully!")

else:

    print("Monitoring tests already exist.")

Monitoring and explainability tests added successfully!

In [196]:
from pathlib import Path

requirements = """fastapi
uvicorn
streamlit
pandas
numpy
scikit-learn
joblib
requests
statsmodels
httpx
pytest
"""

Path("requirements.txt").write_text(
    requirements,
    encoding="utf-8"
)

print("Clean requirements.txt created successfully!")

Clean requirements.txt created successfully!

In [197]:
from pathlib import Path

gitignore = r"""
# Python
__pycache__/
*.py[cod]
*.pyo
*.pyd

# Jupyter
.ipynb_checkpoints/

# Pytest
.pytest_cache/

# Virtual environments
venv/
env/
.venv/

# Environment variables / secrets
.env
*.env

# IDE / OS
.vscode/
.idea/
.DS_Store
Thumbs.db

# Logs
*.log

# Large/raw datasets
data/raw/
data/*.zip

# Temporary files
*.tmp
*.bak

# Streamlit secrets
.streamlit/secrets.toml

# Full local dependency dump
requirements_full.txt
"""

Path(".gitignore").write_text(
    gitignore.strip() + "\n",
    encoding="utf-8"
)

print(".gitignore created successfully!")

.gitignore created successfully!

In [198]:
from pathlib import Path

ui_code = r'''
import streamlit as st


# ============================================================
# PRODUCT LABELS
# ============================================================

def friendly_product_name(item_id):
    """
    Convert technical M5 IDs into cleaner business-facing labels
    without inventing product information.
    """

    if not isinstance(item_id, str):
        return str(item_id)

    parts = item_id.split("_")

    if len(parts) >= 3:

        category = parts[0].title()
        family = parts[1]
        sku = parts[2]

        return f"{category} · SKU {family}-{sku}"

    return item_id


def product_label_with_id(item_id):
    return f"{friendly_product_name(item_id)}  ·  {item_id}"


# ============================================================
# GLOBAL PROFESSIONAL STYLING
# ============================================================

def apply_professional_style():

    st.markdown(
        """
        <style>

        /* Main application */
        .block-container {
            max-width: 1450px;
            padding-top: 2.2rem;
            padding-bottom: 4rem;
        }


        /* Main headings */
        h1 {
            font-size: 2.25rem !important;
            font-weight: 700 !important;
            letter-spacing: -0.035em !important;
        }

        h2 {
            font-size: 1.45rem !important;
            font-weight: 650 !important;
            letter-spacing: -0.02em !important;
            margin-top: 1.8rem !important;
        }

        h3 {
            font-size: 1.05rem !important;
            font-weight: 650 !important;
        }


        /* KPI cards */
        div[data-testid="stMetric"] {
            background: rgba(248, 250, 252, 0.72);
            border: 1px solid rgba(148, 163, 184, 0.24);
            padding: 1.15rem 1.25rem;
            border-radius: 14px;
            min-height: 122px;
        }

        div[data-testid="stMetricLabel"] {
            font-size: 0.78rem;
            font-weight: 600;
            letter-spacing: 0.025em;
            color: #64748b;
        }

        div[data-testid="stMetricValue"] {
            font-size: 2rem;
            font-weight: 650;
            letter-spacing: -0.035em;
        }


        /* Tables */
        div[data-testid="stDataFrame"] {
            border: 1px solid rgba(148, 163, 184, 0.22);
            border-radius: 12px;
            overflow: hidden;
        }


        /* Inputs */
        div[data-baseweb="select"] > div,
        div[data-baseweb="input"] > div {
            border-radius: 10px;
        }


        /* Buttons */
        div.stButton > button {
            border-radius: 10px;
            font-weight: 600;
            min-height: 44px;
        }


        /* Info / success / warning containers */
        div[data-testid="stAlert"] {
            border-radius: 12px;
        }


        /* Sidebar */
        section[data-testid="stSidebar"] {
            border-right: 1px solid rgba(148, 163, 184, 0.16);
        }

        </style>
        """,
        unsafe_allow_html=True
    )


# ============================================================
# SECTION HEADER
# ============================================================

def section_header(title, subtitle=None):

    st.markdown(f"## {title}")

    if subtitle:
        st.caption(subtitle)


# ============================================================
# BUSINESS MODEL NAMES
# ============================================================

def clean_model_name(model_name):

    mapping = {
        "HistGradientBoostingRegressor":
            "AI Demand Model",

        "Lag-1 Naive Forecast":
            "Baseline Forecast"
    }

    return mapping.get(
        model_name,
        model_name
    )
'''

Path("dashboard/ui.py").write_text(
    ui_code,
    encoding="utf-8"
)

print("Professional UI system created successfully!")

Professional UI system created successfully!

In [199]:
from pathlib import Path

path = Path("dashboard/pages/5_Model_Monitoring.py")

# Backup current working page
backup = Path("dashboard/pages/5_Model_Monitoring_backup.py")

if path.exists() and not backup.exists():
    backup.write_text(
        path.read_text(encoding="utf-8"),
        encoding="utf-8"
    )

new_page = r'''
import sys
from pathlib import Path

import pandas as pd
import requests
import streamlit as st

# ============================================================
# PROJECT IMPORTS
# ============================================================

BASE_DIR = Path(__file__).resolve().parents[2]

if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from dashboard.ui import (
    apply_professional_style,
    clean_model_name
)


# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="Model Intelligence",
    page_icon="◈",
    layout="wide"
)

apply_professional_style()

API_URL = "http://127.0.0.1:8001"


# ============================================================
# EXTRA PAGE STYLING
# ============================================================

st.markdown(
    """
    <style>

    .hero {
        padding: 1.1rem 0 1.8rem 0;
    }

    .eyebrow {
        font-size: 0.72rem;
        font-weight: 700;
        letter-spacing: 0.12em;
        text-transform: uppercase;
        color: #64748b;
        margin-bottom: 0.4rem;
    }

    .hero-title {
        font-size: 2.35rem;
        line-height: 1.05;
        font-weight: 750;
        letter-spacing: -0.045em;
        color: #0f172a;
    }

    .hero-subtitle {
        margin-top: 0.7rem;
        max-width: 850px;
        color: #64748b;
        font-size: 0.98rem;
        line-height: 1.55;
    }

    .status-row {
        display: flex;
        gap: 0.55rem;
        flex-wrap: wrap;
        margin-top: 1rem;
    }

    .status-chip {
        padding: 0.36rem 0.7rem;
        border-radius: 999px;
        font-size: 0.76rem;
        font-weight: 650;
        background: #f1f5f9;
        border: 1px solid #e2e8f0;
        color: #334155;
    }

    .status-chip.good {
        background: #ecfdf5;
        border-color: #bbf7d0;
        color: #166534;
    }

    .benchmark-card {
        background: #ffffff;
        border: 1px solid #e2e8f0;
        border-radius: 16px;
        padding: 1.2rem 1.3rem;
        margin-bottom: 0.85rem;
    }

    .benchmark-label {
        font-size: 0.74rem;
        color: #64748b;
        font-weight: 650;
        text-transform: uppercase;
        letter-spacing: 0.06em;
    }

    .benchmark-value {
        font-size: 1.7rem;
        font-weight: 720;
        letter-spacing: -0.035em;
        color: #0f172a;
        margin-top: 0.2rem;
    }

    .benchmark-sub {
        font-size: 0.77rem;
        color: #64748b;
        margin-top: 0.25rem;
    }

    .benchmark-win {
        color: #15803d;
        font-weight: 700;
    }

    .bar-bg {
        height: 9px;
        width: 100%;
        border-radius: 999px;
        background: #eef2f7;
        overflow: hidden;
        margin-top: 0.65rem;
    }

    .bar-ai {
        height: 100%;
        border-radius: 999px;
        background: #2563eb;
    }

    .bar-base {
        height: 100%;
        border-radius: 999px;
        background: #94a3b8;
    }

    .feature-row {
        display: grid;
        grid-template-columns: 185px 1fr 75px;
        gap: 14px;
        align-items: center;
        margin: 0.72rem 0;
    }

    .feature-name {
        font-size: 0.85rem;
        font-weight: 600;
        color: #334155;
    }

    .feature-value {
        font-size: 0.78rem;
        text-align: right;
        font-variant-numeric: tabular-nums;
        color: #475569;
    }

    .feature-bg {
        height: 11px;
        border-radius: 999px;
        background: #eef2f7;
        overflow: hidden;
    }

    .feature-fill {
        height: 100%;
        border-radius: 999px;
        background: #2563eb;
    }

    .governance-card {
        border: 1px solid #dcfce7;
        background: #f0fdf4;
        border-radius: 13px;
        padding: 0.85rem 1rem;
        min-height: 92px;
    }

    .governance-title {
        font-size: 0.83rem;
        font-weight: 700;
        color: #166534;
    }

    .governance-copy {
        font-size: 0.73rem;
        color: #4b5563;
        margin-top: 0.25rem;
    }

    .interpretation-box {
        background: #f8fafc;
        border: 1px solid #e2e8f0;
        border-radius: 14px;
        padding: 1.1rem 1.2rem;
        line-height: 1.55;
    }

    </style>
    """,
    unsafe_allow_html=True
)


# ============================================================
# API LOADERS
# ============================================================

@st.cache_data(ttl=300)
def load_model_info():

    response = requests.get(
        f"{API_URL}/model-info",
        timeout=10
    )

    response.raise_for_status()

    return response.json()


@st.cache_data(ttl=300)
def load_feature_importance():

    response = requests.get(
        f"{API_URL}/feature-importance",
        timeout=10
    )

    response.raise_for_status()

    return response.json()


try:

    model = load_model_info()
    importance_payload = load_feature_importance()

except requests.exceptions.ConnectionError:

    st.error(
        "FastAPI backend is offline. "
        "Start the backend on port 8001."
    )

    st.stop()

except Exception as e:

    st.error(
        f"Unable to load model intelligence: {e}"
    )

    st.stop()


evaluation = model["evaluation"]
baseline = model["baseline"]

improvement_mae = float(
    model["computed_metrics"][
        "mae_improvement_vs_baseline_pct"
    ]
)

rmse_improvement = (
    (baseline["rmse"] - evaluation["rmse"])
    / baseline["rmse"]
    * 100
)

r2_gain = (
    evaluation["r2"]
    -
    baseline["r2"]
)


# ============================================================
# HERO
# ============================================================

business_model_name = clean_model_name(
    model["model_type"]
)

st.markdown(
    f"""
    <div class="hero">

        <div class="eyebrow">
            Model intelligence
        </div>

        <div class="hero-title">
            Forecast Performance & Explainability
        </div>

        <div class="hero-subtitle">
            Validation, benchmarking and predictive explainability
            for the demand forecasting engine powering automated
            pricing recommendations.
        </div>

        <div class="status-row">

            <span class="status-chip good">
                ● {model["status"]}
            </span>

            <span class="status-chip">
                {business_model_name}
            </span>

            <span class="status-chip">
                v{model["version"]}
            </span>

            <span class="status-chip">
                28-day chronological holdout
            </span>

        </div>

    </div>
    """,
    unsafe_allow_html=True
)


# ============================================================
# EXECUTIVE KPI CARDS
# ============================================================

st.markdown("## Executive Model KPIs")

k1, k2, k3, k4 = st.columns(4)

k1.metric(
    "Mean Absolute Error",
    f"{evaluation['mae']:.3f}",
    delta=f"{improvement_mae:.1f}% lower vs baseline",
    delta_color="normal"
)

k2.metric(
    "Root Mean Squared Error",
    f"{evaluation['rmse']:.3f}",
    delta=f"{rmse_improvement:.1f}% lower vs baseline",
    delta_color="normal"
)

k3.metric(
    "R² Score",
    f"{evaluation['r2']:.3f}",
    delta=f"+{r2_gain:.3f} vs baseline"
)

k4.metric(
    "Active Features",
    len(model["features"]),
    delta="Production feature set",
    delta_color="off"
)


# ============================================================
# PROFESSIONAL BENCHMARK
# ============================================================

st.divider()

st.markdown("## Forecast Benchmark")

st.caption(
    "AI Demand Model versus a lag-1 naive forecasting baseline."
)

ai_name = clean_model_name(
    model["model_type"]
)

baseline_name = clean_model_name(
    baseline["model"]
)


# MAE
mae_max = max(
    baseline["mae"],
    evaluation["mae"]
)

ai_mae_width = (
    evaluation["mae"]
    / mae_max
    * 100
)

base_mae_width = (
    baseline["mae"]
    / mae_max
    * 100
)

left, right = st.columns(2)

with left:

    st.markdown(
        f"""
        <div class="benchmark-card">

            <div class="benchmark-label">
                MAE · Lower is better
            </div>

            <div class="benchmark-value">
                {evaluation["mae"]:.3f}
            </div>

            <div class="benchmark-sub">
                {ai_name}
                ·
                <span class="benchmark-win">
                    {improvement_mae:.1f}% lower error
                </span>
            </div>

            <div class="bar-bg">
                <div class="bar-ai"
                     style="width:{ai_mae_width:.1f}%;">
                </div>
            </div>

            <div class="benchmark-sub">
                Baseline {baseline["mae"]:.3f}
            </div>

            <div class="bar-bg">
                <div class="bar-base"
                     style="width:{base_mae_width:.1f}%;">
                </div>
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


with right:

    rmse_max = max(
        baseline["rmse"],
        evaluation["rmse"]
    )

    ai_rmse_width = (
        evaluation["rmse"]
        / rmse_max
        * 100
    )

    base_rmse_width = (
        baseline["rmse"]
        / rmse_max
        * 100
    )

    st.markdown(
        f"""
        <div class="benchmark-card">

            <div class="benchmark-label">
                RMSE · Lower is better
            </div>

            <div class="benchmark-value">
                {evaluation["rmse"]:.3f}
            </div>

            <div class="benchmark-sub">
                {ai_name}
                ·
                <span class="benchmark-win">
                    {rmse_improvement:.1f}% lower error
                </span>
            </div>

            <div class="bar-bg">
                <div class="bar-ai"
                     style="width:{ai_rmse_width:.1f}%;">
                </div>
            </div>

            <div class="benchmark-sub">
                Baseline {baseline["rmse"]:.3f}
            </div>

            <div class="bar-bg">
                <div class="bar-base"
                     style="width:{base_rmse_width:.1f}%;">
                </div>
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


# R2 benchmark

r2_left, r2_right = st.columns([1, 1])

with r2_left:

    st.markdown(
        f"""
        <div class="benchmark-card">

            <div class="benchmark-label">
                R² · Higher is better
            </div>

            <div class="benchmark-value">
                {evaluation["r2"]:.3f}
            </div>

            <div class="benchmark-sub">
                Baseline: {baseline["r2"]:.3f}
            </div>

            <div class="benchmark-sub benchmark-win">
                +{r2_gain:.3f} absolute improvement
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


with r2_right:

    st.markdown(
        f"""
        <div class="interpretation-box">

        <b>Benchmark conclusion</b><br><br>

        The AI Demand Model reduces average forecast error
        by <b>{improvement_mae:.1f}%</b> against the lag-1 baseline
        and improves R² from <b>{baseline["r2"]:.3f}</b>
        to <b>{evaluation["r2"]:.3f}</b>.

        </div>
        """,
        unsafe_allow_html=True
    )


# ============================================================
# TECHNICAL BENCHMARK TABLE
# ============================================================

with st.expander(
    "Technical benchmark details"
):

    benchmark_df = pd.DataFrame(
        {
            "Model": [
                ai_name,
                baseline_name
            ],

            "Technical Model": [
                model["model_type"],
                baseline["model"]
            ],

            "MAE": [
                evaluation["mae"],
                baseline["mae"]
            ],

            "RMSE": [
                evaluation["rmse"],
                baseline["rmse"]
            ],

            "R²": [
                evaluation["r2"],
                baseline["r2"]
            ]
        }
    )

    st.dataframe(
        benchmark_df,
        use_container_width=True,
        hide_index=True
    )


# ============================================================
# EXPLAINABILITY
# ============================================================

st.divider()

st.markdown("## Predictive Explainability")

st.caption(
    "Permutation importance measured on held-out observations "
    "using negative mean absolute error."
)

importance_df = pd.DataFrame(
    importance_payload["features"]
).sort_values(
    "rank"
)

max_importance = max(
    importance_df["importance_mean"].max(),
    0.000001
)

for _, row in importance_df.iterrows():

    value = max(
        float(row["importance_mean"]),
        0
    )

    width = (
        value
        / max_importance
        * 100
    )

    st.markdown(
        f"""
        <div class="feature-row">

            <div class="feature-name">
                #{int(row["rank"])}
                &nbsp;
                {row["feature"]}
            </div>

            <div class="feature-bg">
                <div
                    class="feature-fill"
                    style="width:{width:.1f}%;">
                </div>
            </div>

            <div class="feature-value">
                {row["importance_mean"]:.4f}
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


top_feature = importance_df.iloc[0]

st.markdown(
    f"""
    <div class="interpretation-box">

    <b>What drives the forecast?</b><br><br>

    <b>{top_feature["feature"]}</b> is currently the strongest
    predictive feature. Overall, recent demand history and rolling
    demand signals contribute most strongly to forecasting accuracy.

    </div>
    """,
    unsafe_allow_html=True
)


with st.expander(
    "Explainability methodology"
):

    st.write(
        """
        Permutation importance measures how much model performance
        deteriorates when a feature is randomly shuffled.

        A larger value means the model relies more heavily on that
        feature for predictive accuracy.
        """
    )

    st.warning(
        """
        Predictive importance is not causal importance.
        Correlated lag and rolling-demand variables can share
        predictive information.
        """
    )


# ============================================================
# FEATURE INVENTORY
# ============================================================

st.divider()

st.markdown("## Production Feature Set")

feature_groups = {
    "Demand History": [
        "demand_lag_1",
        "demand_lag_7",
        "rolling_mean_7",
        "rolling_mean_28"
    ],

    "Pricing": [
        "sell_price"
    ],

    "Calendar": [
        "day_of_week",
        "month",
        "year"
    ]
}

cols = st.columns(3)

for col, (group, features) in zip(
    cols,
    feature_groups.items()
):

    with col:

        st.markdown(
            f"### {group}"
        )

        for feature in features:

            if feature in model["features"]:

                st.write(
                    f"✓ {feature}"
                )


# ============================================================
# GOVERNANCE
# ============================================================

st.divider()

st.markdown("## Model Governance")

governance_copy = {
    "pricing_guardrails":
        (
            "Pricing Guardrails",
            "Limits automated price movement."
        ),

    "human_review":
        (
            "Human Review",
            "Routes uncertain decisions for validation."
        ),

    "elasticity_validation":
        (
            "Elasticity Validation",
            "Checks economic coherence before automation."
        ),

    "profit_guardrail":
        (
            "Profit Protection",
            "Protects against uneconomic price decisions."
        )
}

gcols = st.columns(4)

for col, (key, content) in zip(
    gcols,
    governance_copy.items()
):

    title, copy = content

    enabled = model[
        "governance"
    ].get(
        key,
        False
    )

    with col:

        if enabled:

            st.markdown(
                f"""
                <div class="governance-card">

                    <div class="governance-title">
                        ✓ {title}
                    </div>

                    <div class="governance-copy">
                        {copy}
                    </div>

                </div>
                """,
                unsafe_allow_html=True
            )

        else:

            st.error(
                title
            )


# ============================================================
# VALIDATION / LIMITATIONS
# ============================================================

st.divider()

st.markdown("## Validation Framework")

v1, v2 = st.columns(2)

with v1:

    st.markdown(
        f"""
        <div class="interpretation-box">

        <b>Evaluation design</b><br><br>

        {evaluation["test_strategy"]}.<br><br>

        A chronological holdout is used instead of a random split
        to reduce temporal leakage and better reflect a real
        forecasting workflow.

        </div>
        """,
        unsafe_allow_html=True
    )


with v2:

    st.warning(
        """
        The current evaluation uses lag-based one-step-ahead
        predictions.

        Results should not be interpreted as a fully recursive
        28-day forecasting experiment.
        """
    )


st.caption(
    "AI Demand & Pricing Engine · Model Intelligence Layer"
)
'''

path.write_text(
    new_page,
    encoding="utf-8"
)

print("Model Monitoring redesigned successfully!")
print("Backup:", backup)

Model Monitoring redesigned successfully!
Backup: dashboard\pages\5_Model_Monitoring_backup.py

In [200]:
from pathlib import Path
import re
import shutil

# ============================================================
# 1. FIX HTML RENDERING
# ============================================================

page = Path("dashboard/pages/5_Model_Monitoring.py")
text = page.read_text(encoding="utf-8")

# Convert HTML markdown blocks to Streamlit's HTML renderer
pattern = re.compile(
    r'st\.markdown\(\s*(f?""".*?""")\s*,\s*unsafe_allow_html=True\s*\)',
    re.DOTALL
)

text, replacements = pattern.subn(
    r"st.html(\1)",
    text
)

page.write_text(
    text,
    encoding="utf-8"
)

print("HTML blocks fixed:", replacements)


# ============================================================
# 2. REMOVE BACKUP FROM STREAMLIT SIDEBAR
# ============================================================

old_backup = Path(
    "dashboard/pages/5_Model_Monitoring_backup.py"
)

backup_folder = Path(
    "dashboard/backups"
)

backup_folder.mkdir(
    parents=True,
    exist_ok=True
)

new_backup = (
    backup_folder
    / "5_Model_Monitoring_backup.py"
)

if old_backup.exists():

    shutil.move(
        str(old_backup),
        str(new_backup)
    )

    print("Backup moved outside Streamlit pages.")

else:

    print("Backup already moved.")


print("Model Monitoring visual fix completed!")

HTML blocks fixed: 10
Backup moved outside Streamlit pages.
Model Monitoring visual fix completed!

In [201]:
from pathlib import Path
import shutil

page = Path(
    "dashboard/pages/4_Portfolio_Opportunities.py"
)

# Backup outside Streamlit pages
backup_dir = Path("dashboard/backups")
backup_dir.mkdir(
    parents=True,
    exist_ok=True
)

backup = (
    backup_dir
    / "4_Portfolio_Opportunities_backup.py"
)

if page.exists() and not backup.exists():
    shutil.copy(
        page,
        backup
    )


new_page = r'''
import sys
from pathlib import Path

import altair as alt
import pandas as pd
import requests
import streamlit as st


# ============================================================
# PROJECT IMPORTS
# ============================================================

BASE_DIR = Path(__file__).resolve().parents[2]

if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from dashboard.ui import (
    apply_professional_style,
    friendly_product_name
)


# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="Portfolio Opportunities",
    page_icon="◈",
    layout="wide"
)

apply_professional_style()

API_URL = "http://127.0.0.1:8001"


# ============================================================
# PAGE-SPECIFIC STYLE
# ============================================================

st.html(
    """
    <style>

    .portfolio-hero {
        padding: 0.8rem 0 1.6rem 0;
    }

    .eyebrow {
        font-size: 0.72rem;
        font-weight: 700;
        letter-spacing: 0.12em;
        text-transform: uppercase;
        color: #64748b;
        margin-bottom: 0.4rem;
    }

    .hero-title {
        font-size: 2.35rem;
        font-weight: 750;
        letter-spacing: -0.045em;
        color: #0f172a;
        line-height: 1.08;
    }

    .hero-copy {
        max-width: 850px;
        margin-top: 0.7rem;
        color: #64748b;
        line-height: 1.55;
    }

    .opportunity-card {
        background: #ffffff;
        border: 1px solid #e2e8f0;
        border-radius: 16px;
        padding: 1.15rem 1.25rem;
        min-height: 140px;
    }

    .card-label {
        font-size: 0.72rem;
        font-weight: 700;
        letter-spacing: 0.06em;
        text-transform: uppercase;
        color: #64748b;
    }

    .card-value {
        font-size: 2rem;
        font-weight: 730;
        letter-spacing: -0.04em;
        color: #0f172a;
        margin-top: 0.25rem;
    }

    .card-sub {
        font-size: 0.78rem;
        color: #64748b;
        margin-top: 0.35rem;
    }

    .positive {
        color: #15803d;
        font-weight: 700;
    }

    .action-increase {
        display: inline-block;
        background: #ecfdf5;
        color: #166534;
        border: 1px solid #bbf7d0;
        border-radius: 999px;
        padding: 0.25rem 0.55rem;
        font-size: 0.72rem;
        font-weight: 700;
    }

    .action-decrease {
        display: inline-block;
        background: #fff7ed;
        color: #9a3412;
        border: 1px solid #fed7aa;
        border-radius: 999px;
        padding: 0.25rem 0.55rem;
        font-size: 0.72rem;
        font-weight: 700;
    }

    .insight-box {
        background: #f8fafc;
        border: 1px solid #e2e8f0;
        border-radius: 14px;
        padding: 1.1rem 1.2rem;
        line-height: 1.55;
    }

    </style>
    """
)


# ============================================================
# API
# ============================================================

@st.cache_data(ttl=300)
def load_portfolio(
    top_n=20,
    max_change_pct=0.10
):

    response = requests.get(
        f"{API_URL}/portfolio-opportunities",
        params={
            "top_n": top_n,
            "max_change_pct": max_change_pct
        },
        timeout=90
    )

    response.raise_for_status()

    return response.json()


try:

    payload = load_portfolio(
        top_n=20,
        max_change_pct=0.10
    )

except requests.exceptions.ConnectionError:

    st.error(
        "FastAPI backend is offline. "
        "Start the backend on port 8001."
    )

    st.stop()

except Exception as e:

    st.error(
        f"Unable to load portfolio opportunities: {e}"
    )

    st.stop()


df = pd.DataFrame(
    payload["opportunities"]
)

summary = payload["summary"]


if df.empty:

    st.warning(
        "No eligible pricing opportunities were returned."
    )

    st.stop()


# ============================================================
# CLEAN BUSINESS LABELS
# ============================================================

df["product"] = (
    df["item_id"]
    .apply(friendly_product_name)
)

df["action"] = df.apply(
    lambda row:
        "Increase"
        if row["recommended_price"]
        > row["current_price"]
        else "Decrease"
        if row["recommended_price"]
        < row["current_price"]
        else "Hold",
    axis=1
)


# ============================================================
# HERO
# ============================================================

st.html(
    """
    <div class="portfolio-hero">

        <div class="eyebrow">
            Portfolio intelligence
        </div>

        <div class="hero-title">
            Pricing Opportunity Radar
        </div>

        <div class="hero-copy">
            Portfolio-level prioritization of automated pricing
            opportunities using demand forecasts, elasticity estimates
            and commercial pricing guardrails.
        </div>

    </div>
    """
)


# ============================================================
# FILTERS
# ============================================================

st.markdown("## Opportunity Filters")

f1, f2, f3 = st.columns(
    [1.2, 1, 1]
)

with f1:

    classifications = (
        ["All"]
        +
        sorted(
            df["classification"]
            .dropna()
            .unique()
            .tolist()
        )
    )

    classification_filter = st.selectbox(
        "Elasticity Segment",
        classifications
    )


with f2:

    min_uplift = st.slider(
        "Minimum Revenue Uplift",
        min_value=0.0,
        max_value=float(
            max(
                20.0,
                round(
                    df[
                        "expected_revenue_uplift_pct"
                    ].max(),
                    1
                )
            )
        ),
        value=0.0,
        step=0.5,
        format="%.1f%%"
    )


with f3:

    top_n = st.slider(
        "Show Top Opportunities",
        min_value=5,
        max_value=len(df),
        value=min(
            10,
            len(df)
        )
    )


filtered = df.copy()

if classification_filter != "All":

    filtered = filtered[
        filtered["classification"]
        == classification_filter
    ]


filtered = filtered[
    filtered[
        "expected_revenue_uplift_pct"
    ] >= min_uplift
]


filtered = (
    filtered
    .sort_values(
        "expected_revenue_gain",
        ascending=False
    )
    .head(top_n)
    .copy()
)


# ============================================================
# EXECUTIVE KPIs
# ============================================================

st.divider()

st.markdown("## Executive Portfolio KPIs")

total_gain = (
    filtered[
        "expected_revenue_gain"
    ].sum()
    if not filtered.empty
    else 0
)

average_uplift = (
    filtered[
        "expected_revenue_uplift_pct"
    ].mean()
    if not filtered.empty
    else 0
)

largest_gain = (
    filtered[
        "expected_revenue_gain"
    ].max()
    if not filtered.empty
    else 0
)

increase_count = int(
    (
        filtered["action"]
        == "Increase"
    ).sum()
)

decrease_count = int(
    (
        filtered["action"]
        == "Decrease"
    ).sum()
)


k1, k2, k3, k4 = st.columns(4)


with k1:

    st.html(
        f"""
        <div class="opportunity-card">

            <div class="card-label">
                Priority Opportunities
            </div>

            <div class="card-value">
                {len(filtered)}
            </div>

            <div class="card-sub">
                Highest-ranked eligible SKUs
            </div>

        </div>
        """
    )


with k2:

    st.html(
        f"""
        <div class="opportunity-card">

            <div class="card-label">
                Expected Revenue Gain
            </div>

            <div class="card-value">
                {total_gain:.2f}
            </div>

            <div class="card-sub positive">
                Portfolio opportunity value
            </div>

        </div>
        """
    )


with k3:

    st.html(
        f"""
        <div class="opportunity-card">

            <div class="card-label">
                Average Revenue Uplift
            </div>

            <div class="card-value">
                {average_uplift:.2f}%
            </div>

            <div class="card-sub">
                Across displayed opportunities
            </div>

        </div>
        """
    )


with k4:

    st.html(
        f"""
        <div class="opportunity-card">

            <div class="card-label">
                Largest Single Gain
            </div>

            <div class="card-value">
                {largest_gain:.2f}
            </div>

            <div class="card-sub">
                Best individual opportunity
            </div>

        </div>
        """
    )


# ============================================================
# TOP OPPORTUNITY
# ============================================================

if not filtered.empty:

    best = filtered.iloc[0]

    action = best["action"]

    action_html = (
        '<span class="action-increase">↑ Increase</span>'
        if action == "Increase"
        else
        '<span class="action-decrease">↓ Decrease</span>'
        if action == "Decrease"
        else
        "Hold"
    )


    st.divider()

    st.markdown(
        "## Highest-Priority Recommendation"
    )

    st.html(
        f"""
        <div class="insight-box">

            <b>{best["product"]}</b>
            &nbsp;&nbsp;
            {action_html}

            <br><br>

            Current price:
            <b>{best["current_price"]:.2f}</b>

            &nbsp;→&nbsp;

            Recommended:
            <b>{best["recommended_price"]:.2f}</b>

            <br><br>

            Estimated revenue uplift:
            <b>{best["expected_revenue_uplift_pct"]:.2f}%</b>

            &nbsp;·&nbsp;

            Expected revenue gain:
            <b>{best["expected_revenue_gain"]:.2f}</b>

            &nbsp;·&nbsp;

            Elasticity:
            <b>{best["elasticity"]:.3f}</b>

        </div>
        """
    )


# ============================================================
# OPPORTUNITY RANKING
# ============================================================

st.divider()

st.markdown(
    "## Opportunity Ranking"
)

st.caption(
    "Expected revenue gain by prioritized SKU."
)


ranking_chart = (
    alt.Chart(
        filtered
    )
    .mark_bar(
        cornerRadiusEnd=5
    )
    .encode(
        y=alt.Y(
            "product:N",
            sort="-x",
            title=None
        ),

        x=alt.X(
            "expected_revenue_gain:Q",
            title="Expected revenue gain"
        ),

        tooltip=[
            alt.Tooltip(
                "product:N",
                title="Product"
            ),

            alt.Tooltip(
                "item_id:N",
                title="Technical ID"
            ),

            alt.Tooltip(
                "current_price:Q",
                title="Current Price",
                format=".2f"
            ),

            alt.Tooltip(
                "recommended_price:Q",
                title="Recommended Price",
                format=".2f"
            ),

            alt.Tooltip(
                "expected_revenue_gain:Q",
                title="Revenue Gain",
                format=".2f"
            ),

            alt.Tooltip(
                "expected_revenue_uplift_pct:Q",
                title="Uplift",
                format=".2f"
            )
        ]
    )
    .properties(
        height=max(
            280,
            len(filtered) * 36
        )
    )
)

st.altair_chart(
    ranking_chart,
    use_container_width=True
)


# ============================================================
# REVENUE UPLIFT + PRICE CHANGE
# ============================================================

left, right = st.columns(2)


with left:

    st.markdown(
        "### Revenue Uplift"
    )

    uplift_chart = (
        alt.Chart(
            filtered
        )
        .mark_bar(
            cornerRadiusEnd=4
        )
        .encode(
            x=alt.X(
                "product:N",
                sort="-y",
                title=None
            ),

            y=alt.Y(
                "expected_revenue_uplift_pct:Q",
                title="Expected uplift (%)"
            ),

            tooltip=[
                "product:N",

                alt.Tooltip(
                    "expected_revenue_uplift_pct:Q",
                    title="Uplift",
                    format=".2f"
                )
            ]
        )
        .properties(
            height=330
        )
    )

    st.altair_chart(
        uplift_chart,
        use_container_width=True
    )


with right:

    st.markdown(
        "### Recommended Price Change"
    )

    change_chart = (
        alt.Chart(
            filtered
        )
        .mark_bar(
            cornerRadiusEnd=4
        )
        .encode(
            x=alt.X(
                "product:N",
                sort="-y",
                title=None
            ),

            y=alt.Y(
                "price_change_pct:Q",
                title="Price change (%)"
            ),

            tooltip=[
                "product:N",

                alt.Tooltip(
                    "price_change_pct:Q",
                    title="Price Change",
                    format=".2f"
                )
            ]
        )
        .properties(
            height=330
        )
    )

    st.altair_chart(
        change_chart,
        use_container_width=True
    )


# ============================================================
# CURRENT VS RECOMMENDED
# ============================================================

st.divider()

st.markdown(
    "## Current vs Recommended Price"
)


price_long = filtered[
    [
        "product",
        "current_price",
        "recommended_price"
    ]
].melt(
    id_vars="product",
    var_name="price_type",
    value_name="price"
)


price_long["price_type"] = (
    price_long["price_type"]
    .replace(
        {
            "current_price":
                "Current Price",

            "recommended_price":
                "Recommended Price"
        }
    )
)


price_chart = (
    alt.Chart(
        price_long
    )
    .mark_bar()
    .encode(
        x=alt.X(
            "product:N",
            title=None
        ),

        y=alt.Y(
            "price:Q",
            title="Price"
        ),

        xOffset="price_type:N",

        color=alt.Color(
            "price_type:N",
            title=None
        ),

        tooltip=[
            "product:N",
            "price_type:N",

            alt.Tooltip(
                "price:Q",
                format=".2f"
            )
        ]
    )
    .properties(
        height=380
    )
)

st.altair_chart(
    price_chart,
    use_container_width=True
)


# ============================================================
# EXECUTIVE TABLE
# ============================================================

st.divider()

st.markdown(
    "## Decision Table"
)


table = filtered[
    [
        "rank",
        "product",
        "item_id",
        "classification",
        "current_price",
        "recommended_price",
        "price_change_pct",
        "expected_revenue_gain",
        "expected_revenue_uplift_pct"
    ]
].copy()


table.columns = [
    "Rank",
    "Product",
    "Technical ID",
    "Elasticity Segment",
    "Current Price",
    "Recommended Price",
    "Price Change %",
    "Revenue Gain",
    "Revenue Uplift %"
]


st.dataframe(
    table,
    use_container_width=True,
    hide_index=True,

    column_config={

        "Current Price":
            st.column_config.NumberColumn(
                format="%.2f"
            ),

        "Recommended Price":
            st.column_config.NumberColumn(
                format="%.2f"
            ),

        "Price Change %":
            st.column_config.NumberColumn(
                format="%.2f%%"
            ),

        "Revenue Gain":
            st.column_config.NumberColumn(
                format="%.2f"
            ),

        "Revenue Uplift %":
            st.column_config.NumberColumn(
                format="%.2f%%"
            )
    }
)


# ============================================================
# PORTFOLIO INTERPRETATION
# ============================================================

st.divider()

st.markdown(
    "## Executive Interpretation"
)


if not filtered.empty:

    st.html(
        f"""
        <div class="insight-box">

        The current opportunity set contains
        <b>{len(filtered)}</b> priority SKUs.

        <br><br>

        <b>{increase_count}</b> recommendations imply a price increase
        and <b>{decrease_count}</b> imply a price decrease.

        The strongest identified opportunity is
        <b>{best["product"]}</b>, with an estimated revenue uplift of
        <b>{best["expected_revenue_uplift_pct"]:.2f}%</b>.

        </div>
        """
    )


st.caption(
    """
    Portfolio ranking reflects modeled revenue opportunity under
    pricing guardrails. Estimates are decision-support outputs,
    not guaranteed realized commercial outcomes.
    """
)
'''

page.write_text(
    new_page,
    encoding="utf-8"
)

print(
    "Portfolio Opportunities redesigned successfully!"
)

print(
    "Backup:",
    backup
)

Portfolio Opportunities redesigned successfully!
Backup: dashboard\backups\4_Portfolio_Opportunities_backup.py

In [202]:
from pathlib import Path
import shutil

page = Path(
    "dashboard/pages/3_Profit_Optimization.py"
)

backup_dir = Path("dashboard/backups")
backup_dir.mkdir(
    parents=True,
    exist_ok=True
)

backup = (
    backup_dir
    / "3_Profit_Optimization_backup.py"
)

if page.exists() and not backup.exists():
    shutil.copy(page, backup)


new_page = r'''
import sys
from pathlib import Path

import altair as alt
import pandas as pd
import requests
import streamlit as st


BASE_DIR = Path(__file__).resolve().parents[2]

if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))


from dashboard.ui import (
    apply_professional_style,
    friendly_product_name
)


st.set_page_config(
    page_title="Pricing Decision Center",
    page_icon="◈",
    layout="wide"
)

apply_professional_style()

API_URL = "http://127.0.0.1:8001"


# ============================================================
# VISUAL STYLE
# ============================================================

st.html(
    """
    <style>

    .decision-hero {
        padding: 0.7rem 0 1.5rem 0;
    }

    .eyebrow {
        font-size: .72rem;
        font-weight: 700;
        letter-spacing: .12em;
        text-transform: uppercase;
        color: #64748b;
    }

    .decision-title {
        font-size: 2.4rem;
        font-weight: 750;
        letter-spacing: -.045em;
        color: #0f172a;
        margin-top: .35rem;
    }

    .decision-copy {
        color: #64748b;
        margin-top: .65rem;
        max-width: 850px;
        line-height: 1.55;
    }

    .decision-panel {
        background: #f8fafc;
        border: 1px solid #e2e8f0;
        border-radius: 16px;
        padding: 1.2rem 1.3rem;
    }

    .decision-product {
        font-size: 1.2rem;
        font-weight: 720;
        color: #0f172a;
    }

    .decision-summary {
        margin-top: .75rem;
        color: #475569;
        line-height: 1.6;
    }

    .status-good {
        display: inline-block;
        padding: .28rem .62rem;
        border-radius: 999px;
        background: #ecfdf5;
        border: 1px solid #bbf7d0;
        color: #166534;
        font-size: .73rem;
        font-weight: 700;
    }

    .governance-card {
        padding: .85rem 1rem;
        border-radius: 12px;
        background: #f0fdf4;
        border: 1px solid #dcfce7;
        color: #166534;
        font-size: .8rem;
        font-weight: 650;
        min-height: 62px;
    }

    </style>
    """
)


# ============================================================
# PRODUCT LIST
# ============================================================

@st.cache_data
def load_products():

    path = (
        BASE_DIR
        / "data"
        / "master_product_elasticities.csv"
    )

    df = pd.read_csv(path)

    return sorted(
        df["item_id"]
        .dropna()
        .unique()
        .tolist()
    )


products = load_products()


# ============================================================
# HERO
# ============================================================

st.html(
    """
    <div class="decision-hero">

        <div class="eyebrow">
            Decision intelligence
        </div>

        <div class="decision-title">
            Pricing Decision Center
        </div>

        <div class="decision-copy">
            AI-assisted SKU pricing combining demand forecasting,
            elasticity, revenue optimization, unit economics and
            commercial governance.
        </div>

    </div>
    """
)


# ============================================================
# PRODUCT + BUSINESS INPUTS
# ============================================================

st.markdown("## Decision Inputs")

c1, c2, c3 = st.columns(
    [1.6, 1, 1]
)


with c1:

    selected_product = st.selectbox(
        "Product",
        products,
        format_func=friendly_product_name,
        index=(
            products.index("HOBBIES_1_295")
            if "HOBBIES_1_295" in products
            else 0
        )
    )


with c2:

    unit_cost = st.number_input(
        "Unit Cost",
        min_value=0.01,
        value=0.30,
        step=0.01,
        format="%.2f"
    )


with c3:

    guardrail_pct = st.slider(
        "Maximum Price Change",
        min_value=1,
        max_value=25,
        value=10,
        step=1,
        format="%d%%"
    )


run = st.button(
    "Run AI Pricing Decision",
    type="primary",
    use_container_width=True
)


# ============================================================
# API CALL
# ============================================================

if run:

    try:

        response = requests.post(
            f"{API_URL}/recommend-profit-auto",
            json={
                "item_id":
                    selected_product,

                "unit_cost":
                    unit_cost,

                "max_change_pct":
                    guardrail_pct / 100
            },
            timeout=60
        )

        response.raise_for_status()

        st.session_state[
            "pricing_result"
        ] = response.json()


    except requests.exceptions.ConnectionError:

        st.error(
            "FastAPI backend is offline."
        )


    except Exception as e:

        st.error(
            f"Pricing engine error: {e}"
        )


# ============================================================
# RESULTS
# ============================================================

result = st.session_state.get(
    "pricing_result"
)


if result:

    product_label = friendly_product_name(
        result["item_id"]
    )

    recommended_price = result.get(
        "profit_maximizing_price",
        result.get(
            "recommended_price"
        )
    )

    current_price = result[
        "current_price"
    ]

    profit_uplift = result.get(
        "expected_profit_uplift_pct",
        0
    )

    action = (
        "Increase"
        if recommended_price > current_price
        else
        "Decrease"
        if recommended_price < current_price
        else
        "Hold"
    )


    # ========================================================
    # EXECUTIVE DECISION
    # ========================================================

    st.divider()

    st.markdown(
        "## Executive Recommendation"
    )

    summary_text = result.get(
        "decision_summary",
        (
            f"{action} the price from "
            f"{current_price:.2f} to "
            f"{recommended_price:.2f}."
        )
    )


    st.html(
        f"""
        <div class="decision-panel">

            <div class="decision-product">
                {product_label}
                &nbsp;
                <span class="status-good">
                    ✓ {result["status"].replace("_", " ")}
                </span>
            </div>

            <div class="decision-summary">
                {summary_text}
            </div>

        </div>
        """
    )


    # ========================================================
    # CORE KPIs
    # ========================================================

    st.markdown("### Decision KPIs")

    k1, k2, k3, k4 = st.columns(4)

    k1.metric(
        "Current Price",
        f"{current_price:.2f}"
    )

    k2.metric(
        "Recommended Price",
        f"{recommended_price:.2f}",
        delta=(
            f"{((recommended_price/current_price)-1)*100:+.1f}%"
        )
    )

    k3.metric(
        "Expected Profit Uplift",
        f"{profit_uplift:.2f}%"
    )

    k4.metric(
        "Forecast Demand",
        f"{result['forecast_demand']:.2f}"
    )


    k5, k6, k7, k8 = st.columns(4)

    k5.metric(
        "Unit Cost",
        f"{result['unit_cost']:.2f}"
    )

    k6.metric(
        "Elasticity",
        f"{result['elasticity']:.3f}"
    )

    k7.metric(
        "Elasticity Segment",
        result["classification"]
    )

    k8.metric(
        "Guardrail",
        f"±{result['guardrail_max_change_pct']:.0f}%"
    )


    # ========================================================
    # REVENUE VS PROFIT OPTIMA
    # ========================================================

    st.divider()

    st.markdown(
        "## Revenue vs Profit Optimization"
    )

    r1, r2, r3 = st.columns(3)

    r1.metric(
        "Revenue-Max Price",
        f"{result['revenue_maximizing_price']:.2f}"
    )

    r2.metric(
        "Profit-Max Price",
        f"{result['profit_maximizing_price']:.2f}"
    )

    r3.metric(
        "Expected Profit at Optimum",
        f"{result['expected_profit_at_profit_optimum']:.2f}"
    )


    # ========================================================
    # SCENARIOS
    # ========================================================

    scenarios = pd.DataFrame(
        result["scenarios"]
    )

    st.divider()

    st.markdown(
        "## Pricing Scenario Analysis"
    )

    scenario_table = scenarios.copy()

    display_cols = [
        col
        for col in [
            "price",
            "forecast_demand",
            "expected_revenue",
            "expected_profit",
            "gross_margin_pct"
        ]
        if col in scenario_table.columns
    ]

    st.dataframe(
        scenario_table[display_cols],
        use_container_width=True,
        hide_index=True
    )


    # ========================================================
    # PROFESSIONAL CURVES
    # ========================================================

    left, right = st.columns(2)


    with left:

        st.markdown(
            "### Revenue Curve"
        )

        revenue_chart = (
            alt.Chart(
                scenarios
            )
            .mark_line(
                point=True,
                strokeWidth=3
            )
            .encode(
                x=alt.X(
                    "price:Q",
                    title="Candidate Price"
                ),

                y=alt.Y(
                    "expected_revenue:Q",
                    title="Expected Revenue"
                ),

                tooltip=[
                    alt.Tooltip(
                        "price:Q",
                        format=".2f"
                    ),

                    alt.Tooltip(
                        "expected_revenue:Q",
                        format=".2f"
                    ),

                    alt.Tooltip(
                        "forecast_demand:Q",
                        format=".2f"
                    )
                ]
            )
            .properties(
                height=330
            )
        )

        st.altair_chart(
            revenue_chart,
            use_container_width=True
        )


    with right:

        st.markdown(
            "### Profit Curve"
        )

        profit_chart = (
            alt.Chart(
                scenarios
            )
            .mark_line(
                point=True,
                strokeWidth=3
            )
            .encode(
                x=alt.X(
                    "price:Q",
                    title="Candidate Price"
                ),

                y=alt.Y(
                    "expected_profit:Q",
                    title="Expected Profit"
                ),

                tooltip=[
                    alt.Tooltip(
                        "price:Q",
                        format=".2f"
                    ),

                    alt.Tooltip(
                        "expected_profit:Q",
                        format=".2f"
                    ),

                    alt.Tooltip(
                        "forecast_demand:Q",
                        format=".2f"
                    )
                ]
            )
            .properties(
                height=330
            )
        )

        st.altair_chart(
            profit_chart,
            use_container_width=True
        )


    # ========================================================
    # DEMAND RESPONSE
    # ========================================================

    st.markdown(
        "### Demand Response"
    )

    demand_chart = (
        alt.Chart(
            scenarios
        )
        .mark_line(
            point=True,
            strokeWidth=3
        )
        .encode(
            x=alt.X(
                "price:Q",
                title="Price"
            ),

            y=alt.Y(
                "forecast_demand:Q",
                title="Forecast Demand"
            ),

            tooltip=[
                alt.Tooltip(
                    "price:Q",
                    format=".2f"
                ),

                alt.Tooltip(
                    "forecast_demand:Q",
                    format=".2f"
                )
            ]
        )
        .properties(
            height=300
        )
    )

    st.altair_chart(
        demand_chart,
        use_container_width=True
    )


    # ========================================================
    # GOVERNANCE
    # ========================================================

    governance = result.get(
        "governance_checks",
        {}
    )

    if governance:

        st.divider()

        st.markdown(
            "## Governance Status"
        )

        labels = {
            "elasticity_accepted":
                "Elasticity Accepted",

            "automatic_recommendation":
                "Auto Recommendation",

            "price_within_guardrails":
                "Within Guardrails",

            "price_above_unit_cost":
                "Above Unit Cost",

            "positive_expected_profit":
                "Positive Expected Profit"
        }

        cols = st.columns(
            len(labels)
        )

        for col, (
            key,
            label
        ) in zip(
            cols,
            labels.items()
        ):

            with col:

                passed = governance.get(
                    key,
                    False
                )

                if passed:

                    st.html(
                        f"""
                        <div class="governance-card">
                            ✓ {label}
                        </div>
                        """
                    )

                else:

                    st.error(
                        f"Review · {label}"
                    )


    # ========================================================
    # TECHNICAL TRACEABILITY
    # ========================================================

    with st.expander(
        "Technical decision details"
    ):

        st.write(
            "**Technical Product ID:**",
            result["item_id"]
        )

        st.write(
            "**Snapshot Date:**",
            result.get(
                "snapshot_date",
                "N/A"
            )
        )

        st.json(result)


else:

    st.info(
        """
        Select a product, provide unit cost and pricing guardrail,
        then run the AI Pricing Decision.
        """
    )


st.caption(
    """
    AI Demand & Pricing Engine · Pricing Decision Intelligence
    """
)
'''

page.write_text(
    new_page,
    encoding="utf-8"
)

print(
    "Profit Optimization redesigned successfully!"
)

print(
    "Backup:",
    backup
)

Profit Optimization redesigned successfully!
Backup: dashboard\backups\3_Profit_Optimization_backup.py

In [203]:
from pathlib import Path

text = Path("dashboard/app.py").read_text(
    encoding="utf-8"
)

print(
    "New Executive Overview installed:",
    "Executive Snapshot" in text
)

print(
    "Old homepage still present:",
    "Elasticity Landscape" in text
)

New Executive Overview installed: False
Old homepage still present: True

In [204]:
from pathlib import Path
import shutil

page = Path("dashboard/app.py")

backup_dir = Path("dashboard/backups")
backup_dir.mkdir(
    parents=True,
    exist_ok=True
)

backup = (
    backup_dir
    / "app_before_executive_redesign.py"
)

if page.exists() and not backup.exists():
    shutil.copy(page, backup)


new_page = r'''
import sys
from pathlib import Path

import altair as alt
import pandas as pd
import requests
import streamlit as st


# ============================================================
# PROJECT
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from dashboard.ui import (
    apply_professional_style,
    friendly_product_name,
    clean_model_name
)


# ============================================================
# PAGE
# ============================================================

st.set_page_config(
    page_title="AI Pricing Intelligence",
    page_icon="◈",
    layout="wide"
)

apply_professional_style()

API_URL = "http://127.0.0.1:8001"


# ============================================================
# EXECUTIVE STYLING
# ============================================================

st.html(
    """
    <style>

    .hero {
        padding: 1rem 0 2rem 0;
    }

    .eyebrow {
        font-size: .72rem;
        font-weight: 700;
        letter-spacing: .13em;
        text-transform: uppercase;
        color: #64748b;
    }

    .hero-title {
        font-size: 2.7rem;
        font-weight: 760;
        letter-spacing: -.05em;
        line-height: 1.05;
        color: #0f172a;
        margin-top: .4rem;
    }

    .hero-copy {
        color: #64748b;
        font-size: 1rem;
        max-width: 880px;
        line-height: 1.6;
        margin-top: .8rem;
    }

    .chip-row {
        display: flex;
        flex-wrap: wrap;
        gap: .55rem;
        margin-top: 1rem;
    }

    .chip {
        display: inline-block;
        padding: .34rem .72rem;
        border-radius: 999px;
        background: #f1f5f9;
        border: 1px solid #e2e8f0;
        color: #334155;
        font-size: .74rem;
        font-weight: 650;
    }

    .chip-online {
        background: #ecfdf5;
        border-color: #bbf7d0;
        color: #166534;
    }

    .hero-card {
        border: 1px solid #e2e8f0;
        background: #ffffff;
        border-radius: 16px;
        padding: 1.25rem 1.35rem;
        min-height: 155px;
    }

    .card-eyebrow {
        font-size: .7rem;
        font-weight: 700;
        letter-spacing: .08em;
        text-transform: uppercase;
        color: #64748b;
    }

    .card-big {
        margin-top: .25rem;
        font-size: 2rem;
        font-weight: 740;
        letter-spacing: -.04em;
        color: #0f172a;
    }

    .card-copy {
        margin-top: .4rem;
        font-size: .78rem;
        color: #64748b;
        line-height: 1.45;
    }

    .positive {
        color: #15803d;
        font-weight: 700;
    }

    .decision-card {
        padding: 1.25rem 1.35rem;
        border-radius: 16px;
        border: 1px solid #dbeafe;
        background: #f8fbff;
    }

    .product-name {
        font-size: 1.25rem;
        font-weight: 720;
        color: #0f172a;
    }

    .decision-copy {
        color: #475569;
        line-height: 1.65;
        margin-top: .65rem;
    }

    .stage-card {
        border: 1px solid #e2e8f0;
        background: #ffffff;
        border-radius: 14px;
        padding: 1rem 1.05rem;
        min-height: 138px;
    }

    .stage-number {
        font-size: .68rem;
        font-weight: 700;
        color: #2563eb;
        letter-spacing: .08em;
    }

    .stage-title {
        font-size: .95rem;
        font-weight: 700;
        color: #0f172a;
        margin-top: .35rem;
    }

    .stage-copy {
        font-size: .75rem;
        line-height: 1.45;
        color: #64748b;
        margin-top: .35rem;
    }

    .benchmark-box {
        border: 1px solid #e2e8f0;
        border-radius: 15px;
        padding: 1.1rem 1.2rem;
        background: #ffffff;
    }

    .benchmark-title {
        font-size: .72rem;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: .07em;
        color: #64748b;
    }

    .benchmark-number {
        font-size: 1.8rem;
        font-weight: 730;
        letter-spacing: -.04em;
        margin-top: .25rem;
    }

    .benchmark-foot {
        font-size: .76rem;
        color: #64748b;
        margin-top: .3rem;
    }

    </style>
    """
)


# ============================================================
# DATA LOADERS
# ============================================================

@st.cache_data(ttl=120)
def backend_health():

    response = requests.get(
        f"{API_URL}/health",
        timeout=4
    )

    response.raise_for_status()

    return response.json()


@st.cache_data(ttl=300)
def model_info():

    response = requests.get(
        f"{API_URL}/model-info",
        timeout=10
    )

    response.raise_for_status()

    return response.json()


@st.cache_data(ttl=300)
def portfolio_info():

    response = requests.get(
        f"{API_URL}/portfolio-opportunities",
        params={
            "top_n": 10,
            "max_change_pct": 0.10
        },
        timeout=90
    )

    response.raise_for_status()

    return response.json()


@st.cache_data
def elasticity_data():

    path = (
        BASE_DIR
        / "data"
        / "master_product_elasticities.csv"
    )

    return pd.read_csv(path)


try:

    health = backend_health()
    model = model_info()
    portfolio_payload = portfolio_info()

    engine_online = True

except Exception:

    engine_online = False


if not engine_online:

    st.error(
        "FastAPI backend is offline. Start the backend on port 8001."
    )

    st.stop()


elasticity = elasticity_data()

portfolio = pd.DataFrame(
    portfolio_payload["opportunities"]
)


# ============================================================
# PORTFOLIO STATISTICS
# ============================================================

total_products = len(elasticity)

manual_review = int(
    (
        elasticity["classification"]
        == "Investigate"
    ).sum()
)

auto_eligible = total_products - manual_review

evaluation = model["evaluation"]
baseline = model["baseline"]

mae_improvement = float(
    model["computed_metrics"][
        "mae_improvement_vs_baseline_pct"
    ]
)

rmse_improvement = (
    (baseline["rmse"] - evaluation["rmse"])
    / baseline["rmse"]
    * 100
)

r2_gain = (
    evaluation["r2"]
    - baseline["r2"]
)


# ============================================================
# HERO
# ============================================================

st.html(
    f"""
    <div class="hero">

        <div class="eyebrow">
            AI decision intelligence
        </div>

        <div class="hero-title">
            AI Pricing Intelligence Platform
        </div>

        <div class="hero-copy">
            An end-to-end machine-learning pricing system combining
            SKU-level demand forecasting, price elasticity,
            revenue and profit optimization, commercial guardrails,
            portfolio prioritization and human-in-the-loop governance.
        </div>

        <div class="chip-row">

            <span class="chip chip-online">
                ● Engine Online
            </span>

            <span class="chip">
                {clean_model_name(model["model_type"])}
            </span>

            <span class="chip">
                {total_products} Products Modeled
            </span>

            <span class="chip">
                16 Automated Tests Passed
            </span>

        </div>

    </div>
    """
)


# ============================================================
# EXECUTIVE KPIs
# ============================================================

st.markdown("## Executive Snapshot")

c1, c2, c3, c4 = st.columns(4)


with c1:

    st.html(
        f"""
        <div class="hero-card">
            <div class="card-eyebrow">Products Modeled</div>
            <div class="card-big">{total_products:,}</div>
            <div class="card-copy">
                SKU-level elasticity coverage across the modeled portfolio.
            </div>
        </div>
        """
    )


with c2:

    st.html(
        f"""
        <div class="hero-card">
            <div class="card-eyebrow">Auto-Recommend Eligible</div>
            <div class="card-big">{auto_eligible:,}</div>
            <div class="card-copy positive">
                {auto_eligible / total_products * 100:.1f}% of modeled products
            </div>
        </div>
        """
    )


with c3:

    st.html(
        f"""
        <div class="hero-card">
            <div class="card-eyebrow">Human Review</div>
            <div class="card-big">{manual_review:,}</div>
            <div class="card-copy">
                Routed to manual validation because elasticity requires investigation.
            </div>
        </div>
        """
    )


with c4:

    st.html(
        f"""
        <div class="hero-card">
            <div class="card-eyebrow">Forecast Error Reduction</div>
            <div class="card-big">{mae_improvement:.1f}%</div>
            <div class="card-copy positive">
                Lower MAE versus lag-1 baseline
            </div>
        </div>
        """
    )


# ============================================================
# MODEL BENCHMARK
# ============================================================

st.divider()

st.markdown("## Model Benchmark")

st.caption(
    "Performance on the chronological 28-day holdout."
)

b1, b2, b3 = st.columns(3)


with b1:

    st.html(
        f"""
        <div class="benchmark-box">
            <div class="benchmark-title">Mean Absolute Error</div>
            <div class="benchmark-number">{evaluation["mae"]:.3f}</div>
            <div class="benchmark-foot">
                Baseline {baseline["mae"]:.3f}
                ·
                <span class="positive">{mae_improvement:.1f}% lower</span>
            </div>
        </div>
        """
    )


with b2:

    st.html(
        f"""
        <div class="benchmark-box">
            <div class="benchmark-title">Root Mean Squared Error</div>
            <div class="benchmark-number">{evaluation["rmse"]:.3f}</div>
            <div class="benchmark-foot">
                Baseline {baseline["rmse"]:.3f}
                ·
                <span class="positive">{rmse_improvement:.1f}% lower</span>
            </div>
        </div>
        """
    )


with b3:

    st.html(
        f"""
        <div class="benchmark-box">
            <div class="benchmark-title">R² Score</div>
            <div class="benchmark-number">{evaluation["r2"]:.3f}</div>
            <div class="benchmark-foot">
                Baseline {baseline["r2"]:.3f}
                ·
                <span class="positive">+{r2_gain:.3f}</span>
            </div>
        </div>
        """
    )


# ============================================================
# TOP COMMERCIAL OPPORTUNITY
# ============================================================

if not portfolio.empty:

    best = (
        portfolio
        .sort_values(
            "expected_revenue_gain",
            ascending=False
        )
        .iloc[0]
    )

    friendly = friendly_product_name(
        best["item_id"]
    )

    action = (
        "Increase"
        if best["recommended_price"] > best["current_price"]
        else
        "Decrease"
        if best["recommended_price"] < best["current_price"]
        else
        "Hold"
    )


    st.divider()

    st.markdown(
        "## Highest-Priority Commercial Opportunity"
    )

    st.html(
        f"""
        <div class="decision-card">

            <div class="product-name">
                {friendly}
            </div>

            <div class="decision-copy">

                Recommended action:
                <b>{action}</b>

                &nbsp;·&nbsp;

                Price:
                <b>{best["current_price"]:.2f}</b>
                →
                <b>{best["recommended_price"]:.2f}</b>

                <br><br>

                Expected revenue gain:
                <b>{best["expected_revenue_gain"]:.2f}</b>

                &nbsp;·&nbsp;

                Expected uplift:
                <b>{best["expected_revenue_uplift_pct"]:.2f}%</b>

                &nbsp;·&nbsp;

                Elasticity:
                <b>{best["elasticity"]:.3f}</b>

            </div>

        </div>
        """
    )


# ============================================================
# GOVERNANCE
# ============================================================

st.divider()

st.markdown(
    "## Portfolio Governance"
)

left, right = st.columns(
    [1.05, 1]
)


governance_df = pd.DataFrame(
    {
        "Decision Route": [
            "Auto-Recommend",
            "Human Review"
        ],
        "Products": [
            auto_eligible,
            manual_review
        ]
    }
)


with left:

    governance_chart = (
        alt.Chart(
            governance_df
        )
        .mark_arc(
            innerRadius=72,
            outerRadius=115
        )
        .encode(
            theta="Products:Q",
            color=alt.Color(
                "Decision Route:N",
                title=None
            ),
            tooltip=[
                "Decision Route:N",
                "Products:Q"
            ]
        )
        .properties(
            height=320
        )
    )

    st.altair_chart(
        governance_chart,
        use_container_width=True
    )


with right:

    st.markdown(
        "### Human-in-the-Loop Policy"
    )

    st.write(
        """
        Products with economically coherent elasticity estimates
        can enter the automated recommendation workflow.
        """
    )

    st.write(
        """
        Products classified as **Investigate** are deliberately
        excluded from automatic repricing and routed to manual review.
        """
    )

    st.success(
        f"{auto_eligible} products currently qualify "
        "for automated decision support."
    )

    st.warning(
        f"{manual_review} products remain under human review."
    )


# ============================================================
# WORKFLOW
# ============================================================

st.divider()

st.markdown(
    "## Decision Intelligence Workflow"
)

s1, s2, s3, s4 = st.columns(4)


with s1:

    st.html(
        """
        <div class="stage-card">
            <div class="stage-number">01 · FORECAST</div>
            <div class="stage-title">Demand Intelligence</div>
            <div class="stage-copy">
                Predict SKU demand using price, lag signals,
                rolling demand and calendar features.
            </div>
        </div>
        """
    )


with s2:

    st.html(
        """
        <div class="stage-card">
            <div class="stage-number">02 · UNDERSTAND</div>
            <div class="stage-title">Price Elasticity</div>
            <div class="stage-copy">
                Estimate product-level price sensitivity
                and identify economically coherent recommendations.
            </div>
        </div>
        """
    )


with s3:

    st.html(
        """
        <div class="stage-card">
            <div class="stage-number">03 · OPTIMIZE</div>
            <div class="stage-title">Revenue & Profit</div>
            <div class="stage-copy">
                Simulate candidate prices and identify
                revenue-maximizing and profit-maximizing decisions.
            </div>
        </div>
        """
    )


with s4:

    st.html(
        """
        <div class="stage-card">
            <div class="stage-number">04 · GOVERN</div>
            <div class="stage-title">Decision Control</div>
            <div class="stage-copy">
                Apply pricing guardrails, profitability checks
                and human-review controls before recommendations are surfaced.
            </div>
        </div>
        """
    )


st.caption(
    """
    AI Demand & Pricing Engine ·
    Machine-Learning Pricing Decision Intelligence Platform
    """
)
'''

page.write_text(
    new_page,
    encoding="utf-8"
)

print("Executive Overview redesigned successfully!")
print("Backup:", backup)

Executive Overview redesigned successfully!
Backup: dashboard\backups\app_before_executive_redesign.py

In [205]:
from pathlib import Path

print("MAIN:")
print(Path("dashboard/app.py"))

print("\nPAGES:")
for p in sorted(Path("dashboard/pages").glob("*.py")):
    print(p)

MAIN:
dashboard\app.py

PAGES:
dashboard\pages\1_Product_Intelligence.py
dashboard\pages\3_Model_Performance.py
dashboard\pages\3_Profit_Optimization.py
dashboard\pages\4_Governance.py
dashboard\pages\4_Portfolio_Opportunities.py
dashboard\pages\5_Model_Monitoring.py

In [206]:
from pathlib import Path

renames = {
    "dashboard/app.py":
        "dashboard/Executive_Overview.py",

    "dashboard/pages/1_Product_Intelligence.py":
        "dashboard/pages/1_Product_Intelligence.py",

    "dashboard/pages/3_Model_Performance.py":
        "dashboard/pages/2_Model_Performance.py",

    "dashboard/pages/3_Profit_Optimization.py":
        "dashboard/pages/3_Pricing_Decision.py",

    "dashboard/pages/4_Portfolio_Opportunities.py":
        "dashboard/pages/4_Portfolio_Radar.py",

    "dashboard/pages/5_Model_Monitoring.py":
        "dashboard/pages/5_Model_Intelligence.py",

    "dashboard/pages/4_Governance.py":
        "dashboard/pages/6_Governance.py",
}

for old_name, new_name in renames.items():

    old = Path(old_name)
    new = Path(new_name)

    if old == new:
        print("Kept:", old)
        continue

    if old.exists():

        old.rename(new)
        print(
            "Renamed:",
            old.name,
            "→",
            new.name
        )

    elif new.exists():

        print(
            "Already renamed:",
            new.name
        )

    else:

        print(
            "Not found:",
            old
        )


print("\nNavigation files cleaned successfully!")

Renamed: app.py → Executive_Overview.py
Kept: dashboard\pages\1_Product_Intelligence.py
Renamed: 3_Model_Performance.py → 2_Model_Performance.py
Renamed: 3_Profit_Optimization.py → 3_Pricing_Decision.py
Renamed: 4_Portfolio_Opportunities.py → 4_Portfolio_Radar.py
Renamed: 5_Model_Monitoring.py → 5_Model_Intelligence.py
Renamed: 4_Governance.py → 6_Governance.py

Navigation files cleaned successfully!

In [3]:
from pathlib import Path

readme = r"""
# AI Pricing Intelligence Platform

An end-to-end machine-learning decision platform for demand forecasting, SKU-level price elasticity, revenue and profit optimization, portfolio prioritization, and governed pricing recommendations.

---

## Overview

The AI Pricing Intelligence Platform transforms historical retail demand and pricing data into actionable pricing decisions.

The system combines:

- Demand forecasting
- Product-level price elasticity estimation
- Revenue optimization
- Profit optimization
- Automated pricing recommendations
- Commercial pricing guardrails
- Portfolio opportunity ranking
- Human-in-the-loop governance
- Model monitoring and explainability
- FastAPI backend
- Streamlit decision dashboard

The project is built around the M5 retail dataset and currently models **659 products**.

---

## Business Problem

Retail pricing decisions require balancing several objectives:

- Maintain customer demand
- Improve revenue
- Protect profitability
- Understand price sensitivity
- Avoid unrealistic price movements
- Identify the highest-value pricing opportunities
- Keep risky recommendations under human supervision

This project turns those requirements into an ML-powered pricing decision workflow.

---

## Key Results

### Demand Forecasting

Model:

**HistGradientBoostingRegressor**

Chronological 28-day holdout performance:

| Metric | AI Model | Lag-1 Baseline |
|---|---:|---:|
| MAE | 1.092 | 1.348 |
| RMSE | 2.034 | 2.761 |
| R² | 0.680 | 0.411 |

The model reduces MAE by approximately **19% versus the baseline**.

---

## Portfolio Coverage

- **659** modeled products
- **424** eligible for automated recommendation
- **235** routed to human review
- **19** products classified as elastic
- Product-level elasticity estimates
- Portfolio-wide pricing opportunity ranking

---

## Demand Forecasting Features

The forecasting model currently uses:

- `sell_price`
- `day_of_week`
- `month`
- `year`
- `demand_lag_1`
- `demand_lag_7`
- `rolling_mean_7`
- `rolling_mean_28`

Feature importance is evaluated using permutation importance on held-out observations.

---

## Price Elasticity

Product-level price sensitivity is estimated using controlled Poisson regression models.

Products are classified into categories such as:

- Elastic
- Inelastic
- Investigate

Products with suspicious or economically incoherent elasticity estimates are automatically routed to manual review.

Elasticity estimates should be interpreted as observational decision-support estimates rather than causal effects.

---

## Pricing Optimization

For eligible products, the engine:

1. Retrieves the latest product information
2. Forecasts demand
3. Loads product elasticity
4. Generates candidate prices
5. Simulates demand response
6. Estimates expected revenue
7. Estimates expected profit
8. Applies pricing guardrails
9. Selects the recommended price
10. Generates an executive decision explanation

The system supports both:

- Revenue-maximizing pricing
- Profit-maximizing pricing

---

## Governance

The platform includes a human-in-the-loop decision layer.

Automatic recommendations require:

- Accepted elasticity estimate
- Product eligible for automation
- Recommended price inside configured guardrails
- Recommended price above unit cost
- Positive expected profit

Products failing governance checks remain under manual review.

---

## Portfolio Opportunity Radar

The portfolio engine ranks the strongest pricing opportunities across eligible SKUs.

For each product it provides:

- Current price
- Recommended price
- Price change %
- Forecast demand
- Expected revenue
- Expected revenue gain
- Expected revenue uplift
- Elasticity
- Classification

This allows decision-makers to prioritize commercial actions across the portfolio.

---

## Model Explainability

The platform includes predictive explainability through permutation feature importance.

Current strongest predictors include:

- Rolling 7-day mean demand
- Rolling 28-day mean demand
- Lagged demand
- Day of week
- Selling price

These importance values describe predictive contribution and should not be interpreted as causal effects.

---

## Technology Stack

### Machine Learning
- Python
- NumPy
- pandas
- scikit-learn
- HistGradientBoostingRegressor
- Poisson regression
- joblib

### Backend
- FastAPI
- Pydantic
- Uvicorn

### Frontend
- Streamlit
- Altair

### Testing
- pytest
- FastAPI TestClient

### Development
- Jupyter Notebook
- Anaconda

---

## API

Main FastAPI endpoints include:

```text
GET  /
GET  /health
GET  /elasticity/{item_id}
POST /forecast
POST /recommend-price
GET  /recommend-auto/{item_id}
POST /recommend-profit-auto
GET  /portfolio-opportunities
GET  /model-info
GET  /feature-importance

_IncompleteInputError: incomplete input (1962144337.py, line 3)

In [2]:
from pathlib import Path

readme_path = Path("README.md")

print("Project folder:", Path.cwd())
print("README target:", readme_path.resolve())

Project folder: C:\Users\iliasso\AI_Demand_Pricing_Engine
README target: C:\Users\iliasso\AI_Demand_Pricing_Engine\README.md

In [4]:
from pathlib import Path

readme_lines = [
    "# AI Pricing Intelligence Platform",
    "",
    "An end-to-end machine-learning decision platform for demand forecasting, "
    "SKU-level price elasticity, revenue and profit optimization, portfolio prioritization, "
    "and governed pricing recommendations.",
    "",
    "## Project Overview",
    "",
    "The platform transforms historical retail demand and pricing data into controlled "
    "commercial pricing decisions.",
    "",
    "It combines:",
    "",
    "- Demand forecasting",
    "- Product-level price elasticity",
    "- Revenue optimization",
    "- Profit optimization",
    "- Automated pricing recommendations",
    "- Commercial guardrails",
    "- Portfolio opportunity ranking",
    "- Human-in-the-loop governance",
    "- Model monitoring and explainability",
    "- FastAPI backend",
    "- Streamlit decision dashboard",
    "",
    "The current system models **659 retail products**.",
    "",
    "## Business Problem",
    "",
    "Pricing teams need to balance demand, revenue, profitability and customer price sensitivity "
    "while avoiding unrealistic or risky automated price changes.",
    "",
    "This project turns forecasting and elasticity estimates into governed pricing recommendations "
    "that can be reviewed at product and portfolio level.",
    "",
    "## Key Results",
    "",
    "| Metric | AI Model | Lag-1 Baseline |",
    "| --- | ---: | ---: |",
    "| MAE | 1.092 | 1.348 |",
    "| RMSE | 2.034 | 2.761 |",
    "| R² | 0.680 | 0.411 |",
    "",
    "**MAE improvement versus baseline: ~19%**",
    "",
    "Evaluation uses a chronological 28-day holdout.",
    "",
    "## Portfolio Coverage",
    "",
    "- 659 modeled products",
    "- 424 auto-recommend eligible products",
    "- 235 products routed to human review",
    "- 19 products classified as elastic",
    "- Portfolio-wide opportunity ranking",
    "",
    "## Demand Forecasting",
    "",
    "Forecasting model: **HistGradientBoostingRegressor**",
    "",
    "Current features:",
    "",
    "- sell_price",
    "- day_of_week",
    "- month",
    "- year",
    "- demand_lag_1",
    "- demand_lag_7",
    "- rolling_mean_7",
    "- rolling_mean_28",
    "",
    "## Price Elasticity",
    "",
    "Product-level price sensitivity is estimated using controlled Poisson regression models.",
    "",
    "Products are classified as **Elastic**, **Inelastic**, or **Investigate**.",
    "",
    "Products with suspicious or economically incoherent elasticity estimates are prevented "
    "from automatic repricing and routed to human review.",
    "",
    "> Elasticity estimates are observational decision-support estimates and should not be interpreted as causal effects.",
    "",
    "## Pricing Optimization",
    "",
    "For eligible products, the engine forecasts demand, retrieves elasticity, generates candidate prices, "
    "simulates demand response, estimates revenue and profit, applies commercial guardrails, and produces "
    "an executive recommendation.",
    "",
    "The platform supports both **revenue-maximizing** and **profit-maximizing** pricing.",
    "",
    "## Governance",
    "",
    "Automatic recommendations require:",
    "",
    "- Accepted elasticity",
    "- Automation eligibility",
    "- Price inside configured guardrails",
    "- Price above unit cost",
    "- Positive expected profit",
    "",
    "Products failing these checks remain under human review.",
    "",
    "## Portfolio Opportunity Radar",
    "",
    "The portfolio engine ranks high-value repricing opportunities using:",
    "",
    "- Current price",
    "- Recommended price",
    "- Price change",
    "- Forecast demand",
    "- Expected revenue gain",
    "- Expected revenue uplift",
    "- Elasticity",
    "- Product classification",
    "",
    "## Model Explainability",
    "",
    "Permutation feature importance is calculated using held-out forecasting observations.",
    "",
    "The strongest predictive signals include rolling demand, lagged demand, calendar effects and price.",
    "",
    "> Predictive importance should not be interpreted as causal importance.",
    "",
    "## Technology Stack",
    "",
    "**Machine Learning:** Python, NumPy, pandas, scikit-learn, HistGradientBoostingRegressor, Poisson regression, joblib",
    "",
    "**Backend:** FastAPI, Pydantic, Uvicorn",
    "",
    "**Frontend:** Streamlit, Altair",
    "",
    "**Testing:** pytest, FastAPI TestClient",
    "",
    "**Development:** Jupyter Notebook, Anaconda",
    "",
    "## API",
    "",
    "Main endpoints:",
    "",
    "```text",
    "GET  /",
    "GET  /health",
    "GET  /elasticity/{item_id}",
    "POST /forecast",
    "POST /recommend-price",
    "GET  /recommend-auto/{item_id}",
    "POST /recommend-profit-auto",
    "GET  /portfolio-opportunities",
    "GET  /model-info",
    "GET  /feature-importance",
    "```",
    "",
    "Local Swagger documentation:",
    "",
    "```text",
    "http://127.0.0.1:8001/docs",
    "```",
    "",
    "## Dashboard",
    "",
    "The Streamlit application includes:",
    "",
    "- Executive Overview",
    "- Product Intelligence",
    "- Model Performance",
    "- Pricing Decision",
    "- Portfolio Radar",
    "- Model Intelligence",
    "- Governance",
    "",
    "## Automated Testing",
    "",
    "The project currently passes **16 automated tests** covering the API, pricing logic, "
    "commercial guardrails, portfolio ranking, model information and feature importance.",
    "",
    "```text",
    "16 passed",
    "```",
    "",
    "## Architecture",
    "",
    "```text",
    "M5 Retail Data",
    "      ↓",
    "Feature Engineering",
    "      ↓",
    "Demand Forecasting",
    "      ↓",
    "Product-Level Elasticity",
    "      ↓",
    "Pricing Simulation",
    "      ↓",
    "Revenue & Profit Optimization",
    "      ↓",
    "Governance Layer",
    "      ↓",
    "FastAPI Decision Engine",
    "      ↓",
    "Streamlit Decision Intelligence Platform",
    "```",
    "",
    "## Running Locally",
    "",
    "Start the backend:",
    "",
    "```bash",
    "python -m uvicorn api.app:app --host 127.0.0.1 --port 8001",
    "```",
    "",
    "Start the frontend:",
    "",
    "```bash",
    "python -m streamlit run dashboard/Executive_Overview.py",
    "```",
    "",
    "Run automated tests:",
    "",
    "```bash",
    "python -m pytest tests -v",
    "```",
    "",
    "## Limitations",
    "",
    "- Elasticity estimates are observational rather than causal.",
    "- Historical demand does not guarantee future demand.",
    "- Profit optimization currently relies on supplied unit cost.",
    "- Recommendations should be validated before real production use.",
    "- Current evaluation uses lag-based one-step-ahead predictions rather than a fully recursive 28-day forecast.",
    "",
    "## Future Improvements",
    "",
    "- Recursive multi-step forecasting",
    "- Inventory constraints",
    "- Promotion effects",
    "- Competitor pricing",
    "- Prediction uncertainty",
    "- Drift monitoring",
    "- Automated retraining",
    "- Cloud deployment",
    "- CI/CD",
    "- Docker containerization",
    "",
    "## Project Positioning",
    "",
    "**Data engineering → forecasting → price sensitivity → optimization → API engineering → "
    "decision dashboard → explainability → governance → automated testing**",
    "",
    "The objective is not only to predict demand, but to transform model outputs into controlled, "
    "interpretable and commercially actionable pricing decisions.",
]

readme_text = "\n".join(readme_lines)

Path("README.md").write_text(
    readme_text,
    encoding="utf-8"
)

print("README.md created successfully!")
print("Saved to:", Path("README.md").resolve())
print("Lines:", len(readme_lines))

README.md created successfully!
Saved to: C:\Users\iliasso\AI_Demand_Pricing_Engine\README.md
Lines: 237

In [5]:
from pathlib import Path

requirements = [
    "# Core data stack",
    "numpy",
    "pandas",
    "scipy",
    "",
    "# Machine learning / econometrics",
    "scikit-learn",
    "statsmodels",
    "joblib",
    "",
    "# Backend API",
    "fastapi",
    "uvicorn[standard]",
    "pydantic",
    "",
    "# Dashboard",
    "streamlit",
    "altair",
    "requests",
    "",
    "# Testing",
    "pytest",
    "httpx",
    "",
    "# Analysis / notebooks",
    "matplotlib",
    "jupyter",
]

Path("requirements.txt").write_text(
    "\n".join(requirements) + "\n",
    encoding="utf-8"
)

print("requirements.txt created successfully!")
print("Saved to:", Path("requirements.txt").resolve())
print()
print(Path("requirements.txt").read_text(encoding="utf-8"))

requirements.txt created successfully!
Saved to: C:\Users\iliasso\AI_Demand_Pricing_Engine\requirements.txt

# Core data stack
numpy
pandas
scipy

# Machine learning / econometrics
scikit-learn
statsmodels
joblib

# Backend API
fastapi
uvicorn[standard]
pydantic

# Dashboard
streamlit
altair
requests

# Testing
pytest
httpx

# Analysis / notebooks
matplotlib
jupyter

In [6]:
from pathlib import Path

root = Path(".")

print("PROJECT CONTENTS:\n")

for path in sorted(root.rglob("*")):
    if path.is_file():
        size_kb = path.stat().st_size / 1024
        print(f"{path}  |  {size_kb:.1f} KB")

PROJECT CONTENTS:

.gitignore  |  0.5 KB
.ipynb_checkpoints\01_data_exploration.-checkpoint.ipynb  |  227.9 KB
.pytest_cache\.gitignore  |  0.0 KB
.pytest_cache\CACHEDIR.TAG  |  0.2 KB
.pytest_cache\README.md  |  0.3 KB
.pytest_cache\v\cache\lastfailed  |  0.0 KB
.pytest_cache\v\cache\nodeids  |  0.9 KB
01_data_exploration..ipynb  |  551.4 KB
api\.ipynb_checkpoints\app-checkpoint.py  |  9.3 KB
api\__pycache__\app.cpython-313.pyc  |  9.1 KB
api\app.py  |  9.3 KB
dashboard\__pycache__\ui.cpython-313.pyc  |  3.8 KB
dashboard\backups\3_Profit_Optimization_backup.py  |  7.7 KB
dashboard\backups\4_Portfolio_Opportunities_backup.py  |  5.6 KB
dashboard\backups\5_Model_Monitoring_backup.py  |  7.7 KB
dashboard\backups\app_before_executive_redesign.py  |  5.6 KB
dashboard\Executive_Overview.py  |  16.4 KB
dashboard\pages\1_Product_Intelligence.py  |  2.3 KB
dashboard\pages\2_Model_Performance.py  |  1.6 KB
dashboard\pages\3_Pricing_Decision.py  |  15.1 KB
dashboard\pages\4_Portfolio_Radar.py  |  17.9 KB
dashboard\pages\5_Model_Intelligence.py  |  17.9 KB
dashboard\pages\6_Governance.py  |  1.8 KB
dashboard\ui.py  |  3.8 KB
data\calendar.csv  |  101.0 KB
data\elasticity_results_checkpoint.csv  |  105.0 KB
data\latest_product_features.csv  |  241.3 KB
data\master_product_elasticities.csv  |  59.4 KB
data\portfolio_opportunities.csv  |  3.6 KB
data\sales_train_evaluation.csv  |  118883.3 KB
data\sales_train_validation.csv  |  117195.0 KB
data\sample_submission.csv  |  5106.2 KB
data\sell_prices.csv  |  198628.7 KB
models\demand_forecaster.joblib  |  331.5 KB
models\feature_importance.csv  |  0.5 KB
models\features.json  |  0.1 KB
models\model_metadata.json  |  0.8 KB
README.md  |  6.0 KB
requirements.txt  |  0.3 KB
requirements_full.txt  |  31.8 KB
src\__pycache__\pricing_engine.cpython-313.pyc  |  16.9 KB
src\pricing_engine.py  |  27.0 KB
tests\__pycache__\test_project.cpython-313-pytest-8.4.2.pyc  |  43.8 KB
tests\test_project.py  |  7.0 KB

In [7]:
from pathlib import Path

gitignore_lines = [
    "# ==================================================",
    "# Python",
    "# ==================================================",
    "__pycache__/",
    "*.py[cod]",
    "*.pyo",
    "",
    "# ==================================================",
    "# Jupyter",
    "# ==================================================",
    ".ipynb_checkpoints/",
    "",
    "# ==================================================",
    "# Testing",
    "# ==================================================",
    ".pytest_cache/",
    "",
    "# ==================================================",
    "# Local environments",
    "# ==================================================",
    ".venv/",
    "venv/",
    "env/",
    ".env",
    "",
    "# ==================================================",
    "# IDE / OS",
    "# ==================================================",
    ".vscode/",
    ".idea/",
    ".DS_Store",
    "Thumbs.db",
    "",
    "# ==================================================",
    "# Dashboard development backups",
    "# ==================================================",
    "dashboard/backups/",
    "",
    "# ==================================================",
    "# Large raw M5 dataset files",
    "# Re-download from the official M5 dataset source",
    "# ==================================================",
    "data/sales_train_evaluation.csv",
    "data/sales_train_validation.csv",
    "data/sell_prices.csv",
    "data/sample_submission.csv",
    "data/calendar.csv",
    "",
    "# ==================================================",
    "# Environment dumps / temporary dependency files",
    "# ==================================================",
    "requirements_full.txt",
    "",
    "# ==================================================",
    "# Logs / temporary files",
    "# ==================================================",
    "*.log",
    "*.tmp",
    "*.temp",
]

Path(".gitignore").write_text(
    "\n".join(gitignore_lines) + "\n",
    encoding="utf-8"
)

print(".gitignore created successfully!")
print("Saved to:", Path(".gitignore").resolve())

.gitignore created successfully!
Saved to: C:\Users\iliasso\AI_Demand_Pricing_Engine\.gitignore

In [8]:
from pathlib import Path

folders = [
    "assets",
    "assets/screenshots",
    "assets/architecture",
]

for folder in folders:
    Path(folder).mkdir(
        parents=True,
        exist_ok=True
    )

print("Portfolio asset folders created successfully!")

print("\nFINAL PROJECT STRUCTURE:\n")

for p in sorted(Path(".").iterdir()):
    if p.name.startswith(".") and p.name != ".gitignore":
        continue

    if p.is_dir():
        print(f"[DIR]  {p.name}/")
    else:
        size_kb = p.stat().st_size / 1024
        print(f"[FILE] {p.name} — {size_kb:.1f} KB")

Portfolio asset folders created successfully!

FINAL PROJECT STRUCTURE:

[FILE] .gitignore — 1.5 KB
[FILE] 01_data_exploration..ipynb — 556.4 KB
[DIR]  api/
[DIR]  assets/
[DIR]  dashboard/
[DIR]  data/
[DIR]  docs/
[DIR]  models/
[FILE] README.md — 6.0 KB
[FILE] requirements.txt — 0.3 KB
[FILE] requirements_full.txt — 31.8 KB
[DIR]  src/
[DIR]  tests/

In [9]:
from pathlib import Path

path = Path("README.md")
text = path.read_text(encoding="utf-8")

visual_section = "\n".join([
    "",
    "## Platform Preview",
    "",
    "### Executive Overview",
    "",
    "![Executive Overview](assets/screenshots/01_executive_overview.png)",
    "",
    "### AI Pricing Decision",
    "",
    "![Pricing Decision](assets/screenshots/02_pricing_decision.png)",
    "",
    "### Portfolio Opportunity Radar",
    "",
    "![Portfolio Radar](assets/screenshots/03_portfolio_radar.png)",
    "",
    "### Model Performance & Explainability",
    "",
    "![Model Intelligence](assets/screenshots/04_model_intelligence.png)",
    "",
    "## System Architecture",
    "",
    "![AI Pricing Intelligence Architecture](assets/architecture/system_architecture.png)",
    "",
])

marker = "## Business Problem"

if "## Platform Preview" not in text:
    text = text.replace(
        marker,
        visual_section + "\n" + marker
    )
    path.write_text(text, encoding="utf-8")
    print("README visuals connected successfully!")
else:
    print("README visual section already exists.")

README visuals connected successfully!

In [15]:
from pathlib import Path

assets = [
    "assets/screenshots/01_executive_overview.png",
    "assets/screenshots/02_pricing_decision.png",
    "assets/screenshots/03_portfolio_radar.png",
    "assets/screenshots/04_model_intelligence.png",
    "assets/architecture/system_architecture.png",
]

print("GITHUB VISUAL ASSET CHECK\n")

all_ok = True

for file in assets:
    p = Path(file)

    if p.exists():
        size_kb = p.stat().st_size / 1024
        print(f"✅ {file} — {size_kb:.1f} KB")
    else:
        print(f"❌ MISSING: {file}")
        all_ok = False

print()
print("READY FOR GITHUB:", all_ok)

GITHUB VISUAL ASSET CHECK

✅ assets/screenshots/01_executive_overview.png — 242.5 KB
✅ assets/screenshots/02_pricing_decision.png — 236.3 KB
✅ assets/screenshots/03_portfolio_radar.png — 229.2 KB
✅ assets/screenshots/04_model_intelligence.png — 231.4 KB
✅ assets/architecture/system_architecture.png — 1621.8 KB

READY FOR GITHUB: True

In [14]:
from pathlib import Path
import shutil

desktop = Path.home() / "Desktop"

# Correct project destinations
screenshots_target = Path("assets/screenshots")
architecture_target = Path("assets/architecture")

screenshots_target.mkdir(parents=True, exist_ok=True)
architecture_target.mkdir(parents=True, exist_ok=True)

# Your accidentally-created Desktop folders
screenshots_source = desktop / "CUsersiliassoAI_Demand_Pricing_Engineassetsscreenshots"
architecture_source = desktop / "system_architecture.png"

# Copy the four screenshots
expected = [
    "01_executive_overview.png",
    "02_pricing_decision.png",
    "03_portfolio_radar.png",
    "04_model_intelligence.png",
]

for filename in expected:
    src = screenshots_source / filename
    dst = screenshots_target / filename

    if src.exists():
        shutil.copy2(src, dst)
        print("✅ Copied:", filename)
    else:
        print("❌ Missing:", src)

# Copy the architecture image
architecture_files = [
    p for p in architecture_source.iterdir()
    if p.is_file() and p.suffix.lower() == ".png"
]

if architecture_files:
    shutil.copy2(
        architecture_files[0],
        architecture_target / "system_architecture.png"
    )
    print("✅ Copied: system_architecture.png")
else:
    print("❌ Architecture image not found")

print("\nDONE")

✅ Copied: 01_executive_overview.png
✅ Copied: 02_pricing_decision.png
✅ Copied: 03_portfolio_radar.png
✅ Copied: 04_model_intelligence.png
✅ Copied: system_architecture.png

DONE